### ISSUE TITLE
Asus RT-AC68U C1 Freezing..

### ISSUE THREAD

**Issue by diegonogueira** [RMerl/asuswrt-merlin.ng#100]
Hi, I bought this router this week and I'm facing same freezing.. 
Almost every day, the router freezes and I need to reboot it. Sometimes, when I reboot it freezes again..

I'm using the version: RT-AC68U_384.3_0

I don't know if it's a software or hardware issues.. 

[syslog.txt](https://www.dropbox.com/s/zktg5gl38itmpr5/syslog.txt.zip?dl=0)

Thanks!

**Comment by goetzc** [comment]
@diegonogueira the log cannot be seen without login, please upload it to [pastebin.com](http://pastebin.com) or similar sites.

Did you also experience this with the stock firmware?

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
