### ISSUE TITLE
openvpn*.postconf

### ISSUE THREAD

**Issue by MolotovMocktail** [RMerl/asuswrt-merlin.ng#101]
AFAICT, the ovpn client (and server) configurations are stored only in nvram, therefore references to [/tmp]/etc/openvpn/* fail.

e.g.

> Running /jffs/scripts/openvpnclient2.postconf (args: /etc/openvpn/client2/config.ovpn)

**Comment by RMerl** [comment]
That's incorrect.  Configuration files are dynamically generated when the service is started, like all other services.  That path is the correct one.

**Comment by MolotovMocktail** [comment]
Confirmed.  Thanks for the explanation.
