### ISSUE TITLE
mDNS not forwarding WLAN->LAN in AP mode

### ISSUE THREAD

**Issue by LukasQ** [RMerl/asuswrt-merlin.ng#102]
Hello Eric

Maybe I'm just a terrible admin, but unfortunately the service discovery (mDNS aka Bonjour aka avahi) does not pass from WLAN to LAN. I activated avahi on my pfsense, but the multicast packets seem to be blocked or not forwarded to the LAN interfaces on my AC66U. Background is: my [Home Assistant](https://github.com/home-assistant/home-assistant) instance checks for Chromecast Audio devices and finds nothing, whereby the App itself (all devices in WLAN) finds them and everything is fine.
Previouse DD-WRT installation on N66U did work with the same config.

AC66U, v380.69_2. All sorts of cluents.

Regards, Luke

**Comment by RMerl** [comment]
Closing, since 380.xx is no longer supported, neither is the RT-AC66U.
