### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vladut123** [RMerl/asuswrt-merlin.ng#103]
make -C router kernel -j`grep -c '^processor' /proc/cpuinfo`
make[1]: Entering directory '/home/vlad/asuswrt-merlin/release/src/router'
Makefile:15: /home/vlad/asuswrt-merlin/release/src-rt-6.x.4708/.config: No such file or directory
Makefile:57: *** empty variable name. Stop.
make[1]: Leaving directory '/home/vlad/asuswrt-merlin/release/src/router'
Makefile:440: recipe for target 'kernel' failed
make: *** [kernel] Error 2

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
