### ISSUE TITLE
"Enable Manual Assignment" toggle (LAN DHCP) has no effect

### ISSUE THREAD

**Issue by bughit** [RMerl/asuswrt-merlin.ng#104]
RT-AC68U_384.4_beta3

When set to "no", you can still assign IPs in the table below, and these assignments are respected.

**Comment by RMerl** [comment]
Can't reproduce here with 384.5-alpha3-ga12ef62.  When I disable manual assignment, entries stop being added to dnsmasq.conf as expected.

Don't forget that if your clients already own leases, these will stay there until they expire.
