### ISSUE TITLE
feature: independent 2.4/5 wifi toggle in the header/toolbar area

### ISSUE THREAD

**Issue by bughit** [RMerl/asuswrt-merlin.ng#105]
Currently toggling a particular radio on/off is rather cumbersome, requiring multiple clicks and navigations.

Would be nice to be be able to do it via a single click.

**Comment by RMerl** [comment]
Not technically doable, as toggling wifi requires service restarts, and therefore a webui reload.

A better location would be on the System Status iframe, as there is already code in place that would trigger a wireless restart (SSID/authentication can be changed there).
