### ISSUE TITLE
openvpn client nat problem

### ISSUE THREAD

**Issue by jstebbins** [RMerl/asuswrt-merlin.ng#106]
Running merlin 384.3 on an RT-AC68R.

I have an openvpn client configured with "Create NAT on tunnel" enabled.  When the vpn is brought up I can not ping hosts on the server side of the vpn.  But if I go to the firewall tab and simply "Apply" without making any changes, I can then access hosts across the vpn.  I logged the iptables nat and mangle tables after bringing up the the vpn and again after kicking the firewall.  There are differences in the nat table.  The mangle table does not change when kicking the firwall. But I'm not familiar enough with iptables syntax to understand what is broken.

Have I done something wrong, or have I found a bug?

nat table after starting vpn
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N DNSFILTER
-N LOCALSRV
-N PCREDIRECT
-N PUPNP
-N VSERVER
-N VUPNP
-A PREROUTING -d 71.229.176.97/32 -j VSERVER
-A PREROUTING ! -d 192.168.1.0/24 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.1.1:18017
-A PREROUTING -p udp -m udp --dport 53 -j DNAT --to-destination 192.168.1.1:18018
-A POSTROUTING -o eth0 -j PUPNP
-A POSTROUTING ! -s 71.229.176.97/32 -o eth0 -j MASQUERADE
-A POSTROUTING -s 192.168.1.0/24 -d 192.168.1.0/24 -o br0 -j MASQUERADE
-A VSERVER -p tcp -m tcp --dport 22 -j DNAT --to-destination 192.168.1.10:22
-A VSERVER -j VUPNP
```
nat table after kicking firewall
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N DNSFILTER
-N DNSVPN1
-N LOCALSRV
-N PCREDIRECT
-N PUPNP
-N VSERVER
-N VUPNP
-A PREROUTING -d 71.229.176.97/32 -j VSERVER
-A POSTROUTING -s 192.168.1.0/24 -o tun11 -j MASQUERADE
-A POSTROUTING -o eth0 -j PUPNP
-A POSTROUTING ! -s 71.229.176.97/32 -o eth0 -j MASQUERADE
-A POSTROUTING -s 192.168.1.0/24 -d 192.168.1.0/24 -o br0 -j MASQUERADE
-A VSERVER -p tcp -m tcp --dport 22 -j DNAT --to-destination 192.168.1.10:22
-A VSERVER -j VUPNP
```

**Comment by MichaelEFlip** [comment]
Similar problem here.
AsusWRT Merlin 384.6 @ AC86U is used as client to connect to OpenVPN server on Tomato router (site2site vpn).
From the AsusWRT subnet i can access all subnets from the OpenVPN server and other (tomato) clients subnets connected to the VPN.
From the server subnet and (tomato) client subnets i can not connect to the AsusWRT subnet.
