### ISSUE TITLE
System Status no longer displays ram and cpu usage 

### ISSUE THREAD

**Issue by harleythayer** [RMerl/asuswrt-merlin.ng#107]
On the main landing page after logging in the 380 firmware showed the cpu and ram usage under the "System Status"   384.3 shows the "System Status" but no ram or cpu info underneath it.  

I have an Asus RT-AC68U router.  Any ideas?

Pic of what I am talking about:
![asus](https://user-images.githubusercontent.com/26088020/37497017-2f73fec4-288c-11e8-99ae-c53a64dd0565.jpg)

**Comment by RMerl** [comment]
Clear your browser cache.

**Comment by harleythayer** [comment]
Thanks.  I thought I tried that.  It works now
