### ISSUE TITLE
Devices in different subnet than router does not show

### ISSUE THREAD

**Issue by Kalekulan** [RMerl/asuswrt-merlin.ng#108]
I'm using AC3200 with 384.3.

Router has (made-up) IP 192.168.24.1 and subnet mask 255.255.0.0.

Devices with IP 192.168.24.x shows up in client list on router webpage, but not devices with 192.168.y.x where y is not 24.

Devices are available and connected, but not showing up on web page.

**Comment by RMerl** [comment]
This is a known limitation, networkmap is hardcoded to a /24, and nothing I can do about it.
