### ISSUE TITLE
Connection type for devices connected via the 5Ghz network is not recognized correctly

### ISSUE THREAD

**Issue by mleko64** [RMerl/asuswrt-merlin.ng#110]
Hi,
I am running merlin 384.4_0 on an RT-AC87U (fresh flash + factory reset).
Every device which is connected via 5GHz network has wrong connection type in Network Map (Clients). 
Connection type for these devices is wired instead 5Ghz.
I also attach screenshots.

Thanks!
![1](https://user-images.githubusercontent.com/16608636/37672182-b53b4faa-2c6d-11e8-9836-581b1321ba56.PNG)
![2](https://user-images.githubusercontent.com/16608636/37672183-b556b83a-2c6d-11e8-88b7-a0927347a4c4.PNG)

**Comment by RMerl** [comment]
Known issue, will have to be fixed by Asus because networkmap code is now closed source.
