### ISSUE TITLE
Client Limit on 384.4?

### ISSUE THREAD

**Issue by mynameisdaniel32** [RMerl/asuswrt-merlin.ng#111]
I updated my RT-AC3200 to 384.4 yesterday and noticed intermittent problems with my 2.4G devices connecting. Seems it was maxing out at either 22 clients total (including ethernet and 5G as well) or 10 total 2.4G devices based on whoever was able to connect first.

I put it back on 384.3 and all devices (37 total, 25 on 2.4G) were able to connect again.

**Comment by RMerl** [comment]
The wifi code is closed source and outside of my control.
