### ISSUE TITLE
WiFi scheduler settings lost after reboot

### ISSUE THREAD

**Issue by drhelius** [RMerl/asuswrt-merlin.ng#118]
Running merlin 384.4_2 on an RT-AC86U.

WiFi scheduler runs fine on both 2.4 and 5 GHz bands but as soon as I reboot the router the scheduler settings are gone.

Rebooting or changing other settings that imply a WiFi reboot make the scheduler settings to disappear.

**Comment by RMerl** [comment]
Known issue on the RT-AC86U, will have to be fixed by Asus because the issue lies within closed source components.

A similar issue also exists for QoS settings.
