### ISSUE TITLE
Network Map shows 100%, htop shows 15%

### ISSUE THREAD

**Issue by kwloafman** [RMerl/asuswrt-merlin.ng#126]
The subject says it all.

![screen shot 2018-04-09 at 6 14 28 am](https://user-images.githubusercontent.com/158032/38494955-6d71de28-3bbd-11e8-8888-f6162f2d38ce.png)
<img width="1086" alt="screen shot 2018-04-09 at 6 15 56 am" src="https://user-images.githubusercontent.com/158032/38494992-931d1e9e-3bbd-11e8-8e68-f515d41255eb.png">

...Thanks,
...Ken

**Comment by pkohut** [comment]
Seeing this as well.
