### ISSUE TITLE
[PPTP Client] Kill Switch and Policy Routing

### ISSUE THREAD

**Issue by samip5** [RMerl/asuswrt-merlin.ng#130]
I wish to request a feature similar to the way OpenVPN is setup, so it has the kill switch and policy routing functionality, but for PPTP Clients.

How hard whould this be to implement?

**Comment by RMerl** [comment]
PPTP is obsolete technology that should not be used due to its security limitations.  Therefore I have no plan to devote any time toward the currently existing PPTP implementation, sorry.

**Comment by samip5** [comment]
Could you in that case just collebrate where to look for the correct files if I want to figure out myself how to do it?

Where are the files for the GUI and OpenVPN's policy routing related things?
