### ISSUE TITLE
Random reconnection issues on RT-AC88U

### ISSUE THREAD

**Issue by Zeebrah** [RMerl/asuswrt-merlin.ng#132]
Latest (384.4_2) firmware installed. Router is setup in AP mode since provider runs finer optic. Generally performance is great with decent coverage and top of the line speeds. However several devices have trouble reconnecting to the router (particularly on laptops after sleep mode was engaged). WIFI network is visible to the client however it won't connect saying that saved password is wrong. The only way I found to fix the issue is router reboot. Problem has already happened about 5 times so I don't think that is a random network interference bug. Will save the logs on the device once will observe such behaviour again.

**Comment by esbenfa** [comment]
I have sometimes the same problem on my RT-AC3200, also in AP mode. Firmware 380.69_0. Mostly on my laptop after sleep mode and a iphone/ipad (never on my android devices). Rebooting my router fix the problem.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
