### ISSUE TITLE
384.4_2 - RT-AC88U --- 2.4ghz radio stopped broadcasting

### ISSUE THREAD

**Issue by thezoggy** [RMerl/asuswrt-merlin.ng#134]
I noticed that some things werent working and saw that the 2.4ghz wireless network was not being shown... I turned off the radio and turned it back on. Now everything works again. The 'hide' option is not set... what can I check to see if something on the router crashed?

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
