### ISSUE TITLE
Quite frequent kernel: TCP: time wait bucket table overflow errors and freezes

### ISSUE THREAD

**Issue by rkkoszewski** [RMerl/asuswrt-merlin.ng#136]
Hi, every now and then I get the log flooded with kernel: TCP: time wait bucket table overflow errors. I'm not sure why this happens. The only thing that is noticeable is that during this time the whole network seems frozen during some time till it recovers. Any idea why could be causing this? (Router: RT-AC68U)

I haven't noticed anything in particular triggering it, and it sometimes even happens when there are only 2 clients connected to the router. So I'm not sure what is causing this. But it happens quite frequently, sometimes even several times during one day.

Here is a Log excerpt which doesn't seem to tell much:

> Apr 20 22:02:55 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: net_ratelimit: 482 callbacks suppressed
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:02 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: net_ratelimit: 726 callbacks suppressed
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:07 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: net_ratelimit: 926 callbacks suppressed
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:12 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: net_ratelimit: 218 callbacks suppressed
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow
> Apr 20 22:03:19 kernel: TCP: time wait bucket table overflow

**Comment by RMerl** [comment]
You have something generating a lot of TCP sessions on your network - not a bug in the firmware.  I recommend using the support forums at SNBForums for further torubleshooting.
