### ISSUE TITLE
Enhanced user script support

### ISSUE THREAD

**Issue by fantom-x** [RMerl/asuswrt-merlin.ng#138]
For a long time now I was missing the support for user scripts via the use of folders like **firewall-start.d**, etc. This way all those additional features that require the use of the user script functionality could just drop their scripts into an appropriate folder without a risk of overwriting the existing files. 
I am offering to implement and test this if it has a chance of being useful others and eventually merged.

**Comment by RMerl** [comment]
I don't want to make things more complicated for end-user.  Changing the user script behaviour at this point by going for an init.d-similar setup would make things very confusing for new users, who would be facing both the previously implemented scripts in addition to a folder-based system.

At this point in this firmware's age, I believe it's too late for such a radical design decision change.

**Comment by fantom-x** [comment]
Good point, but I was not suggesting a replacement. It would be backwards compatible and not mutually exclusive. The handler would generate a new script under **/tmp/** and put the original one on the first line followed by alfabetically ordered **ng** scripts.

**Comment by samip5** [comment]
Idea is so if that kind of setup exists, use it and if not failback to the one in use now?

**Comment by RMerl** [comment]
Don't have any plans to change the way custom scripts are currently implemented.
