### ISSUE TITLE
OpenVPN Listening IP adress

### ISSUE THREAD

**Issue by yelkarama** [RMerl/asuswrt-merlin.ng#141]
When openvpn starts, is listen to all IP addresses:

lsof -i tcp -P 2>/dev/null| grep LIST | grep vpn
vpnserver 1275     root    9u  IPv6   4383      0t0  TCP *:11949 (LISTEN)

IMO, it should listen only to the WAN ip address. 

The reason I'm raising this issue is that, to be able to connect from work, The only ports I can use are 80 and 443. When I use one of them from OpenVPN, it doesn't allow pixelserv to start.

**Comment by RMerl** [comment]
OpenVPN doesn't allow specifying on which interface it should listen.  You can only specify the local IP, which would break whenever your WAN IP changed.

If you have a static IP, you could try setting it in the custom field:

```
local 1.2.3.4
```
