### ISSUE TITLE
ip6tables nat is not supported

### ISSUE THREAD

**Issue by wilenka** [RMerl/asuswrt-merlin.ng#143]
Hi everyone, I'm using RT-N66U (**380.70**), I know that it is now not supported. but...
if you will fix this in NG, could you please add nat support also for ipv6 for legacy branch. :)

Linux ASUS 2.6.22.19 #1 Sun Apr 8 14:03:49 EDT 2018 mips ASUSWRT-Merlin

ip6tables -t nat -L
modprobe: module ip6_tables not found in modules.dep
ip6tables v1.3.8: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

**Comment by RMerl** [comment]
Not possible, requires kernel 3.9.0 or newer.
