### ISSUE TITLE
How to prevent Guest Network users to access VPN Server Clients? Bug?

### ISSUE THREAD

**Issue by rkkoszewski** [RMerl/asuswrt-merlin.ng#145]
Hi,
I have connected two LANs via OpenVPN. My RT-AC68U is acting as OpenVPN Server (TUN), and the other Router connects to it allowing me to communicate with any device from the other LAN.

On my RT-AC68U I also have a Guest network, which has no access to my intranet. But to my surprise the Guest network seems to have complete access to any Client that is connected to my OpenVPN Server. The routes are also working, allowing anybody from my Guest Network to access the whole LAN on the other end. A simple network scan from the Guest Network reveals all the IPs from the other LAN, which is a huge problem.

Is there any way to block the Guest Network from communicating with the OpenVPN Clients? Basically allowing the connected clients to communicate **only** with my personal intranet.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
