### ISSUE TITLE
Kernel 4.1: Update to latest version

### ISSUE THREAD

**Issue by RMerl** [RMerl/asuswrt-merlin.ng#15]
Originally reported by: **Eric Sauvageau (Bitbucket: [RMerlin](https://bitbucket.org/RMerlin), GitHub: [RMerlin](https://github.com/RMerlin))**

----------------------------------------

See if it's possible to update to the latest 4.1.xx release.

----------------------------------------
- Bitbucket: https://bitbucket.org/RMerlin/am382/issue/15

**Comment by lilianmoraru** [comment]
The ancient kernel is probably the most problematic component in the entire system(mostly security-wise).

**Comment by someburner** [comment]
@RMerl I'm hacking around on my own flavor of tomato, loosely based on kille77's repo and a while back I attempted this. But a few patches in, realized it was going to be a substantial undertaking. I am willing to help with this- and since all these projects all use the same kernel more-or-less, it could be a joint effort. I just did a diff of vanilla 2.6.36.4 vs 7.x.main and it's actually not that bad from what I can tell. The majority of the changes are removing `#if 0`s and comments. Obviously there are some "real" edit, that would need attention, but I don't see a lot of hacks inside source files, and edits are documented.

That said, I am a bit confused with respect to ASUS/Broadcom because in 2.6.37, Broadcom submitted drivers for `mac80211`. But we are all still using `wl` and `dhd` in binary form, supplied by ASUS. So then my read on the situation is that Broadcom has moved on and ASUS doesn't want to do this?

**Comment by RMerl** [comment]
This is a completely different thing.  I'm referring to the Broadcom HND platform which is based on 4.1.21 - it's an LTS branch, but it's not the latest release of that LTS branch.  I wouldn't be changing kernel release, just updating to the latest minor release for that specific 4.1 release.

wl and dhd are far more advanced than whatever is built in the kernel.  dhd for instance will run an actual firmware on the SoC's own CPU.

**Comment by fantom-x** [comment]
@RMerl Broadcom have indeed made a lot of customizations, but patching from 4.1.27 to 4.1.51 was an easy thing to do with very few issues. Granted, I have not tried compiling anything yet; the next step is to set up a build env. Your second note mentions that getting to the latest 4.1 kernel would be a tricky thing, so I must be missing something here. Were you referring to more than just applying kernel patches?

**Comment by RMerl** [comment]
I was referring to the amount of work and testing that would be required with such a merge due to the large number of changes - not something I'm willing to devote time to at the moment.

**Comment by fantom-x** [comment]
Was just checking to see if that is something that I could do. So far there have been zero conflicts with the Broadcom code, but I have not tried compiling yet.

**Comment by RMerl** [comment]
See if it compiles and passes basic tests (booting, connecting wifi, etc...).  If it does, feel free to provide a pull request so we can get this tested by a larger audience.

**Comment by RMerl** [comment]
I just pushed a new kernel41upd branch to Github, I suggest using that branch for kernel 4.1 update tests.

Ideally, I'd like to have separate merges for each patches (i.e. one for 4.1.28, one for 4.1.29, etc...), with a mention in the commit message if anything had to be changed/adjusted to deal with BCM's own changes.  This will make it easier to track things down if something ends up breaking down the line and we want to try fixing it.

Your file size looks good, however anytime something gets touched in the kernel, it's best to ensure you have a working firmware at hand, and are able to use firmware recovery mode in case the kernel fails to boot.  Recovery Mode seemed to work a bit differently on the RT-AC86U versus older models, so make sure you test it out before you proceed with flashing a test build.

If it fails to boot, then a serial interface might be required for proper troubleshooting (but not necessary for rrecovery).

Cc: @themiron  (as he might want to keep track of this issue)

**Comment by fantom-x** [comment]
Thx for the warning about the recovery mode, but can you pls clarify what you mean by **Recovery Mode seemed to work a bit differently on the RT-AC86U versus older models** ? My only experience with with RT-N66U, which was non-brickable.

I assume the process below is the correct one?

Q: How do I put the router into Recovery Mode?
A: Turn the router off. Press the reset button, and while keeping it pressed turn it back on. Wait a few seconds until the power led blinks, and then release the reset button. Router will now be in Recovery Mode, reachable at 192.168.1.1.

**Comment by fantom-x** [comment]
It booted the first time, no problems connecting over wired or WiFi. No issues browsing the portal. Right after I loaded this image, the portal started giving me some weird warnings that the router settings changed and I need to reboot or something. Seemed to go away once I reset to factory defaults.
This is not my main router yet, so the amount of testing I have performed so far is very limited.

uname -a
Linux RT-AC86U-B568 **4.1.51** #2 SMP PREEMPT Sat Apr 21 19:57:24 EDT 2018 aarch64 ASUSWRT-Merlin

**Comment by themiron** [comment]
what about bwdpi, ntfs, nat offload?

**Comment by fantom-x** [comment]
@themiron  Any specific tests in mind?

**Comment by RMerl** [comment]
Enable every Trend Micro-related features, then make sure they still work (test the malicious website blocking for instance), and check that syslog doesn't show any error message, especially when loading the bwdpi-related modules.

For tntfs, plug a USB disk that's formatted in NTFS, and make sure it can be read by the router.

For nat offload, you'll have to check that both runner and flow cache can be loaded and are working.  Easiest test is to look the syslog and dmesg for any unusual error message (comparing the boot log with a regular 4.1.27 boot log).  Ideally, test throughput by running iperf on the LAN and the WAN side of the router, ensuring you can hit near to 1 Gbps of NAT throughput.

**Comment by fantom-x** [comment]
HW NAT test. I do not have access to a bare metal Linux box, so have to improvise and use my VM. One iperf was running on my main router, an RT-AC86U connected to it, my laptop connected to the RT-AC86U, and an iperf endpoint in a Linux VM is running on the laptop. I checked the CPU usage on my main router (one perf endpoint) and it was at 100%. It is close enough to 1Gbps, I think, considering a router being an endpoint.

```
[  5]  0.0-10.0 sec  1023 MBytes   858 Mbits/sec
[  5]  0.0-10.0 sec  1.00 GBytes   860 Mbits/sec
[  5]  0.0-10.0 sec   980 MBytes   822 Mbits/sec
```

<img width="685" alt="screen shot 2018-04-22 at 5 49 23 pm" src="https://user-images.githubusercontent.com/5624569/39100290-8c314c02-4655-11e8-989d-28397cecc327.png">

**Comment by fantom-x** [comment]
Found this error message, but I do not have a clean log to check if it is present there:

**Comment by fantom-x** [comment]
I am gonna compile the **4.1.51** kernel sources without a version number change and see it it bricks the router...

**Comment by fantom-x** [comment]
No luck: **tdts** modules have loaded, but not **tntfs** and others. Also, **Runner** is now being disabled almost right after the boot. I guess, it is a big NO to the whole idea...

```
Apr 22 20:00:52 kernel: tfat: loading out-of-tree module taints kernel.                
Apr 22 20:00:52 kernel: tfat: Unknown symbol inode_change_ok (err 0)       
Apr 22 20:00:52 modprobe: can't load module tfat (kernel/fs/tfat.ko): unknown symbol in module, or unknown parameter
Apr 22 20:00:52 kernel: tntfs: Unknown symbol inode_change_ok (err 0)                                           
Apr 22 20:00:52 modprobe: can't load module tntfs (kernel/fs/tntfs.ko): unknown symbol in module, or unknown parameter
Apr 22 20:00:52 kernel: thfsplus: Unknown symbol inode_change_ok (err 0)     
Apr 22 20:00:52 modprobe: can't load module thfsplus (kernel/fs/thfsplus.ko): unknown symbol in module, or unknown parameter

```

**Comment by RMerl** [comment]
I guess there were some struct changes with at least one of the updates past 4.1.27.  Not totally unexpected.

Thanks for taking the time to give it a try, at least now we know our answer.  Best that might be possible would be backporting some select patches, probably more trouble than it's worth it at this time unless some very specific patches are deemed critical enough to backport.

**Comment by fantom-x** [comment]
**inode_change_ok** wa removed in **4.1.37**, so it might be possible to go up to **4.1.36**, but doubt it makes sense.

**Comment by fantom-x** [comment]
On the second thought, I want to ask for your opinion here. There could still be a case for people like me who use their routers as originally intended and nothing more. I do not need those modules that did not load as I would never enable those services to begin with. But I do like the way you integrated other features and I have use cases for them. 
I am not asking you to do anything, but do you see any issues with running this firmware with the latest kernel, but without the proprietary blobs/features?

**Comment by RMerl** [comment]
Some of the proprietary modules could be removed.  Tuxera, you could probably recompile the firmware with NTFS set to use Open instead of Tuxera.  However other modules like bwdpi cannot be removed, as various closed source portions for rc or shared are compiled expecting these features to be enabled at compile time.  Recompiling the firmware without bwdpi support would require complete source code for httpd/rc/shared.

**Comment by RMerl** [comment]
Going to close this since tests has shown it couldn't be done.
