### ISSUE TITLE
384.5 - RT-AC87U - After upgrading the router still says the version is 384.4_2

### ISSUE THREAD

**Issue by oittaa** [RMerl/asuswrt-merlin.ng#150]
As the title says, after flashing the newest firmware RT-AC87U_384.5_0.trx (SHA256 9eb8021418881a693a04d4dceaa43ea2167704da5e9583e45a1e59e978700ab5) the web interface still shows 384.4_2 as the version and the "A new version of firmware is now available." symbol keeps flashing.

https://i.imgur.com/ZUytuOJ.png

**Comment by oittaa** [comment]
@MacQwerty Thanks! It's not a very elegant workaround, but it worked.

**Comment by technomooney** [comment]
be sure you dont have any usb drives plugged in and it should upgrade... i have the same model router

**Comment by oittaa** [comment]
I didn't have any USB devices attached. Only couple of Ethernet cables are connected in addition to the power source.

**Comment by ookonbekend** [comment]
FYI, this worked for me,
First eject the USB disk and then updated the firmware.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.

**Comment by oittaa** [comment]
What do you mean with a comment like that? This is clearly about a bug in your software.

**Comment by kevinmarchant** [comment]
> be sure you dont have any usb drives plugged in and it should upgrade... i have the same model router

Thanks technomooney - this caught me out on the 384.7_2 to 384.9 upgrade.  Ejecting the USB stick and upgrade went without hitch.  Useful to know !

**Comment by isa220** [comment]
I do factory reset with JFFS and config backup, then I need flash 384.9 twice to complete firmware upgrade (after first flashing version still 384.5). it's no USB stick. same for 384.5 - I need to flash it twice to apply.
