### ISSUE TITLE
Wireless guest shows as wired interface

### ISSUE THREAD

**Issue by sectoramen** [RMerl/asuswrt-merlin.ng#157]
Ver. 384.5
Network Map -> View List -> All: shows a wired icon.
Network Map -> View List -> Interface: shows under wired.

Only 1 Guest network configured on 2.4 GHz
Time: Unlimited
Access Intranet: Off
No Bandwidth Limited
No MAC Filter

**Comment by Teddyz** [comment]
Until this is fixed by ASUS, is there a way to view a wireless guest's signal strength and data rate? Perhaps via ssh?
