### ISSUE TITLE
upgrade works but openVPN speed now intolerable...

### ISSUE THREAD

**Issue by proseLA** [RMerl/asuswrt-merlin.ng#160]
hi,
i've been using this firmware for quite some time.  i recently upgraded w/o problem; however when i connect via openVPN to the router, my network speed now becomes horrifically slow.  i'm more than willing to help on troubleshooting.  the previous version worked like a charm.  not sure what could have caused the speed issue; i have changed none of the openVPN settings on the router or on the client.  thanks.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
