### ISSUE TITLE
DSL-AC88U

### ISSUE THREAD

**Issue by Weggy** [RMerl/asuswrt-merlin.ng#161]
Hi,

Myself and I'm sure many others would be really greatful if you could support the DSL-AC88U. I'm assuming it's possible? Pleaseeeee! :)

Many Thanks!

**Comment by Weggy** [comment]
Looks like I'm sending this router back then

**Comment by vladut123** [comment]
Why is not possible

**Comment by crkinard** [comment]
It’s a hybrid dsl modem and router.

**Comment by vladut123** [comment]
Why is not possible to support the DSL-AC88U

**Comment by RMerl** [comment]
It does not run Asuswrt, it runs a completely different firmware.

**Comment by vladut123** [comment]
Which firmware it runs

**Comment by RMerl** [comment]
Whatever custom firmware Asus wrote for it.  I you want to know more, download their source code and look at it - I don`t know.

**Comment by vladut123** [comment]
Why you don't know

**Comment by RMerl** [comment]
Because I simply don`t care about that device?  Asus has well over 40 different networking devices.  I only focus on the high-end Broadcom devices that they manufacture, I don't analyze every single device that they manufacture...
