### ISSUE TITLE
Password length

### ISSUE THREAD

**Issue by sectoramen** [RMerl/asuswrt-merlin.ng#167]
Consider placing a notification/warning that the password length is 16 characters in or next to the password fields in the GUI. Those who use password managers to generate long passwords or type long passwords may not realize the password gets truncated in the GUI. I spend time troubleshooting SSH authentication issues because a 20 char password that was truncated without notification in the GUI did not work via SSH.

**Comment by RMerl** [comment]
Doing so would overload the webui.

What I am considering instead is to remove the size limitation from the input field, but do a length validation either on onblur() or on apply.

**Comment by RMerl** [comment]
Asus came up with a clever way to handle it with GPL 384_6210 (a bit similar to what I suggested in my previous comment): they now accept up to 17 characters in the input fields, however they issue a warning on apply if the length is longer than 16.

This will be merged in 384.13 for the RT-AX88U, and will eventually make it to the mainline branch as well.
