### ISSUE TITLE
Pick up kernel patch if it useful from linksys.

### ISSUE THREAD

**Issue by odkrys** [RMerl/asuswrt-merlin.ng#174]
Linksys made some of patches for their ea9300, ea9500v2 router which use bcm4908 chipset.
I expect if they are common and useful then you can pick them up.

https://drive.google.com/file/d/152f1woPac93EEa_Zc3BMbm9igaQZqUa4/view

https://drive.google.com/open?id=1nhA-KpAt1XS2SAxjeGNmX72KxgV62RWy

**Comment by RMerl** [comment]
ping @themiron

**Comment by RMerl** [comment]
Will require a lot of work to analyze each of them.  Different kernel version, at least one of those I checked seemed to be already patched in a much more comprehensive way in Asus's own code, etc...

**Comment by odkrys** [comment]
Yes, there is stem that seems to made by broadcom. It already applied on Asus's kernel.
But isn't the same 4.1.27 kernel on asus?

**Comment by RMerl** [comment]
You're right, sorry (for some reason I had 4.1.21 in mind).

**Comment by themiron** [comment]
I’ll take a look, thanks
