### ISSUE TITLE
IPv6 Broken in RT-AC5300 version 384.6

### ISSUE THREAD

**Issue by sectoramen** [RMerl/asuswrt-merlin.ng#175]
The router gets a LAN and WAN IPv6 address but is not sending router advertisements. 
![screenshot from 2018-07-27 15-34-25](https://user-images.githubusercontent.com/39841198/43343055-df930e1e-91b2-11e8-97e5-a1c260cacc5b.png)

**Comment by RMerl** [comment]
Look in the System Log for any error message related to dnsmasq.

**Comment by sectoramen** [comment]
No issues in the logs and one day later internal devices are starting to get IPv6 addresses. I am closing this and will keep an eye on it.
