### ISSUE TITLE
GT-AC5300 not listed as supported on Wiki and other documentation

### ISSUE THREAD

**Issue by traek** [RMerl/asuswrt-merlin.ng#181]
I find the GT-AC5300 is not listed supported on the Wiki and elsewhere. However, I do find it listed on asuswrt-merlin.ng/release/src/router/tools/Lnx_ToolHelp/DefaultModels.txt, hinting that is was or is somehow already supported through another (unreleased?) build.

Why the discrepancy? Is it officially supported? If so, can the RT-AC5300 release be used with modification? I'm happy to help play with mine if need be.

I found this release: asuswrt-merlin.ng/release/src-rt-5.02hnd/targets/cfe/sysdeps/GT-AC5300/ which shared it's release with (among other models) the RT-86U. The chipsets for the R/GT-AC5300 are almost identical and seem far off from the RT-86U and this commit is from a while ago.

I know I'm off into the weeds on this but is there a release that will support the GT-AC5300? I got it for the hardware not the firmware which is far too game focused for my taste.

**Comment by RMerl** [comment]
The GT-AC5300 is not supported by this project.  The Wiki and website documentation are correct.

What you are seeing are parts that are from the original Asuswrt firmware code.

The RT-AC5300 and GT-AC5300 are completely different devices.  One has a dual-core ARMv7 CPU, the other is a quad-core ARMv8 64-bit CPU.
