### ISSUE TITLE
Add information in "Asusnat tunnel"

### ISSUE THREAD

**Issue by DowngradeTheKernel** [RMerl/asuswrt-merlin.ng#184]
@RMerl @themiron Please add popup to help explain the option **Asusnat tunnel** on the router, I had to use google to understand what it was for.  (8 months without knowing what it was for and I hope I'm not wrong)

   - Tools -> Other Settings -> Disable Asusnat tunnel

**Example:**
Disable this option to get a better performance, because it eats a fair amount of CPU and RAM.

Only enable **Asusnat tunnel** if you use **IFTTT** or **Alexa** or **ASUS application** on cell phones.
(I recommend that you do not use any of that)

Source:
- [Disable Asusnat tunnel IFTTT: People having issues with it](https://www.snbforums.com/threads/release-384-ng-asuswrt-merlin-384-4-is-now-available.45406/page-12#post-390769)
- [ I think it's also used by Asus's AiHome product](https://www.snbforums.com/threads/release-382-asuswrt-merlin-382-1-is-now-available.42127/page-18#post-362122)
- [if you don't use IFTTT or Alexa then you can disable](https://www.snbforums.com/threads/preview-early-asuswrt-merlin-384-6-test-builds-are-available.47385/page-11#post-415473)
- [I have asked ASUS to clarify the function of ASUSNat Tunnel](http://whatsyourrouter.com/mybb/showthread.php?tid=304) (The answer of ASUS support)
- [turning on this setting "Disable Asusnat tunnel" Seems the crashing has stopped](https://www.snbforums.com/threads/2-4g-wifi-connectivity-problem.46639/page-2#post-422790)
- [Changelog 382.1 (12-Nov-2017)](http://asuswrt.lostrealm.ca/changelog-382) (**find:** Asus NAT)

**Comment by DowngradeTheKernel** [comment]
When I say add, I am referring to add popup to help explain what it is for.

**Comment by RMerl** [comment]
There's no definitive information as to how these services work and interact, therefore I can't document it.
