### ISSUE TITLE
AC68U spaming some DNS server

### ISSUE THREAD

**Issue by CHazz** [RMerl/asuswrt-merlin.ng#185]
hi i want to ask why the router continuously every few seconds spamming the address: dns.msftncsi.com? i do not use this DNS or any other .. i have my own DNS server .. what is it so? and why ? please remove this bug it is very unpleasant and I do not feel good about protecting the privacy of the data stream

**Comment by skeal1** [comment]
Try disabling this setting under the tools>other settings tab.  

Wan: Use DNS probes to determine if WAN is up (default: Yes) | Yes No
-- | --

**Comment by CHazz** [comment]
thanks i try :)

**Comment by RMerl** [comment]
This is by design, this is how Asus checks for the WAN state.  Windows uses the same nameserver to achieve the same result.

**Comment by expipiplus1** [comment]
@skeal1 This setting doesn't appear to be there in firmware version 384.13

**Comment by EsEnZeT** [comment]
Found out my way to this issue via my firewall logs & https://discourse.pi-hole.net/t/excessive-requests-for-dns-msftncsi-com/556/25

The only way to stop DNS spam was to **empty** first the:
- Resolve Hostname
- Resolved IP Addresses
under Administration -> System (Network Monitoring) then it can be saved with 'DNS Query' unchecked.
