### ISSUE TITLE
[Suggestion] Provide a metrics endpoint

### ISSUE THREAD

**Issue by mrueg** [RMerl/asuswrt-merlin.ng#187]
A router provides a nice set of data, that it would be interesting to monitor on.
It would be interesting to have a prometheus endpoint (https://prometheus.io) in this firmware, that would allow to monitor the connection to the WAN network as well as information about WIFI clients.

**Comment by RMerl** [comment]
This is beyond the scope of this project.  SNMP is the currently supported method of retrieving device information, any other method is up to the end-user.
