### ISSUE TITLE
Fix "reverse traffic" when using VPN - 100% confirmed solution!

### ISSUE THREAD

**Issue by DowngradeTheKernel** [RMerl/asuswrt-merlin.ng#188]
@RMerl @themiron These 2 protocols **PPTP** or **OpenVPN** the traffic is reversed, you can see it in **Bandwidth Monitor** or in a **Speed Test** and the **downloads** or **any other thing** are limited to the added value in **Upload Bandwidth**, but **L2TP** traffic is not reversed and has no problems.

There is already a Fix, but you have to install a script and I was wondering if you can do this a permanent solution:
- [QOS + VPN Client **fix traffic reversed** via custom rules by **FreshJR**](https://www.snbforums.com/threads/release-freshjr-adaptive-qos-improvements-custom-rules-and-inner-workings.36836/page-78#post-412034)

**Notes:** 
1. Please read completely the post, to understand the problem and how those **iptables** in the section **"Custom Rules for when the router is acting as a VPN Client"** fix it.
2. In **Bandwidth Monitor** you can still see the _reversed traffic_ but it **is only visual**, you can go to **QoS Statistics** or do a **Speed Test** and you can check that it **is fixed**.

I think the error is in the **iptables** of **OpenVPN** and only in **L2TP** are well configured, If you can see the **code/iptables** of them 3, I hope that you identify what is missing.

**Comment by Da5hes** [comment]
i recently started to use merlin and i also noticed this issue when using VPN client
would love to see a fix incorporated
