### ISSUE TITLE
Feature: Add half hour to parental controls time scheduling

### ISSUE THREAD

**Issue by Senate9690** [RMerl/asuswrt-merlin.ng#197]
If possible could you add the half hour increments to the time scheduling

**Comment by RMerl** [comment]
Not possible, would require overhauling large portions of the internal scheduler design (the scheduler itself does not support fractional hours), and the work of an advanced Javascript programmer to rewrite the Javascript calendar applet.  This is completely beyond the scope of this project, sorry.

**Comment by Senate9690** [comment]
Completely understand, was worth a shot... thanks!
