### ISSUE TITLE
Virtual Server/Port Forwarding disappear once AiProtection setting applied

### ISSUE THREAD

**Issue by hsabbagh** [RMerl/asuswrt-merlin.ng#207]
It seems as soon as I apply a "AiProtection - Time Scheduling" to a client all Port Forwarding settings disappear.

I am on 384.5 with RT-AC68U. And I have seen this issue in previous versions as well.

Amazing work man, keep up the excellent work!

**Comment by RMerl** [comment]
Unable to reproduce here, works properly for me.

**Comment by hsabbagh** [comment]
I have factory reset both my routers and now I cant reproduce either. I suspect some sort of incompatibility got nuked on factory reset.
