### ISSUE TITLE
Add support for Wireguard

### ISSUE THREAD

**Issue by yrzr** [RMerl/asuswrt-merlin.ng#210]
Is it possible to add support for Wireguard as an alternative to OpenVPN?

**Comment by RMerl** [comment]
No.  First reason being Wireguard requires a newer kernel , other reason is I don't want to have to develop and maintain yet another VPN protocol - too much work.

**Comment by masonesq** [comment]
I thought the kernel on my AC86U was more recent than what WireGuard requires.  

> [WireGuard requires Linux ≥3.10](https://www.wireguard.com/install/)

**Comment by RMerl** [comment]
That would mean only two models out of all supported models would be able to support it.

**Comment by r0bbie** [comment]
Understand the rationale behind not considering this, but hope there might be some possibility of it some point in the future.

**Comment by nobless** [comment]
Hi, any news here 2 years have gone, maybe kernels have been updated :) ?

**Comment by faux123** [comment]
> Hi, any news here 2 years have gone, maybe kernels have been updated :) ?

Device manufacturers don't change kernel base (too much effort involved with no return on investment), so for those devices stuck with the older kernels such as RT-AC68U etc, it won't happen.  Only RT-AC86U and RT-AX88U can run wireguard.

**Comment by PutinVladimir** [comment]
I compile this
https://github.com/WireGuard/wireguard-go
for mips ac66u, but can't create tun device neither from wireguard-go neither by hands...

**Comment by rvpn** [comment]
I use ac86u right now too, but i cannot find any step-by-step tutorial for non technical people like me. if somebody know please point me in the right direction. tq

**Comment by gitthangbaby** [comment]
i thought openvpn is pretty much dead. nothing has improved there for years - slow initialization and switching, huge cpu & battery burden on all devices, inability to cope with current ISP speeds by most top end home routers. in future, there's imo only one protocol to maintain: WG. pfsense switched this month, opnsense had support for some time. it's time.
