### ISSUE TITLE
Please make nvram wan0_gateway and wan_gateway in sync(same) in single WAN mode, 384.7

### ISSUE THREAD

**Issue by Originalimoc** [RMerl/asuswrt-merlin.ng#211]
wan_gateway won't be updated with wan0 or wan1 when using single WAN mode, loss some generatity in script writing.

**Comment by RMerl** [comment]
wan_gateway should not be used because it's not an instanced variable.  Indexed wan0_ and wan_1 should always be used.

**Comment by Originalimoc** [comment]
Ah, I thought it should be in sync because you can just use wan_* in Dual WAN Fail-back mode and single WAN as well.
So manually check wan0 wan1 availability and use one of them is a better solution?

**Comment by RMerl** [comment]
Yes.  There might be other variables to better indicate the state of the failback, but I don't touch the Dual WAN code so I have no idea.

**Comment by Originalimoc** [comment]
Leave it for now.
