### ISSUE TITLE
traceroute -I fails after a few hops

### ISSUE THREAD

**Issue by RMerl** [RMerl/asuswrt-merlin.ng#214]
When running traceroute using ICMP ECHO instead lf UDP datagrams, it fails after a few hops claiming "No buffer space available".

**Comment by RMerl** [comment]
Possible references:

https://bugzilla.redhat.com/show_bug.cgi?id=245438
https://bugs.launchpad.net/ubuntu/+source/traceroute/+bug/290145

**Comment by Originalimoc** [comment]
BusyBox stable version is now at 1.29.3, 384.7 running 1.25.1, since there's no version information of traceroute, try updating see if solves problem.
Or can just see the source code.

**Comment by RMerl** [comment]
Upgrading busybox is difficult, it's heavily patched by both Asus and Broadcom.
