### ISSUE TITLE
Namecheap DDNS not updating

### ISSUE THREAD

**Issue by waqaslam** [RMerl/asuswrt-merlin.ng#216]
Hi
I've been using asuswrt-merlin firmware on my AC-68U for last three years. I use my router to update the IP for my domain. However, after recently upgrading to **ver 384.7** my ddns has stopped working. When I force-update the dns and check the logs, it shows the following:

```
Oct 17 20:18:42 rc_service: httpd 265:notify_rc restart_ddns
Oct 17 20:18:43 start_ddns: update WWW.NAMECHEAP.COM namecheap, wan_unit 0
Oct 17 20:18:43 inadyn[1681]: In-a-dyn version 2.5 -- Dynamic DNS update client.
Oct 17 20:18:43 inadyn[1681]: Failed resolving hostname vpn: Name or service not known
Oct 17 20:18:44 inadyn[1681]: Update forced for alias vpn, new IP# XX.XXX.XX.XXX
Oct 17 20:18:45 inadyn[1681]: Updating cache for vpn
```
Just so you know, the domain I update is in a format like **vpn.xyz.com**, hence showing **vpn** in logs. Also the ip address is omitted purposely  :)

I wonder, if there's any known issue or is this feature broken in current release? and if there's any workaround/solution?

Thanks

**Comment by RMerl** [comment]
Already fixed, discussed (with workarounds) in issue #212 .
