### ISSUE TITLE
rt-AC88u wifi asus_5g keeps dropping every couple of minutes

### ISSUE THREAD

**Issue by slayer1957** [RMerl/asuswrt-merlin.ng#218]
Any suggestions from this logs why wifi keeps dropping?

`Oct 20 18:02:48 rc_service: ntp 305:notify_rc restart_diskmon
Oct 20 18:02:49 kernel: rtk port_phyEnableAll (on) ok
Oct 20 18:02:49 RT-AC88U: start httpd:80
Oct 20 18:02:50 httpd: Generating SSL certificate...
Oct 20 18:02:51 NAT_Tunnel: AAE Service is stopped
Oct 20 18:02:51 AAE: AAE Service is started
Oct 20 18:02:51 disk_monitor: be idle
Oct 20 18:02:51 Mastiff: init
Oct 20 18:02:52 jffs2: valid logs(1)
Oct 20 18:02:53 lldpd[469]: minimal kernel version required is 2.6.39, got 2.6.36.4brcmarm
Oct 20 18:02:53 lldpd[469]: lldpd may be unable to detect bonds and bridges correctly
Oct 20 18:02:53 lldpd[469]: consider recompiling with --enable-oldies option
Oct 20 18:02:53 lldpd[472]: could not open either /etc/os-release or /usr/lib/os-release
Oct 20 18:02:53 lldpd[472]: lsb_release information not available
Oct 20 18:02:53 lldpd[475]: created chroot directory /var/run/lldpd
Oct 20 18:02:53 lldpd[475]: protocol LLDP enabled
Oct 20 18:02:53 lldpd[475]: protocol CDPv1 disabled
Oct 20 18:02:53 lldpd[475]: protocol CDPv2 disabled
Oct 20 18:02:53 lldpd[475]: protocol SONMP disabled
Oct 20 18:02:53 lldpd[475]: protocol EDP disabled
Oct 20 18:02:53 lldpd[475]: protocol FDP disabled
Oct 20 18:02:53 lldpd[475]: libevent 2.0.21-stable initialized with epoll method
Oct 20 18:02:53 lldpd[475]: cannot get ethtool link information with GLINKSETTINGS (requires 4.9+): Operation not permitted
Oct 20 18:02:53 lldpd[475]: cannot get ethtool link information with GSET (requires 2.6.19+): Operation not permitted
Oct 20 18:02:53 lldpcli[473]: lldpd should resume operations
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 3
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 3
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 3
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 3
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 2
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 2
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 2
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 2
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 3
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 3
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 3
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 3
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 2
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 2
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 2
Oct 20 18:02:54 lldpd[475]: custom TLV op replace oui f8:32:e4 subtype 2
Oct 20 18:02:57 kernel: SCSI subsystem initialized
Oct 20 18:02:57 kernel: Initializing USB Mass Storage driver...
Oct 20 18:02:57 kernel: usbcore: registered new interface driver usb-storage
Oct 20 18:02:57 kernel: USB Mass Storage support registered.
Oct 20 18:02:57 kernel: Tuxera FAT 12/16/32 driver version 3015.1.29.6 [Flags: R/W MODULE].
Oct 20 18:02:57 kernel: Built against headers 2.6.36.4brcmarm #1 SMP PREEMPT Mon Dec 7 10:09:21 CST 2015 arm
Oct 20 18:02:57 kernel: Running on kernel 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jul 25 12:44:58 EDT 2018 armv7l
Oct 20 18:02:58 kernel: Tuxera NTFS driver 3015.1.29.16 [Flags: R/W MODULE].
Oct 20 18:02:58 kernel: Tuxera HFS+ driver 3014.7.28
Oct 20 18:02:58 kernel: usbcore: registered new interface driver usblp
Oct 20 18:02:58 disk_monitor: Finish
Oct 20 18:02:59 disk_monitor: be idle
Oct 20 18:04:25 rc_service: cfg_server 802:notify_rc restart_wireless
Oct 20 18:04:27 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:04:27 kernel: device eth1 left promiscuous mode
Oct 20 18:04:27 kernel: br0: port 2(eth1) entering disabled state
Oct 20 18:04:32 kernel: device eth1 entered promiscuous mode
Oct 20 18:04:32 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:04:32 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:08:00 rc_service: cfg_server 1107:notify_rc restart_wireless
Oct 20 18:08:01 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:08:01 kernel: device eth1 left promiscuous mode
Oct 20 18:08:01 kernel: br0: port 2(eth1) entering disabled state
Oct 20 18:08:06 kernel: device eth1 entered promiscuous mode
Oct 20 18:08:06 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:08:06 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:11:35 rc_service: cfg_server 1409:notify_rc restart_wireless
Oct 20 18:11:37 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:11:37 kernel: device eth1 left promiscuous mode
Oct 20 18:11:37 kernel: br0: port 2(eth1) entering disabled state
Oct 20 18:11:42 kernel: device eth1 entered promiscuous mode
Oct 20 18:11:42 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:11:42 kernel: br0: port 2(eth1) entering forwarding state
Oct 20 18:28:28 kernel: nvram: consolidating space!
Oct 20 20:04:48 syslogd started: BusyBox v1.25.1
Oct 20 20:04:48 kernel: klogd started: BusyBox v1.25.1 (2018-07-25 12:36:15 EDT)
Oct 20 20:07:10 syslogd started: BusyBox v1.25.1
Oct 20 20:07:10 kernel: klogd started: BusyBox v1.25.1 (2018-07-25 12:36:15 EDT)
Oct 20 20:09:14 syslogd started: BusyBox v1.25.1
Oct 20 20:09:14 kernel: klogd started: BusyBox v1.25.1 (2018-07-25 12:36:15 EDT)
Oct 20 20:16:43 syslogd started: BusyBox v1.25.1
Oct 20 20:16:43 kernel: klogd started: BusyBox v1.25.1 (2018-07-25 12:36:15 EDT)`

**Comment by slayer1957** [comment]
- Oct 20 18:08:06 kernel: br0: port 2(eth1) entering forwarding state 
Oct 20 18:08:06 kernel: br0: port 2(eth1) entering forwarding state 
Oct 20 18:11:35 rc_service: cfg_server 1409:notify_rc restart_wireless 
Oct 20 18:11:37 kernel: br0: port 2(eth1) entering forwarding state 
Oct 20 18:11:37 kernel: device eth1 left promiscuous mode 
Oct 20 18:11:37 kernel: br0: port 2(eth1) entering disabled state 
Oct 20 18:11:42 kernel: device eth1 entered promiscuous mode 
Oct 20 18:11:42 kernel: br0: port 2(eth1) entering forwarding state
 Oct 20 18:11:42 kernel: br0: port 2(eth1) entering forwarding state 
Oct 20 18:28:28 kernel: nvram: consolidating space!
 Oct 20 20:04:48 syslogd started: BusyBox v1.25.1 
Oct 20 20:04:48 kernel: klogd started: BusyBox v1.25.1 (2018-07-25 12:36:15 EDT) 
Oct 20 20:07:10 syslogd started: BusyBox v1.25.1 
Oct 20 20:07:10 kernel: klogd started: BusyBox v1.25.1 (2018-07-25 12:36:15 EDT)
 Oct 20 20:09:14 syslogd started: BusyBox v1.25.1 
Oct 20 20:09:14 kernel: klogd started: BusyBox v1.25.1 (2018-07-25 12:36:15 EDT) 
Oct 20 20:16:43 syslogd started: BusyBox v1.25.1 
Oct 20 20:16:43 kernel: klogd started: BusyBox v1.25.1 (2018-07-25 12:36:15 EDT)

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
