### ISSUE TITLE
dnsmasq version 2.80 Final (18/Oct/2018)

### ISSUE THREAD

**Issue by DowngradeTheKernel** [RMerl/asuswrt-merlin.ng#219]
@RMerl @themiron @john9527

dnsmasq v2.80 Final + other fixes...

http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=summary

**Comment by RMerl** [comment]
Merged with 2bc78a0a28fb04a97e6ab4ddccf34baab97e75ae .
