### ISSUE TITLE
Any fork/maintenance on EA6900 series available ?

### ISSUE THREAD

**Issue by ivnilv** [RMerl/asuswrt-merlin.ng#222]
Hi,

This is more like a general question to the maintainers or people familiar with the project:

Is there any project that continues to provide updates based on this project for the EA6900 Linksys routers ?

Thanks

**Comment by RMerl** [comment]
Running Asuswrt or Asuswrt-Merlin on non-Asus devices is illegal, due to the numerous components that are only licensed for use on Asus hardware.
