### ISSUE TITLE
inadyn.conf missing after reboot

### ISSUE THREAD

**Issue by flowercow** [RMerl/asuswrt-merlin.ng#224]
i use asuscomm as ddns, after i reboot the router(rt-ac66uB1), ddns can't work, i found there is no inadynb.conf in /etc, i must chose close the ddns client and reopen it, then the conf file appears. 

i don't know why this happened. I once moved this conf file away and touch a new one for test, after the test i moved it back. can this action cause this problem?  

3x

**Comment by RMerl** [comment]
That config file is dynamically generated when DDNS is enabled.  You cannot directly modify it, it gets recreated every time your reboot or DDNS is restarted - provided DDNS is enabled.

**Comment by flowercow** [comment]
i reboot my router again a moment ago, the conf file came out. It confused me, i'm sure that i didn't found this file in /etc after reboot.  i'll test later and feedback.
