### ISSUE TITLE
RT-AC1200G+

### ISSUE THREAD

**Issue by Mono5** [RMerl/asuswrt-merlin.ng#229]
Since I'm pretty bad with router source code (hard-bricked my last one), thought I could ask for help from someone more experienced with them. Couldn't find a functional build of other custom firmwares (tomato, openwrt, ddwrt). The official source for it can be downloaded straight from the [Asus Website](https://bit.ly/2QnZGNG).
Here is the cpuinfo, uname, nvram ports/clkfreq and df output: [shell.log](https://github.com/RMerl/asuswrt-merlin.ng/files/2616079/shell.log)

**Comment by RMerl** [comment]
Please use the forums at SNBForums for questions.
