### ISSUE TITLE
HDD mount fails

### ISSUE THREAD

**Issue by DanAspan** [RMerl/asuswrt-merlin.ng#230]
Router does not create /tmp/media at bootup and therefor also fails to mount usb hdd to that point
I am using a RT-AC66U_B1 with firmware 384.7_2

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
