### ISSUE TITLE
Advanced_VPN_OpenVPN.asp - Got `document.form.vpn_server_custom2 is undefined`

### ISSUE THREAD

**Issue by olivierberthomme** [RMerl/asuswrt-merlin.ng#231]
Missing a change from `custom2` to `cust2` ? in file Advanced_VPN_OpenVPN.asp line 352 (applyRule()) in else block of test `if  #(isSupport("hnd"))`

Tested with Firefox 63 - Asus AC68U - Firmware 384.8
Thanks !

_Originally posted by @olivierberthomme in https://github.com/RMerl/asuswrt-merlin.ng/commit_comment/create#commitcomment-31542922_

**Comment by RMerl** [comment]
Thanks, fixed with 6443b042f87c21b4e16e7f2e3e03a801362c359a .
