### ISSUE TITLE
Internal DNS not accessible

### ISSUE THREAD

**Issue by SQLJeet** [RMerl/asuswrt-merlin.ng#232]
Pihole is running on 192.168.1.121 and acting as the internal DNS. The router is providing the DHCP. When you are using the guest wifi with intranet access turned off it is unable to route to the DNS server. All traffic should flow through the internal DNS server even if they do not have the ability to connect to the intranet.

**Comment by RMerl** [comment]
Not a bug, and working as intended - if you are blocking Intranet access, they none of the LAN devices will be reachable.

DNS servers are provided by DHCP, clients have no way to determine what other DNS to use if they are unable to reach the one provided by DHCP.
