### ISSUE TITLE
WiFi connected devices shows as offline

### ISSUE THREAD

**Issue by tatunts** [RMerl/asuswrt-merlin.ng#236]
Hello guys!

Newbie here, just flashed Merlin on my Asus RT-AC68U.

I've noticed that I have some devices that are currently connected to the router shows as offline, is this right?

![image](https://user-images.githubusercontent.com/25224882/50017077-35ff8580-ffb2-11e8-8101-8d29d59fe2ab.png)

I've noticed that after flashing to Merling, some devices shows as offline using another softer called Home Assistant that connects to the router using SSH to get the connected devices on the network, maybe this is related, since those offline devices also shows as offline on Home Assistant?

Thanks a lot and great work here!

**Comment by RMerl** [comment]
The information comes from networkmap, over which I have no control since it's closed source.
