### ISSUE TITLE
TLS verification field field is too small

### ISSUE THREAD

**Issue by matfra** [RMerl/asuswrt-merlin.ng#239]
Some OpenVPN servers (namely all french Freebox Revolution) have a TLS CN that is longer than the 64 char authorized in the field:
VPN / Openvpn client  / Verify TLS certificate / Common name

example:
`C=FR, O=Freebox SA, CN=Freebox OpenVPN server <32char hash>
`gets truncated to
`C=FR, O=Freebox SA, CN=Freebox OpenVPN server <18char...
`
thus failing the TLS server verification
A simple workaround is to manually add this to the Custom configuration field
`
verify-x509-name "C=FR, O=Freebox SA, CN=Freebox OpenVPN server <32char hash>`

but it would be neat to allow longer strings in VPN / Openvpn client  / Verify TLS certificate / Common name

**Comment by matfra** [comment]
I believe this is the line that needs to be changed
https://github.com/RMerl/asuswrt-merlin.ng/blob/263dead27428ec8f5ff8979a4d3c52ef7f13adeb/release/src/router/www/Advanced_OpenVPNClient_Content.asp#L1448

**Comment by RMerl** [comment]
It's more complicated than that, other locations of the code must also be checked (buffer sizes throughout the code, nvram max size in defaults.c, etc...)

Must also ensure that the nvram size can be increased - Broadcom/Asus enforce some limitations now on newer models, making it difficult (sometimes even impossible) to increase the size limits.
