### ISSUE TITLE
RT-AC68U B2 on Supported page wiki

### ISSUE THREAD

**Issue by odinian** [RMerl/asuswrt-merlin.ng#241]
May I suggest that you add the RT-AC68U "B2" hardware revision to the page at 
https://github.com/RMerl/asuswrt-merlin/wiki/Supported-Devices

assuming this revision is supported. I recently purchased three RT-AC68U's from B&H ($99/each :-) and all three are rev B2.

**Comment by RMerl** [comment]
I don`t list explicit hardware revisions because there are too many of them, and new revisions are always supported.

**Comment by odinian** [comment]
The reason I suggested this is because a couple of hardware revisions are list there, but not B2. Maybe remove the ones that are there and just put what you said “all revs”

**Comment by RMerl** [comment]
I see what you mean.  Whoever edited that Wiki article in the past also added various hardware revisions, which leads to the confusion you have experienced, not being sure whether your particular revision support it or not.
