### ISSUE TITLE
Dual-Wan, not able to use IPv6 as destination IP

### ISSUE THREAD

**Issue by samip5** [RMerl/asuswrt-merlin.ng#243]
Could this be fixed so I can add a policy with IPv6 address as destination?

Image of the screen:
![image](https://user-images.githubusercontent.com/1703002/51197660-da028680-18fa-11e9-8c0a-774aacaab823.png)

**Comment by RMerl** [comment]
I suspect that interface might possibly only accept IPv4, limiting the max input field length to 255.255.255.255/32.

I don't know if the backend code would support IPv6 either.

**Comment by samip5** [comment]
Could you look into it, at least? :)

**Comment by themiron** [comment]
right. unfortunately it doesn't support ipv6 at all

**Comment by samip5** [comment]
In that case, could there be a IPv6 supported version of such functionality?

**Comment by RMerl** [comment]
The Dual WAN routing code is closed sourced and outside of my control.  Best I can do is make sure someone from Asus sees this.

In the meantime, your best chance would be to manually configure things through a firewall-start script.
