### ISSUE TITLE
Show IPv6 router address with IPv4 WAN IP when IPv6 address present

### ISSUE THREAD

**Issue by jerbzz** [RMerl/asuswrt-merlin.ng#244]
On the Network Map page, it would be truly excellent if the IPv6 "WAN" (i.e. the output of `nvram get ipv6_rtr_addr`) was shown along with the IPv4 and DDNS information (assuming of course an IPv6 address is present).

I am completely unfamiliar with this codebase so haven't yet attempted to implement this myself.

**Comment by asaddon** [comment]
As far as I can tell Network Map code is now closed source so nothing Eric can do.
