### ISSUE TITLE
CPU 100% when connect HHD 6TB in RT-AC3200

### ISSUE THREAD

**Issue by Pitus660** [RMerl/asuswrt-merlin.ng#247]
When connect an external hard drive ( 6TB split in two partions 2.2TB and 3,8TB NTFS ) into USB 3.0 port in few minutes the 2 CPU 100% usage. I can see the logs of the router and only find this:

```
Jan 17 14:12:28 kernel: device blocksize: 512
Jan 17 14:12:28 kernel: __find_get_block_slow() failed. block=4329074432, b_blocknr=34107136
Jan 17 14:12:28 kernel: b_state=0x00000020, b_size=512
Jan 17 14:12:28 kernel: device blocksize: 512
Jan 17 14:12:28 kernel: __find_get_block_slow() failed. block=4329074432, b_blocknr=34107136
Jan 17 14:12:28 kernel: b_state=0x00000020, b_size=512
Jan 17 14:12:28 kernel: device blocksize: 512
Jan 17 14:12:28 kernel: __find_get_block_slow() failed. block=4329074432, b_blocknr=34107136
Jan 17 14:12:28 kernel: b_state=0x00000020, b_size=512
Jan 17 14:12:28 kernel: device blocksize: 512
Jan 17 14:12:28 kernel: __find3size: 512
Jan 17 14:12:28 kernel: size: 512
```

This block my router and any device connected it, internet not works and is very very slow.
Only solution is disconnect the HHD and restart the router.

I found this link [disksuport](https://event.asus.com/2009/networks/disksupport/) and I think this HHD is compatible with my asus router.

Any suggestion for fix this?

Thanks in advance

**Comment by RMerl** [comment]
There is a problem with the disk, the enclosure or the USB cable.  This has nothing to do with the firmware.
