### ISSUE TITLE
IP Binding and Port Forwarding list do not populate in app. 

### ISSUE THREAD

**Issue by Geezus42** [RMerl/asuswrt-merlin.ng#250]
The app now has support for viewing and modifying IP assignment and port forwarding. However existing rules do not populate and if you add a rule it erases others. I know you can't touch the app but I am guessing that it just reads and modifies a file on the router.

**Comment by RMerl** [comment]
IP assignment might possibly break because my firmware has an extra field that allows you to specify a hostname.  Nothing I can do about it if the app is unable to cope with that.

No idea why port forwards would break, I haven't made any change to the format of that nvram setting.

**Comment by Geezus42** [comment]
10-4
