### ISSUE TITLE
Please update compilation recipe in README.TXT

### ISSUE THREAD

**Issue by mieszkomularczyk** [RMerl/asuswrt-merlin.ng#251]

**Comment by mieszkomularczyk** [comment]
It looks README.TXT has not been updated for some time and the recipe to build firmware does not work (e.g. directories which don't exit are referenced in this file). Could you update the README so it follows the latest branch and idrectory structure. Also please recommend Ubunu version, which guarantees build success.

**Comment by RMerl** [comment]
That README is from Asus.  The up-to-date instruction specific to this fork are in the Wiki.
