### ISSUE TITLE
bug on ddns

### ISSUE THREAD

**Issue by Hardcore-fs** [RMerl/asuswrt-merlin.ng#256]
version 384.9

once you enable DDNS you cannot disable it

IF
free cert or import is selected.

since  you need to have DDNS enabled to configure these settings, the code appears to check that it IS enabled before allowing "apply" to be pressed.
which is fine if it is "off" and you are turning it "on"

but if it is already "on", when you set it to "off" and press apply, it blocks with a message that "DDNS" must be enabled, even if you want to turn it "off"...

Solution:
setting the  "SSL cert to "NONE" allows you to get out of the block & turn it off.

**Comment by RMerl** [comment]
Currently unable to reproduce under 384.11, either the issue was user-specific (Check the browser console for Javascript error), or the issue has been resolved since then.
