### ISSUE TITLE
384.9 // RT-AC88U - Missing Download Master, Webpage error in USB Application & AiCloud

### ISSUE THREAD

**Issue by zhuhang-jasper** [RMerl/asuswrt-merlin.ng#258]
Firmware: **384.9**
Model: **RT-AC88U** 
HW Ver: **A5**
Browser: **72.0.3626.96 (Official Build) beta (64-bit)**

Issues:
- Download Master option missing from USB Application page (after USB device connected, even though download master still accessible via port number) **_(Working fine in 384.8_2)_**

More Errors found in console when accessing USB Application & AiCloud 2.0 webpages:
- Uncaught SyntaxError: Invalid or unexpected token **(APP_Installation.asp:77)**
- Uncaught ReferenceError: initial is not defined **(APP_Installation.asp:779)**
- Uncaught SyntaxError: Unexpected token ) **(cloud_main.asp:80)**
- Uncaught ReferenceError: initial is not defined **(cloud_main.asp:619)**

**Comment by ashokrajar** [comment]
Same issue on RT-AC3200.

Current firmware : 384.10

**Comment by zhuhang-jasper** [comment]
On 384.8 is working fine. That's the reason why I fallback to 384.8

**Comment by kobudev** [comment]
Same on RT-AC68U, firmware 384.10_2
Access through IP:port still works

**Comment by RMerl** [comment]
Should have been fixed by Asus with 45713 and 5951 GPLs, merged with 384.11.
