### ISSUE TITLE
Enable legacy (NFS V2) support doesn't work

### ISSUE THREAD

**Issue by SiliCAT** [RMerl/asuswrt-merlin.ng#261]
Firmware: 384.9
RT-AC68U

The nfsv2 support is enabled from the GUI page, but it doesn't work:

```
cat /proc/fs/nfsd/versions
-2 +3
```

**Comment by RMerl** [comment]
Looks like newer versions of nfs-utils no longer enable NFSv2 by default, and it requires to be explicitely enabled.
