### ISSUE TITLE
DUAL WAN, load balance mode, upnp not work

### ISSUE THREAD

**Issue by lu00** [RMerl/asuswrt-merlin.ng#284]
seems miniupnpd never starts under DUAL WAN mode. 
V384.9

**Comment by RMerl** [comment]
Any error message in the system log regarding miniupnpd?

**Comment by lu00** [comment]
no error message, seems no one to start the miniupnpd.

**Comment by RMerl** [comment]
It seems to be by design.  Asuswrt doesn't start upnp in wan_up() if the router is set to load balancer mode.  I suspect that's because port forwarding through UPNP might not be reliable enough in load balancer mode, since you cannot predict which WAN interface gets used.
