### ISSUE TITLE
dhcp-script used by dnsmasq

### ISSUE THREAD

**Issue by frawau** [RMerl/asuswrt-merlin.ng#286]
Hi,

I just updated to 384.9. The whole network went down.  The reason was that dnsmasq could not start.

I have customised the dnsmasq configuration with a file /jffs/configs/dnsmasq.conf.add  In that file I had a statement defining "dhcp-script". Apparently the version of dnsmasq shipping with 384.9 uses "dhcp-script" with /sbin/dhcp_lease

That file is a binary. If that is really necessary, I would suggest having "dhcp-script" configured to run a script that would run /sbin/dhcp_lease  and allow some customisation.

**Comment by RMerl** [comment]
The change was done by Asus, not by me.  Reverting that change would cause other problems.

The proper workaround is to use a postconf script to replace the existing dhcp-script entry with your own, pointing at your script.  Then at the end of your script, call Asus's own /sbin/dhcp_lease to ensure proper operation.
