### ISSUE TITLE
Turning on DNSFilter doesn't change DNS settings

### ISSUE THREAD

**Issue by jiqiren** [RMerl/asuswrt-merlin.ng#287]
I switch on DNSFilter and selected Quad9. The 3 DNS IP addresses still listed google's 8.8.8.8 DNS servers. I clicked apply anyway but nothing changes.

DHCP still gives out 192.168.1.1 (the router) and dnsmasq is still pointing at Comcast (default 75.75.75.75 & 75.75.76.76).

**Comment by RMerl** [comment]
Working as intended.  The goal of DNSFilter is not to change the settings, it`s to force the traffic to the intended server through firewall rules.  This allows it to override any hardcoded configuration that your clients might have (for instance, Android devices often hardcode 8.8.8.8 for some of their applications).
