### ISSUE TITLE
IPTraffic missing from RT-AX88U

### ISSUE THREAD

**Issue by AngellusMortis** [RMerl/asuswrt-merlin.ng#293]
I just got a new router and I am going through and re applying all of my settings. I noticed IPTraffic does not seem to be on the firmware for the RT-AX88U. Is that a known thing? I just wanted to check in on it.

**Comment by RMerl** [comment]
IPTraffic relies on a kernel module that is not compatible with newer Linux kernel versions, such as the 4.1 kernel used by the RT-AC86U and RT-AX88U.

**Comment by AngellusMortis** [comment]
I figured it was something like that. I just wanted to make sure it was not missed  (and know anyone else can see that as well). Thanks!
