### ISSUE TITLE
Policy rules may be lost on refresh (problem in vpnrouting.sh script)

### ISSUE THREAD

**Issue by eugenezh** [RMerl/asuswrt-merlin.ng#297]
Running 384.10_2 (3-Apr-2019) firmware on a RT-AC66U_B1.

The section in openvpnrouting.sh that runs when 
if [ $script_type = "rmupdate" ]
first does "purge_client_list" and only recreates the rules if [ $VPN_FORCE == "1" -a $VPN_REDIR -ge "2" ]

If I understand it right, the rules should always be present (re-created) if VPN_REDIR mode is 2 or 3 no matter how the VPN_FORCE flag is set. 
Currently, when $VPN_FORCE = 0, the rules are lost even if $VPN_REDIR is set to one of "Policy Routing" options

**Comment by RMerl** [comment]
rmupdate only gets used if the tunnel is currently down, and the user changed whether he wanted LAN clients to be blocked or allowed through the WAN if the tunnel went down.  Therefore there should not be any client rules if the WAN blocking is disabled - it's as if there was no OpenVPN policy rules established.

Once the tunnel is re-established, then proper client rules will be created.

This is working as intended.
