### ISSUE TITLE
IPv6: Configure DHCPv6 from the Web GUI

### ISSUE THREAD

**Issue by samip5** [RMerl/asuswrt-merlin.ng#298]
I would like to see enhancement to the IPv6 page so you would have a choice between stateful and stateless, plus if you want to use SLAAC. On top of that, also the ability to use DHCPv6 with either stateful or statless config.

**Comment by InstantAli3n** [comment]
I am misunderstanding you can already do all of this.

**Comment by samip5** [comment]
I'm not talking about the native options on the IPv6 page,  I'm talking
about every other option as I don't have native connectivity.

**Comment by samip5** [comment]
@RMerl Is this doable?
