### ISSUE TITLE
384.10.2 not broadcasting SSID on RT-AC3200 correctly.

### ISSUE THREAD

**Issue by msconley2172** [RMerl/asuswrt-merlin.ng#299]
factory reset my RT-AC3200, updated from 384.3 to 384.10.2

Changed the SSID from ASUS to my internal SSID, and ran the basic configuration.
The systems never saw the change from ASUS to my internal ID, however, the admin page showed the updated ID.

Checked a similar configuration on RT-AC5300, and there was no issue.

Hard reset the router again, dropeed fro 384.10.2 to 384.3, and the SSID's corrected to the internal one's I set.  I ran the update again, and it is currently broadcasting correctly.

**Comment by RMerl** [comment]
Everything related to wifi is closed source and outside of my control.
