### ISSUE TITLE
Sorting of QoS - Web History

### ISSUE THREAD

**Issue by Alphasmsn** [RMerl/asuswrt-merlin.ng#301]
I have a Asus RT88U. Under Adpative QOS tab, in QoS - Web History. Please make the Access time | MAC Address / Client Name | Domain name sortable alphanumerically. It is difficult to look at the time stamp that are all randomly displayed. Thank you

**Comment by RMerl** [comment]
Not sure it`s doable, since most of that code is closed source (the function currently generating the output comes from libbwdpi).

I recommend people ask Asus to make this list more configurable (I know it`s a fairly common request).
