### ISSUE TITLE
"unhandled level 3 translation fault" 

### ISSUE THREAD

**Issue by facaldoggi** [RMerl/asuswrt-merlin.ng#311]
ASUS RT-AC86U

ON 384.8 9 and 10 firmwares...

May  5 14:03:59 kernel: dcd[1245]: unhandled level 3 translation fault (11) at 0x00000000, esr 0x92000007
May  5 14:03:59 kernel: pgd = ffffffc012ea5000
May  5 14:03:59 kernel: [00000000] *pgd=00000000129f4003, *pud=00000000129f4003, *pmd=0000000015049003, *pte=0000000000000000
May  5 14:03:59 kernel: CPU: 1 PID: 1245 Comm: dcd Tainted: P           O    4.1.27 #2
May  5 14:03:59 kernel: Hardware name: Broadcom-v8A (DT)
May  5 14:03:59 kernel: task: ffffffc01918e040 ti: ffffffc012a3c000 task.ti: ffffffc012a3c000
May  5 14:03:59 kernel: PC is at 0x29b74
May  5 14:03:59 kernel: LR is at 0x29df4
May  5 14:03:59 kernel: pc : [<0000000000029b74>] lr : [<0000000000029df4>] pstate: 200b0010
May  5 14:03:59 kernel: sp : 00000000ff987290
May  5 14:03:59 kernel: x12: 00000000000a0034 
May  5 14:03:59 kernel: x11: 0000000000080c1c x10: 0000000000000022 
May  5 14:03:59 kernel: x9 : 0000000000000003 x8 : 0000000000000022 
May  5 14:03:59 kernel: x7 : 00000000f5dfe744 x6 : 0000000000000036 
May  5 14:03:59 kernel: x5 : 00000000000001d0 x4 : 00000000f5dfe7a4 
May  5 14:03:59 kernel: x3 : 0000000000000000 x2 : 0000000000000020 
May  5 14:03:59 kernel: x1 : 0000000000000014 x0 : 0000000000000000

**Comment by RMerl** [comment]
Known issue, the dcd prorcess often crashes on the RT-AC86U.  This is a closed source component from Trend Micro, and outside of my control.  Asus/Trend Micro will have to fix it.
