### ISSUE TITLE
VirusTotal - Malware / Trojan in /usr/bin files

### ISSUE THREAD

**Issue by svpn** [RMerl/asuswrt-merlin.ng#317]
**RT-AC87U_384.12_beta1-g69e0eaefe1**

**/usr/sbin/nt_actMail** - https://www.virustotal.com/gui/file/ec93fd14f72b12ff782feb73351a7088c3920b23ebfb898c3266aa65def2fcbb/detection

**/usr/bin/Tor** - https://www.virustotal.com/gui/file/3a73ee8eb23d56f51ec9bfc71ac5f55e92e6c79dd6130ef888284af0400c66a8/community

**Signature Match - THOR APT Scanner**

**Detection**

Rule: SUSP_ELF_Tor_Client
Rule Set: APT Malware
Rule Type: community
Description: Detects VPNFilter malware
Reference: Internal Research
Author: Florian Roth
Score: 75

**Detection Snapshot**

Detection Timestamp: 2019-06-10 04:20
AV Detection Ratio: 0 / 53
NO AV DETECTION
#elf #tor #client #APTMalware #SUSP_ELF_Tor_Client

More information: https://www.nextron-systems.com/notes-on-virustotal-matches/
Please report interesting findings via Twitter @thor_scanner

**/usr/sbin/realtc** - https://www.virustotal.com/gui/file/f3d72c58e16d18e1286c65eaa1d2a213b3f5bb74d1b041b6b7108bc8e536f953/detection

**/usr/sbin/tc** - https://www.virustotal.com/gui/file/f3d72c58e16d18e1286c65eaa1d2a213b3f5bb74d1b041b6b7108bc8e536f953/detection

**Comment by RMerl** [comment]
Those scanners are designed for x86 executables, not ARM.  They cannot be used reliably on non-x86 binaries.
