### ISSUE TITLE
Update RT-AC3200 binary blobs/driver

### ISSUE THREAD

**Issue by breisig** [RMerl/asuswrt-merlin.ng#319]
It seems the latest GPL formware for the RT-AC3200 (and RT-AX88U) is now available. [ https://www.asus.com/ca-en/Networking/RTAC3200/HelpDesk_Download/ ] Can we get the binary blogs/drivers updated to the latest version?

**Comment by RMerl** [comment]
RT-AC3200 blobs from 51636 were already merged three weeks ago with 5dcacbb6dc, and RT-AX88U's 5951 was merged over two months ago with d4d4283cfb5bc23d3cb84bf062285800ab7a2848...
