### ISSUE TITLE
Wan connection keeps disconnecting

### ISSUE THREAD

**Issue by samip5** [RMerl/asuswrt-merlin.ng#322]
Device: Asus RT-AC87U
Firmware version: 384.11_2

**Description**
- At random intervals, the primary WAN disconnects, and requires me to go slide the slider a few times so the connection recovers.
- I have DUAL WAN configuration, using Ethernet LAN port 4, and the primary WAN connection, however it does not failover when the primary WAN goes to disconnected state for some reason.

Logs:
[Router_Logs_Jun17-18.txt](https://github.com/RMerl/asuswrt-merlin.ng/files/3300198/Router_Logs_Jun17-18.txt)

**Comment by master3395** [comment]
It's related to this report to.
But i haven't seen this issue in 384.12_beta2-g7e33ba641a
https://github.com/RMerl/asuswrt-merlin.ng/issues/310
