### ISSUE TITLE
ip netns doesn't work in ssh

### ISSUE THREAD

**Issue by tony4212** [RMerl/asuswrt-merlin.ng#327]
when typing ip netns add (insert name) the following output is given "Failed to create a new network namespace (insert name): Invalid argument.

This is using asus merlin 384.11_2 on a rt-68u router.

**Comment by RMerl** [comment]
Probably not supported by the limited environment running on the router.  Keep in mind this is not a full-featured Linux distro, but a very limited embedded system.
