### ISSUE TITLE
Display hostnames in traffic monitor

### ISSUE THREAD

**Issue by Eldenroot** [RMerl/asuswrt-merlin.ng#336]
![image](https://user-images.githubusercontent.com/778890/61577653-b529de80-aaea-11e9-8b30-a40a6d659b04.png)

As title says, would be nice to add hostnames to the table to quickly know the name of device.

Moreover scale option - is possible to add a TB?

**Comment by RMerl** [comment]
Click on "Display Advanced Options", there's an option there to display hostnames.

**Comment by Eldenroot** [comment]
I wil check that.

It will display IP and hostname together? I will check when I return from work.

**Comment by Eldenroot** [comment]
@RMerl I annot find it, where is the setting located? Thank you! Screenshot please :)

**Comment by RMerl** [comment]
![image](https://user-images.githubusercontent.com/1661562/61841846-1b548f80-ae64-11e9-87be-555aef12f5eb.png)

However I can't really test that particular feature any longer since it's not compatible with the 4.1 kernel used by newer routers.

**Comment by Eldenroot** [comment]
Thank you!
