### ISSUE TITLE
Some images can't be found

### ISSUE THREAD

**Issue by geoleonsh** [RMerl/asuswrt-merlin.ng#344]
Example:
asuswrt-merlin.ng/release/src/router/www/images/New_ui/hightaba.png
asuswrt-merlin.ng/release/src/router/www/images/New_ui/inputbg.png
asuswrt-merlin.ng/release/src/router/www/images/New_ui/inputbg_2.png
asuswrt-merlin.ng/release/src/router/www/images/New_ui/inputbg_disable.png

In the lastest source,these images don't exist

**Comment by RMerl** [comment]
I don't understand your point.  These files don't; exist, and there's no reference to them either in the web pages, so I don't understand why you expect these particular images to exist.

**Comment by geoleonsh** [comment]
I got some error message in the web pages，about images 404 error.
But it returned to normal after a while.
I opened the issues before it returned to normal.

**Comment by RMerl** [comment]
You probably had old content in your browser cache which needed to expire.
