### ISSUE TITLE
Can't upgrade to 384.13

### ISSUE THREAD

**Issue by surdu** [RMerl/asuswrt-merlin.ng#345]
I have an RT-AC68U, and I tried to manually update from 384.12 to 384.13, but after I reboot, the version is still 384.12 and the update notification still there.

**Comment by marodor** [comment]
Try this:
Remove usb devices hooked on the router, reboot, and retry flashing

**Comment by surdu** [comment]
@marodor Thank you for the tip, but unfortunately didn't worked

**Comment by asaddon** [comment]
Is it a genuine AC68U or a converted T-mobile model?

**Comment by surdu** [comment]
Genuine. Wet don't even have T-mobile where I'm from.

**Comment by asaddon** [comment]
Airtight then try power cycling the router and then use a different browser to do the upgrade this time.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.

**Comment by surdu** [comment]
@asaddon That didn't work either. Is there a log somewhere that keeps tabs of what's going on during upgrade?

@RMerl This sounds to me like there is an issue with the upgrade process in asuswrt-merlin. This is an issue tracker, right?

**Comment by asaddon** [comment]
I'm not aware of any update logs in the  syslog. The only option left now is do a complete factory reset and then try to update again.
