### ISSUE TITLE
blank page in aiprotection - yandex dns

### ISSUE THREAD

**Issue by YBS-PC** [RMerl/asuswrt-merlin.ng#346]
there is pink page with error in aiprotection - yandex dns

**Comment by RMerl** [comment]
Not sure what firmware you are running, but my firmware does not support Yandex DNS.

**Comment by YBS-PC** [comment]
![2019-08-15 (2)](https://user-images.githubusercontent.com/52429295/63090393-cc31e400-bf63-11e9-945b-09c408133c0f.png)
![2019-08-15 (3)](https://user-images.githubusercontent.com/52429295/63090400-d05e0180-bf63-11e9-8f58-4330cd8d330e.png)
