### ISSUE TITLE
there is pink page with error in aiprotection - yandex dns

### ISSUE THREAD

**Issue by YBS-PC** [RMerl/asuswrt-merlin.ng#347]
![2019-08-15 (2)](https://user-images.githubusercontent.com/52429295/63090393-cc31e400-bf63-11e9-945b-09c408133c0f.png)
![2019-08-15 (3)](https://user-images.githubusercontent.com/52429295/63090400-d05e0180-bf63-11e9-8f58-4330cd8d330e.png)

_Originally posted by @YBS-PC in https://github.com/RMerl/asuswrt-merlin.ng/issues/346#issuecomment-521601261_

**Comment by YBS-PC** [comment]
after all three cases of firmware update: update, nvram clean & update, restoration

**Comment by RMerl** [comment]
That tab doesn't show here.  If it shows on your router, then something else is interfering with the webui from properly showing/hiding tabs.

Try a different browser, also look at your browser console for any Javascript error preventing the tab from being properly removed.  Also if you run any add-on that modifies the webui, disable those add-ons.

**Comment by YBS-PC** [comment]
this tab is in the firmware from ASUS (perhaps for Russia, but I flashed the firmware from the international site and from the Hong Kong site and there it is also), but in the Merlin firmware the tab is also there, but it is not functional and leads to an error page. Checked on a new clean browser Mozila, chrome and Opera

**Comment by RMerl** [comment]
That would imply that this tab is shown when the router`s region is set to RU in the bootloader.  @themiron , can you confirm if this is indeed the case?  If so, they I will need to take active steps to hide it, as it might interfere with the DNSFilter implementation.

If you need the YandexDNS functionality then you can reproduce it by using DNSFilter, on the LAN section.

**Comment by RMerl** [comment]
I can't see any evidence in the code that would show that this tab wouldn't be removed unless the firmware was compiled with explicit YandexDNS support.  Please post a screenshot of your Tools -> Sysinfo page, showing the current Features flags.

**Comment by YBS-PC** [comment]
![2019-08-20-](https://user-images.githubusercontent.com/52429295/63352105-21f1fc00-c369-11e9-9211-d73e24e30dcd.png)

**Comment by RMerl** [comment]
Your feature list reports that yadns is enabled, yet I did not enable it when I built the RT-AC88U firmware.  I also see you have an unexpected bootloader version, so I suspect that maybe the Russian SKU of the RT-AC88U has an hardcoded list of features that enables YandexDNS regardless of whether the firmware supports it or not.

Only way I can see to fix this would be to forcibly remove the YandexDNS tab from the webui regardless of the state of the yadns feature flag.

**Comment by YBS-PC** [comment]
> Only way I can see to fix this would be to forcibly remove the YandexDNS tab from the webui regardless of the state of the yadns feature flag.

How can i do this or it will be in new release?

> unexpected bootloader version

Can i change it?

**Comment by RMerl** [comment]
Just don't click on the tab...  The fix will simply hide the tab from the webui, there will be no change in functionality.

The bootloader cannot be changed by the end-user.
