### ISSUE TITLE
Adaptive QoS mode configuration lost after reboot

### ISSUE THREAD

**Issue by reejue** [RMerl/asuswrt-merlin.ng#354]
**This is a bug since 384.12_0 to 384.13**
 384.11_2 and the official firmware works well.

I set the Adaptive QoS mode to Games, applied successful.
Then **reboot** router , it has been lost and shows Customize mode icon insteand.

Log：
```
Sep  2 18:22:05 A.QoS: qos_count=0, qos_check=0
Sep  2 18:22:05 A.QoS: set_qos_on fails
Sep  2 18:22:05 A.QoS: restart A.QoS because set_qos_conf / set_qos_on / setup rule fail
Sep  2 18:22:05 kernel: ERR[qos_start:3364] qos_ops is not registered!
Sep  2 18:22:05 kernel: ioctl_iqos_op_switch(1) fail!
```

Thank you RMerl help me to fix it.

Screenshot:
![20190902174423](https://user-images.githubusercontent.com/54799213/64106220-5672a880-cdaa-11e9-9b3f-b092df3fc874.png)

**Comment by reejue** [comment]
And the Game Boost - One Click Game First mode button trun to **OFF** status.

Screenshot: 
![20190902174858](https://user-images.githubusercontent.com/54799213/64106192-45c23280-cdaa-11e9-8959-5280c4b0807f.png)

**Comment by RMerl** [comment]
The bug lies in the WLCSM component, which is closed source.  Asus are aware of the issue and should have fixed it only recently.  Until they release a new firmware with the fix there is nothing I can do.
