### ISSUE TITLE
[feature request] AdGuard nameservers

### ISSUE THREAD

**Issue by YBS-PC** [RMerl/asuswrt-merlin.ng#355]
Can you, please, add adguard nameservers ( https://adguard.com/en/adguard-dns/overview.html ) to DNSFilter or one more custom nameserver?

**Comment by RMerl** [comment]
I don`t want to overcrowd the page with a long list of supported servers, so there are currently no plans to add any new services to this page, unless one of the existing one has to be removed (like the discontinued Norton service last year).  The current list provides a wide range of the most popular services, and the custom field would be adequate for the rest.

You only need one single custom field, so the current three fields would support up to three completely different services, which is more than enough for reasonable use.
