### ISSUE TITLE
Только имя пользователя / пароль0

### ISSUE THREAD

**Issue by YBS-PC** [RMerl/asuswrt-merlin.ng#357]
in vpn client tab there is '0' after text
in English Username / Password Auth. Only
in Russian Только имя пользователя / пароль0

asus rt ac88u
merlin 384.13

**Comment by RMerl** [comment]
The issue is upstream.  I don't make changes to the dict files since it would be far too much work to maintain afterward, so it will have to be fixed by Asus.
