### ISSUE TITLE
[Feature Request] Priority setting for app analysis or Bandwidth Management for Application within Router

### ISSUE THREAD

**Issue by wachiiisss** [RMerl/asuswrt-merlin.ng#360]
Under QoS - WAN/LAN Bandwidth Monitor, we know that it is possible to see what apps that the device currently using if we turn on the app analysis. As the subject mention above, I hope that it is possible to set priority setting per app instead of per device. Or, for more complex, a bandwidth management for applications (NetLimiter) within the router.

**Comment by RMerl** [comment]
Adaptive QoS is closed source, and outside of my control.
