### ISSUE TITLE
HELP me to make a script with arguments restart wireless

### ISSUE THREAD

**Issue by YBS-PC** [RMerl/asuswrt-merlin.ng#361]
Please help me to write a script that will be executed when restarting wifi (for example, with arguments restart and wireless in service-event) and execute simultaneously or sequentially several commands
for example
#!/bin/sh
logger "hi"
nvram set time_zone=UTC-3_4
logger "bye"

**Comment by asaddon** [comment]
You better ask this in AsusWRT-Merlin SNB forums, this is the wrong place to ask such questions.
