### ISSUE TITLE
Entware FreeRADIUS3 - TLS 1.3 Problem...

### ISSUE THREAD

**Issue by Aminuxer** [RMerl/asuswrt-merlin.ng#365]
I had freeradius 3.0.19 from entware on my Asus RT-AC68U with 384.13_0 Merlin's firmware.
This firmware contains both openssl - 1.0.2s and 1.1.1c
I use WPA2-Enterprise (802.1x-EAP) in TTLS-MSCHAPv2 mode (inner-tunnel scheme).

Some clients (some androids builds, win7 with GEANTLink) try use TLS 1.3 in EAP - in this case RADIUS reject connection with this error:

```
(11) eap_ttls: <<< recv TLS 1.3  [length 0092] 
(11) eap_ttls: >>> send TLS 1.2  [length 0002] 
(11) eap_ttls: ERROR: TLS Alert write:fatal:handshake failure
tls: TLS_accept: Error in error
(11) eap_ttls: ERROR: Failed in __FUNCTION__ (SSL_read): error:1417A0C1  \
    :SSL routines:tls_post_process_client_hello:no shared cipher
(11) eap_ttls: ERROR: System call (I/O) error (-1)
(11) eap_ttls: ERROR: TLS receive handshake failed during operation
(11) eap_ttls: ERROR: [eaptls process] = fail
```

Normal clients (other androids, Linux) use TLS 1.2 and work correctly.
I read  that TLS 1.3 inside EAP is break of standard, only IETF draft exists.

Does exists recommendation for such reliable config or freeradius3 at merlin firmware , compatible with TLS 1.2 and TLS 1.3 in same time ?

I also try change min_tls_version and max_tls_version in eap.conf , but this can't fix problem.
Thank you.

**Comment by RMerl** [comment]
This tracker is for bug reports related to Asuswrt-Merlin.  I recommend you contact the Entware devs for support.
