### ISSUE TITLE
Failback if configured DNS in DNS-Filter is not available 

### ISSUE THREAD

**Issue by mycloudrevolution** [RMerl/asuswrt-merlin.ng#366]
I tried to set up a configuration where some devices use Pinhole as custom DNS Filter.

But I would like to see that a failback to default (or global DNS Filter) DNS is done if PiHole device is not available.

This feature might be also useful for other setups.

**Comment by RMerl** [comment]
Not technically possible, as the firewall has no way of knowing if a device is available or not.

**Comment by mycloudrevolution** [comment]
Maybe was "device" misleading. If the specified DNA service is not available.

Might that be possible?

**Comment by asaddon** [comment]
I believe this can only be done after implementing some kind of check logic like doing a DNS query and check for the answer every x seconds/minutes to see if the DNS server is online and functional.
