### ISSUE TITLE
WAN down redirect feature cause client always get "10.0.0.1" dns answer

### ISSUE THREAD

**Issue by nightcoffee** [RMerl/asuswrt-merlin.ng#390]
If turn on "Enable WAN down browser redirect notice"
the following code add rule to iptables when WAN down
https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src/router/rc/firewall.c#L2427
it redirect all DNS request to /sbin/wanduck and get 10.0.0.1 as result

**Although WAN UP, the client will always get 10.0.0.1 if it continous send DNS request**
because conntrack will record this udp redirect "connection"
```
admin@RT-AC86U-4828:/tmp/etc# conntrack -L | grep 18018
udp      17 172 src=192.168.50.24 dst=192.168.50.1 sport=49153 dport=53 src=192.168.50.1 dst=192.168.50.24 sport=18018 dport=49153 [**ASSURED**] mark=0 use=1
udp      17 169 src=192.168.50.23 dst=192.168.50.1 sport=49153 dport=53 src=192.168.50.1 dst=192.168.50.23 sport=18018 dport=49153 [**ASSURED**] mark=0 use=1
udp      17 177 src=192.168.50.90 dst=192.168.50.1 sport=49153 dport=53 src=192.168.50.1 dst=192.168.50.90 sport=18018 dport=49153 [**ASSURED**] mark=0 use=1
udp      17 176 src=192.168.50.133 dst=192.168.50.1 sport=49153 dport=53 src=192.168.50.1 dst=192.168.50.133 sport=18018 dport=49153 [**ASSURED**] mark=0 use=1
```

these conntrack record impossible change to **UNREPLIED** because client continuous send dns packet and wanduck continuous answer 10.0.0.1

**Comment by bnuhero** [comment]
Same issue with ASUS RT-AC66U B1 and Asuswrt-Merlin 384.19.
