### ISSUE TITLE
Empty "Client status" and "View List" in Network Map

### ISSUE THREAD

**Issue by chenrylee** [RMerl/asuswrt-merlin.ng#396]
**Router model**: Netgear R7000
**Firmware version**: 384.14

In `Network Map` section, View list and Client status shows empty page, zero client.
But in `Tools` section, the number of clients is correct.

This issue occurred some while ago, and reboot/factory reset doesn't help.

**Comment by RMerl** [comment]
Running Asuswrt-Merlin on a non-Asus router is illegal and not supported.  XVortex and Koolshare firmwares are in violation of multiple software licences, including violation of the GPL licence due to the lack of public sources code.
