### ISSUE TITLE
Net access issue of OpenVPN Server in 384.14

### ISSUE THREAD

**Issue by demonqiqi** [RMerl/asuswrt-merlin.ng#398]
LAN only = LAN+internet；internet only=both failed。

**Comment by digitalec** [comment]
Confirmed here as well on 384.14. LAN only is really LAN + Internet.

On iOS I use Passepartout as my VPN client and I have to override the OVPN settings and force IPv4 Gateway to enabled or else I can’t  connect to any local IPs.
