### ISSUE TITLE
Let's encrypt not updating?

### ISSUE THREAD

**Issue by LaMpiR** [RMerl/asuswrt-merlin.ng#400]
I have noticed that my certificate has not updated automatically. 

Issued by :	Let's Encrypt Authority X3
Expires on :	2019/12/13

I have: RT-AC87U with 384.13_2. Any chance of triggering the update manually?

**Comment by krnkris** [comment]
Just upgrade to 384.14. It is updated and works.
Please close this thread.

**Comment by Neeham** [comment]
> I have noticed that my certificate has not updated automatically.
> 
> Issued by : Let's Encrypt Authority X3
> Expires on : 2019/12/13
> 
> I have: RT-AC87U with 384.13_2. Any chance of triggering the update manually?

I think one way to manually update is to click none then choose apply followed by Disable the DDNS Client and click apply once again. Afterward, simply revert back and see if it work.

**Comment by LaMpiR** [comment]
I have tried that and I am stuck with this:

Status :	Updating...

**Comment by jackyaz** [comment]
Update to 384.14

**Comment by LaMpiR** [comment]
> Update to 384.14/384.14_2 depending on your model

The latest version for my model is already being used. 
RT-AC87U: 384.13_2

**Comment by jackyaz** [comment]
Apologies! You'll have to wait for Asus to release an updated GPL for a fix - contact them if you haven't already.

**Comment by RMerl** [comment]
384.13_2 contains the Let's Encrypt fix.  If you are still facing issues, I recommend posting on the support forums at SNBForums.

**Comment by vladut123** [comment]
> Apologies! You'll have to wait for Asus to release an updated GPL for a fix - contact them if you haven't already.

How i can contact them?
