### ISSUE TITLE
Web GUI Inaccessible after changing the name of a main wifi

### ISSUE THREAD

**Issue by rogueops** [RMerl/asuswrt-merlin.ng#401]
I just changed 1 character in the name of my 2G wifi network and it updated, but then I had to reboot the device just to access the web GUI again. I am new to merlin but never had this happen on the official firmware. I am on the last stable version 384.13_1. Not sure what to check to see why the web GUI after the name change would refuse the connection/not allow me to connect after the change using either wifi or cable until I rebooted the device. If this is normal I just want to know so I can be prepared.

**Comment by jorhett** [comment]
Is the node you're connecting from using the same 2.4Ghz wifi, or are you on 5ghz or on Ethernet?
