### ISSUE TITLE
[Security Update Request] Add WPA3 Wifi Encryption

### ISSUE THREAD

**Issue by stopspazzing** [RMerl/asuswrt-merlin.ng#402]
https://www.wi-fi.org/download.php?file=/sites/default/files/private/WPA3_Specification_v2.0.pdf

Standard is released. Just wanted to put this out there to add to a timeline to be integrated, as devices are starting to emerge already and full compatibility is only a software, not hardware.

**Comment by RMerl** [comment]
Ask Asus and Broadcom.  I have no control over Broadcom's SDK.
