### ISSUE TITLE
"block internet access" option not working

### ISSUE THREAD

**Issue by praveen12bnitt** [RMerl/asuswrt-merlin.ng#406]
When I try to "block internet access" for one of the clients, it does not work. Is this a known issue ? 

![Screenshot_20200109-194534](https://user-images.githubusercontent.com/931290/72116580-a80edf00-3318-11ea-8774-601eba427ce7.png)

I am using firmware 384.14

**Comment by digitalec** [comment]
Just thinking out loud - you may have already gone through some of these but:

- Did you verify the MAC address to make sure it's the same device?
- Is the blocked device still able to browse the web or is it just connecting to the router/LAN?
- Have you tried logging in via the gateway IP to verify it's showing as blocked on the web UI as well?

I know the app works with the custom firmware from merlin but that's not to say something can't go wrong.
