### ISSUE TITLE
Remove height restriction and nested scrolling on Adaptive QoS / Bandwidth Monitor page

### ISSUE THREAD

**Issue by jahed** [RMerl/asuswrt-merlin.ng#407]
This is more of a quality of life feature request.

On the "Adaptive QoS / Bandwidth Monitor" page (`/AdaptiveQoS_Bandwidth_Monitor.asp`), the `monitor_qos_bg` container has inline CSS styles which gives it a fixed `510px` height and makes it scroll when there's more than 8 items. This line specifically:

https://github.com/RMerl/asuswrt-merlin.ng/blob/8e7045e066307428f4b263eb298c4d9f65534023/release/src/router/www/AdaptiveQoS_Bandwidth_Monitor.asp#L1405

In an era of smartphones, IoT, laptops etc. it's easy to exceed 8 connections so often I find myself having to scroll a tiny box to find out what's taking up bandwidth, even though my monitor has over 1000 unused vertical pixels on the screen. Removing the fixed height and the scrolling behaviour lets users more easily see the full list of connected machines.

For now I'm using a `userContent.css` rule on Firefox to remove the restriction.

```
@-moz-document url(https://router-domain/AdaptiveQoS_Bandwidth_Monitor.asp) {
  .monitor_qos_bg {
    overflow: initial !important;
    height: auto !important;
  }
}
```

But Firefox may remove this feature in the future (they already disable it by default now) so it'd be nice if there wasn't a fixed height in the first place.

I can send a PR with this change if needed if you're okay with it. But just wanted to know your thoughts before I commit to it.

**Comment by RMerl** [comment]
I think the reason they decided to limit its height is to ensure that on a small screen, you can still see the two traffic meters at the top while scrolling to the desired device.  If the max height is removed, then it becomes impossible to view both a device at the bottom and keeping the two speed meters visible at the same time.

The current max height seem to have been chosen with a typical laptop screen height in mind (from what I can see, as I am currently testing various heights on my laptop right now).

Therefore, I think that while changing this may improve things for users with large monitors, it would be a step backward for mobile/laptop users.  So, I think that overall, the current layout is the least troublesome one.
