### ISSUE TITLE
RT-AC86U LAN speed limit at 200mbps (Runner & Flow cache enabled)

### ISSUE THREAD

**Issue by zhuhang-jasper** [RMerl/asuswrt-merlin.ng#408]
## Info:
Firmware: **384.14_2**
Model: **RT-AC86U** 

## Issues:
LAN speed is limit at 300mbps, but my WiFi speed can go up to 100% at 500mbps.
There's no NAT Acceleration setting, but HW acceleration shows:
Runner: **Enabled**  -  Flow Cache: **Enabled**
![image](https://user-images.githubusercontent.com/3050117/72273060-a4ef5800-3664-11ea-8fba-071b6308fe4b.png)

## QoS Settings:
QoS Type: **Adaptive**
Queue Discipline: **sfq**

## LAN-Switch Control:
Jumbo Frame: **Disable**
Spanning Tree Protocol: **Disable**

![image](https://user-images.githubusercontent.com/3050117/72273260-01eb0e00-3665-11ea-90d0-ec7cebe9690a.png)

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
