### ISSUE TITLE
In wifi connection can't access lan host

### ISSUE THREAD

**Issue by tldzyx** [RMerl/asuswrt-merlin.ng#409]
hardware: RT-AC68U
software: Merlin RT-AC68U_384.14_2
gateway: 192.168.1.1
netmask: 255.255.255.0

wifi notebook ip: 192.168.1.100
lan pc ip: 192.168.1.200

notebook listen: tcp://192.168.1.100:6666
and pc connect is sucess
pc shown: 192.168.1.200 -> 192.168.1.100:6666
notebook shown: 192.168.1.1:9191 -> 192.168.1.100:6666
send data is stable

then, let pc listen: tcp://192.168.1.200:7777
and notebook connect is sucess, too
notebook shown: 192.168.1.100 -> 192.168.1.200:7777
but, the pc shown: 192.168.1.100:6706 -> 192.168.1.200:7777
send data is unstable, send some data then the connect is broken

look at the different between wifi and lan, when lan accepted a connect, the source was peer ip, but when wifi accepted a connect, the source was the gateway.

I try to let "WAN" -> "Internet Connection" -> "Enable WAN" turn to "No", and the connection become to stable, but I can't connect Internet now, so I turn is back to "Yes".

I try connect pc and notebook all in lan, it fine and work, but notebook plug a dock is not concinnity.

So, I encounter a problem: notebook in wifi can't access the server from the pc in lan. such as rdp or git, it's a bug or something I config wrong ? any one can help me let it work correct ?

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
