### ISSUE TITLE
PTR records

### ISSUE THREAD

**Issue by alini76** [RMerl/asuswrt-merlin.ng#414]
I am not sure if this is an issue or if is just a feature which was added later, and I missed the release notes. A few years back I added the following lines in /jffs/configs/dnsmasq.conf.add in order to do reverse DNS for my IPs:

listen-address=127.0.0.1,192.168.50.1,86.120.999.33
log-queries
local=/comp.mydomain.tld/
srv-host=_ldap._tcp,janus.comp.mydomain.tld,389
dhcp-boot=/pxelinux.0,ops,192.168.50.5

address=/gw.mydomain.tld/86.120.999.33
ptr-record=33.999.120.86.in-addr.arpa.,gw.mydomain.tld
address=/mercury.mydomain.tld/86.120.999.61
ptr-record=61.999.120.86.in-addr.arpa.,mercury.mydomain.tld
address=/sender.mydomain.tld/86.120.999.50
ptr-record=50.999.120.86.in-addr.arpa.,sender.mydomain.tld
address=/sender.lectiiinot.ro/86.120.999.56
ptr-record=56.999.120.86.in-addr.arpa.,sender.otherdomain.ro
address=/mx.mydomain.tld/86.120.999.54
ptr-record=54.999.120.86.in-addr.arpa.,mx.mydomain.tld
address=/outgoing.mydomain.tld/86.120.999.59
ptr-record=59.999.120.86.in-addr.arpa.,outgoing.mydomain.tld
address=/masterns.mydomain.tld/86.120.999.38
ptr-record=38.999.120.86.in-addr.arpa.,masterns.mydomain.tld
address=/janus/192.168.50.28
address=/diskstation/192.168.50.27

Yesterday I discovered that the PTR queries are not working anymore. For example, when I try to query the domain it return SRVFAIL.
# nslookup
> set type=PTR
> server 192.168.50.1
Default server: 192.168.50.1
Address: 192.168.50.1#53
> 86.120.999.59
Server:         192.168.50.1
Address:        192.168.50.1#53

** server can't find 59.999.120.86.in-addr.arpa: SERVFAIL

The IPs are Provider Assigned. I checked with my ISP, and they replied that the delegation for my IP subnet is still active.

[I obfuscated the information a bit. I can disclose for who needs the real IPs]

**Comment by RMerl** [comment]
This is more of a support question.  I suggest asking on the SNBForums support forums, where people familiar with dnsmasq might be able to assist you.
