### ISSUE TITLE
iperf3,wget,curl,ssh,scp not support ipv6

### ISSUE THREAD

**Issue by haohetao** [RMerl/asuswrt-merlin.ng#420]
iperf3,wget,curl,ssh,scp command is timeout when host address is ipv6 address.

**Comment by RMerl** [comment]
What firmware are you running?  Iperf3 is not part of my firmware.

**Comment by haohetao** [comment]
iperf3 from entware-ng
The problem in the ip6tables
ip6tables deny all packet to INPUT Chain
I run 

> ip6tables -D INPUT -j DROP

to fix

**Comment by RMerl** [comment]
Don't do that.  You are opening your whole router to the entire world by doing this.

**Comment by haohetao** [comment]
@RMerl the ip6tables default deny all packet to router host(not foward),also can't configuration from web ui.
I disabled firewall for tested,not really.

**Comment by stehpancar** [comment]
What would the most restrictive rule be to allow curl, wget and all the other to function with IPv6 hosts (and their -6 option)?
Would `ip6tables -I INPUT 1 -j ACCEPT --match state --state ESTABLISHED`, similar to existing iptables (ipv4) INPUT rule?

I also need curl (or wget) working for a custom Dynamic DNS update script to update IPv6 entries.
