### ISSUE TITLE
384.15 DHCP start IP reset after submit LAN IP Apply button

### ISSUE THREAD

**Issue by wincorex** [RMerl/asuswrt-merlin.ng#421]
LAN IP / Server DHCP / Start IP range - will reset to 192.168.2.2 from 192.168.2.100 when LAN IP / Hostname - change and Apply.

**Comment by dave14305** [comment]
There should be a pop-up warning about this after you hit apply. Happened to me before because I didn't read the warning properly.

**Comment by wincorex** [comment]
Oh, there is, so it's probably localization issue, because czech translation of this pop-up message does not mentioning it, or not in  understandable way at least.

**Comment by nospam2k** [comment]
So, is this not a bug? While I understand that changing the router's IP address SHOULD reset the dhcp range, changing anything else (domain, gateway, etc.) should not.

**Comment by wincorex** [comment]
Ok, it's not bug.
Close.
