### ISSUE TITLE
User script - LAN/WiFi event

### ISSUE THREAD

**Issue by nullvalue1** [RMerl/asuswrt-merlin.ng#424]
There is already a wan-event for things like connect/disconnect. There should be an ability to have a script execute when a client connects to the LAN and/or Wifi. This event would receive parameters about the connection.

Or does this capability already exist?

**Comment by RMerl** [comment]
No possible, as I have no way of knowing when that occurs.

**Comment by asaddon** [comment]
@RMerlin For the Wi-Fi event can't we use the Wireless Log as a base to determine the client connection/disconnection along with the MAC/IP address matching?

**Comment by asaddon** [comment]
@RMerl ........
(Why can't I edit the comment on GH app) 🙄🙄

**Comment by RMerl** [comment]
That would require constantly polling, and would only cover Wifi clients - too hackish and unreliable.  It's not an event then.
