### ISSUE TITLE
syslog: vpn_log_error: "537"

### ISSUE THREAD

**Issue by tinysun** [RMerl/asuswrt-merlin.ng#431]
I want to link a openvpnserver,but the log show this error,why?These isnot other info in logfile.
syslog: vpn_log_error: "537"

server:asus rt-ac86u official rom

client:RT-AC56U merlin 380.xx

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
