### ISSUE TITLE
Feature request: What about f2fs?

### ISSUE THREAD

**Issue by Lalarian** [RMerl/asuswrt-merlin.ng#432]
Hello!
I have been using Asus Merliln for some time and experienced it as stable enough for sing it longer.
Now I wanted to add some USB 3.0 drives and notcied that I could only format them as ext2, ext3 and NTFS.
I wonder:
Could you do future build with f2fs support?
I think that today most connected USB storages are flash drives and the advantages for speed and lifetime of modern flash friendly file systems compared to the old filesystems are well known.
If there's a space issue for many models: Why is ext3 in there? Are there really people using ext3 with ext4 being better as a journaling file system in any regard?
So I thin it woudl be great if f2fs could be added to the kernel.
thank you for reading! :)

**Comment by RMerl** [comment]
There are no plans to add any other filesystems.  Even less in this particular case since it only got added with Linux 3.8, which is newer than what most of the supported models use.
