### ISSUE TITLE
Update Inadyn to v2.6

### ISSUE THREAD

**Issue by SimonPilkington** [RMerl/asuswrt-merlin.ng#434]
Inadyn v2.6 has been released with support for a couple of new providers among other things. See full changelog [here](https://github.com/troglobit/inadyn/releases/tag/v2.6).

**Comment by RMerl** [comment]
Done with 1f135b681ff708560160f062c619599d722a8d5f.

**Comment by SimonPilkington** [comment]
Thanks.
