### ISSUE TITLE
Number fields on Smart Connect page in addition to slider

### ISSUE THREAD

**Issue by babbahotep** [RMerl/asuswrt-merlin.ng#441]
Not sure if many people use the Smart Connect Rule page. 

I find it very difficult to set all the sliders to the value I want. It's very imprecise. 

Would it be possible to have a textfield behind each slider, so we can punch in the precise numbers?

Thank you

**Comment by tekneek** [comment]
I can click on the slider and use left and right arrow keys to move in single digit increments. Have you tried that?

**Comment by babbahotep** [comment]
ahh no didnt know that thank you
