### ISSUE TITLE
require to split the temperature of 5GHz-1 and 5GHz-2 on RT-AC5300

### ISSUE THREAD

**Issue by kit132** [RMerl/asuswrt-merlin.ng#442]
Hello sir,

Would you split the temperature of 5GHz-1 and 5GHz-2 chip on web GUI?
Also, i disabled 5GHz-1. The temperature field shown "disable" and wifi icon shown half signal on GUI.
Build version: Asuswrt-Merlin 384.15
Device: ASUS RT-AC5300
Thanks.

**Comment by RMerl** [comment]
Doing so on the graphic page would be tricky, but it should be easy to do on the Sysinfo page.

**Comment by RMerl** [comment]
Done with commit 6cbe6a48e5ef08ce39ac42f49ad225f24e9417bb.
