### ISSUE TITLE
/jffs/scripts/service-start is missing after a refresh update to 384.15 use AMPM.

### ISSUE THREAD

**Issue by zw963** [RMerl/asuswrt-merlin.ng#448]
as i describe on title, on older merlin system,  after init entware use `entware-setup.sh`, we can always see a script, named /jffs/scripts/service-start, when run it, which always try to start all services in /opt/etc/init.d

But, after use this new release, after init entware use new AMTM script, only generate two script,
`post-mount`,  `services-start`, where is the famous "service-start" go?

Thank you.

my router type: AC5300

**Comment by RMerl** [comment]
Amtm moved the unslung command to a post-mount script instead of services-start, as it is a more appropriate location.  Services-start might run too early, causing it to delay starting the Entware services, or flat out miss them, while post-mount will run after the required USB disk has been successfully mounted.

**Comment by RMerl** [comment]
Also, there never was a service-start in the firmware, it always was services-start.

**Comment by wengych** [comment]
I have same issue, and after reboot the router, I can not use opkg anymore without /opt link .

**Comment by zw963** [comment]
> Also, there never was a service-start in the firmware, it always was services-start.

Sorry, i means `/jffs/scripts/services-start`.

Anyway, for those don't want broken older script guys, following is original file

```sh
#!/bin/sh

RC='/opt/etc/init.d/rc.unslung'

i=30
until [ -x "$RC" ] ; do
  i=$(($i-1))
  if [ "$i" -lt 1 ] ; then
    logger "Could not start Entware"
    exit
  fi
  sleep 1
done
$RC start
```
