### ISSUE TITLE
Shouldn't we need to fix it too? // VPN hijacking on Linux (and beyond) systems

### ISSUE THREAD

**Issue by odkrys** [RMerl/asuswrt-merlin.ng#449]
https://lwn.net/Articles/806546/
https://seclists.org/oss-sec/2019/q4/123

https://lore.kernel.org/wireguard/20191205191318.GA44156@zx2c4.com/

WireGuard has already added rule to their script. (wg-quick)
According to the mailing list, policy-based IPsec is not affected, but routing-based vpn is.
However, this is not considered seriously because it requires physical access to the client's gateway.
Routers should have less impact than Unix PCs.

Anyway, I report it because it is worth reading.

**Comment by Syst3mSh0ck** [comment]
From the third link:

> wg-quick(8) has added a few iptables(8)
> rules. In particular, Wireshark have added a rule that is something like:
> 
>     iptables -t raw -I PREROUTING ! -i wg0 -d 10.182.12.8 -m addrtype ! --src-type LOCAL -j DROP
> 
> where wg0 is the WireGuard interface and 10.182.12.8 is the local IP of
> the interface.
> 
> This says to drop all packets that are sent to that IP address that
> aren't coming from the WireGuard interface. And it's done very early in
> Netfilter, in the "raw" table. The researchers have confirmed that this
> mitigates the issue.
