### ISSUE TITLE
Signature update failed

### ISSUE THREAD

**Issue by panther7** [RMerl/asuswrt-merlin.ng#457]
Last works November.

Log only:
```
Mar 23 15:46:48 rc_service: httpds 273:notify_rc start_sig_check
```

![Image_2020-03-23 14 45 32](https://user-images.githubusercontent.com/3808250/77323236-3807d680-6d15-11ea-94d2-9577bbe031d2.png)

**Comment by RMerl** [comment]
Not a firmware issues.  Works for everyone else, and that code is closed source therefore 100% identical to stock firmware.
