### ISSUE TITLE
RT-AC68U dnsmasq port 0

### ISSUE THREAD

**Issue by regae** [RMerl/asuswrt-merlin.ng#458]
when I set DNSMASQ port to 0, client is not getting any dns ip, I had to set dhcp-option 6.
right now using 384.16 beta2, I wasn't using port 0 before beta2, so I cannot notice if this is happened before
is it on purpose ?  if it isn't maybe give an else statement after 
`if ((*value && inet_addr(value)) || (*value2 && inet_addr(value2)))` 
in services.c with dhcpd_dns_router=1 ?

**Comment by RMerl** [comment]
0 is not a valid port.  Working as intended.
