### ISSUE TITLE
Hoping for some clues

### ISSUE THREAD

**Issue by drekka** [RMerl/asuswrt-merlin.ng#462]
There are a bunch of people with AX92s which are all exhibiting the same fault and I’m hoping some here may have some ideas what the problem might be.

The problem is that periodically the routers wfd0-thrd and/or wfd1-thrd processes start consuming 100% CPU causing the router to hang. At the same time the logs fill with “Failed to allocate new ring buffer”.

So far Ive ruled out AIMesh, Smart Connect, And roaming assistant. Ive also had it on a factory reset single node.

Any ideas welcome.

Thank you.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
