### ISSUE TITLE
Intercept NTP client requests is broken

### ISSUE THREAD

**Issue by danlsgiga** [RMerl/asuswrt-merlin.ng#477]
The `Administration`->`System`->`Intercept NTP client requests` is broken.

When enabled, even pointing the NTP server to the ip address of the router it does not work.

`Asus RT-AX88U`
Firmware Version: `384.15`

**Comment by RMerl** [comment]
Works for me.  I just had my VM issue an NTP request to time.nrc.ca, and the router intercepted it conntrack shows the ntp request was sent to the router itself instead of the remote server.

**Comment by danlsgiga** [comment]
K, I just upgraded to `384.16` and it works now! Thanks!
