### ISSUE TITLE
GT-AX11000 Support?

### ISSUE THREAD

**Issue by smitpau** [RMerl/asuswrt-merlin.ng#486]
Hi,

I appreciate this isn't an issue, but unsure where else to ask this, is it likely the GT-AX11000 will be supported at some point in the future?

Thanks,

Paul

**Comment by RMerl** [comment]
I no longer speculate about future model support.  Unless announced otherwise, expect a model to not be supported.

**Comment by smitpau** [comment]
Okay thanks np appreciate it's guesswork.
