### ISSUE TITLE
How to set up OpenVPN to use wan1?

### ISSUE THREAD

**Issue by 3038922** [RMerl/asuswrt-merlin.ng#491]
I have two lines. Wan1 is the external network. Wan2 is the internal network.
I set up routing rules.
But it doesn't work.
Do you need to set wan1 for OpenVPN? How can I set it?

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
