### ISSUE TITLE
Set DNS lookup when on 4G modem

### ISSUE THREAD

**Issue by jdarling** [RMerl/asuswrt-merlin.ng#492]
So, I am using a 4G modem with my Asus 1900 and according to all of the documentation out there I should be able to set the DNS server on the WAN page, except if you enable USB, Modem and disable Dual WAN this option goes away.  I am able to ssh into the router and set this configuration manually but of course I loose it on reboot, not ideal.  Any chance of getting an option or someone pointing me in the direction of how I can set this and persist it?

**Comment by asaddon** [comment]
Well if you can do it via SSH then most easiest way to make it persistent is to use custom script like nat-start and use it to issue the SSH commands every boot.
