### ISSUE TITLE
[384.16 regression] RT-AC3100 - OpenVPN - Could not determine IPv4/IPv6 protocol

### ISSUE THREAD

**Issue by mvadu** [RMerl/asuswrt-merlin.ng#493]
On 384.16 using RT-AC3100. I have 2 open vpn clients setup and been using them for quite some time.  After the firmware upgrade, it fails to connect, it keeps failing with these errors in syslog. 

```
Apr 16 18:33:13 ovpn-client4[23990]: RESOLVE: Cannot resolve host address: us-east.windscribe.com:443 (Name or service not known)
Apr 16 18:33:13 ovpn-client4[23990]: Could not determine IPv4/IPv6 protocol
Apr 16 18:33:13 ovpn-client4[23990]: SIGUSR1[soft,init_instance] received, process restarting
```

I even tried editing the config file to explicitly target udp4, and uploaded, but issue still exists.

```
client
dev tun
proto udp4
remote us-east.windscribe.com 443
```

**Comment by RMerl** [comment]
If your router is unable to resolve the hostname then there is a problem with your WAN DNS configuration.
