### ISSUE TITLE
Policy-based port routing integration into the UI

### ISSUE THREAD

**Issue by elChapoSing** [RMerl/asuswrt-merlin.ng#494]
It's more of a feature request than an issue really.
It would be amazing if the current policy-based port routing would be integrated into the UI the same way IP currently are.
I'm happy to help in any way I can if pointed in the right direction but I'm afraid this would probably be above my paygrade.

**Comment by RMerl** [comment]
No possible.  Policy routing is implemented through the kernel routing table, which can only understand IP addresses.  Port-based routing would require a completely different implementation, which would not be compatible with hardware acceleration or Trend Micro's DPI engine.
