### ISSUE TITLE
Client list Empty, Console errors 384.17

### ISSUE THREAD

**Issue by jobrien2001** [RMerl/asuswrt-merlin.ng#500]
I checked the response of update_clients.asp and it is returning a json client list. However. it never shows anywhere.

I am getting console errors and a missing css?  I can provide more info if needed.

`
13[Violation] Avoid using document.write(). <URL>
state.js:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ state.js:1
state.js:2 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ state.js:2
state.js:3 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ state.js:3
state.js:4 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ state.js:4
VM2259 state.js:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ VM2259 state.js:1
VM2259 state.js:2 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ VM2259 state.js:2
VM2259 state.js:3 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ VM2259 state.js:3
VM2259 state.js:4 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ VM2259 state.js:4
VM2261 table.js:177 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ VM2261 table.js:177
state.js:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ state.js:1
state.js:2 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ state.js:2
state.js:3 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ state.js:3
state.js:4 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ state.js:4
2state.js:1 [Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ state.js:1
state.js:2 [Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ state.js:2
state.js:3 [Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ state.js:3
jquery.js:5 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js:5
ajax @ jquery.js:5
_evalUrl @ jquery.js:5
domManip @ jquery.js:4
append @ jquery.js:4
(anonymous) @ asus_eula.js:3
jquery.js:4 GET http://192.168.1.1/css/basic.css net::ERR_ABORTED 404 (Not Found)
(anonymous) @ jquery.js:4
domManip @ jquery.js:4
append @ jquery.js:4
(anonymous) @ asus_eula.js:2
index.asp:410 [Violation] 'setTimeout' handler took 59ms
`

**Comment by sammyguyana** [comment]
Hello, I have the same issue.
