### ISSUE TITLE
Tmobile -1900 (RT-AU68U) - repeater mode on 5ghz not working

### ISSUE THREAD

**Issue by jsonp80** [RMerl/asuswrt-merlin.ng#502]
Trying to setup repeater mode on 5ghz and it not showing up on wifi discovery, i try to set manual but it didn't work. It won't connect and i have to reset.

**Comment by RMerl** [comment]
That model is not supported.

https://github.com/RMerl/asuswrt-merlin.ng/wiki/Supported-Devices

Plus, this is a bug tracker, not a support site.
