### ISSUE TITLE
ASUS RT-AC88U 384.17 JFFS Unmounted Problem

### ISSUE THREAD

**Issue by xkelvinchiax** [RMerl/asuswrt-merlin.ng#504]
JFFS UNMOUNTED problem.

Model - RT-AC88U
Firmware Version - 384.17
Firmware Build - Sun Apr 26 02:26:32 UTC 2020 merlin@2bcb57c
Bootloader (CFE) - 3.0.0.2

**Comment by xkelvinchiax** [comment]
Note: Downgraded to 384.16, JFFS Partition Works

**Comment by RMerl** [comment]
Zero change related to JFFS in 384.17, changes were only related to OpenSSL, OpenVPN, dnsmasq, curl, and three minor changes at the webui level.  Please use the forums for support and troubleshooting of your setup.
