### ISSUE TITLE
Accessing management page on macos doesn't work

### ISSUE THREAD

**Issue by mertzjames** [RMerl/asuswrt-merlin.ng#511]
After upgrading my AC-3100 to Merlin, I noticed that I wasn't able to connect to the management page from my mac machine.  Furthermore, it appeared to cause a tremendous amount of resource utilization on the mac as soon as I did.  Even more interesting, was that all my apple devices appeared to be operating at very slow speeds, almost to the point of not being operable.

Reverting back to the official ASUS WRT version solved this.  Not sure how to debug this but I'm willing to work with you on it.

**Comment by Germandoe** [comment]
It's recommended to do a full factory reset before upgrading to Merlin, also have you tried from a different browser etc.?
My MBP seems to mess up the functionality of the router management page when using Chrome, Safari works fine tho.
