### ISSUE TITLE
My TM-AC1900 is stuck on firmware version 3.0.0.4.376.47_0

### ISSUE THREAD

**Issue by osokona** [RMerl/asuswrt-merlin.ng#516]
I have a TM-AC1900 with Merlin RT-AC68U firmware version 3.0.0.4.376.47_0. 
Is there anyway I can upgrade this to the latest firmware with AiMesh?

![Capture](https://user-images.githubusercontent.com/6461953/81618620-bc8de180-93b5-11ea-82f9-f98ddfe3145a.JPG)

**Comment by RMerl** [comment]
https://github.com/RMerl/asuswrt-merlin.ng/wiki/Supported-Devices
