### ISSUE TITLE
AC86U: merlin 384.17

### ISSUE THREAD

**Issue by mb13** [RMerl/asuswrt-merlin.ng#517]
I upgraded from 384.16 to 384.17 and I noticed that my 2GHz connected Samsung TV sometimes is stuck when playing video via Media Server. I put back version 16 and I don't have this issue anymore.

But it was not easy to downgrade. Firmware upgrade was successful maybe after 4th or 5th attempt. This seems to me another issue.

**Comment by RMerl** [comment]
Wifi is closed source and outside of my control.
