### ISSUE TITLE
LAN-Ports limited to 100mbps on AX88U

### ISSUE THREAD

**Issue by SuperMeowBro** [RMerl/asuswrt-merlin.ng#520]
Hello,

i've had the problem, that all LAN-Ports where limited to 100mbps on Asus AX88U. WAN Port was on 1000mbps like expected. 

- Firmware Version is 384.17
- Tried different cables (Cat5e, Cat6), no success.
- Tried to restart the Router, no success.
- Tried a factory reset, no success.

As i was desperated, i had enabled "Jumbo Frames" and the problem was gone. The LAN-Ports were not limited to 100mbps anymore! Also after disabling "Jumbo Frames" again, the problem didn't come back!

Maybe there is a unknown bug, that could be fixed, so that other people dont have to spend hours of try and error various settings... :)

**Comment by RMerl** [comment]
No one else reporting a similar issue, and I doubt the auto-negotiate protocol received any changes in years within the switch driver.
