### ISSUE TITLE
384.17 in AP mode claiming DHCP addresses

### ISSUE THREAD

**Issue by gsly** [RMerl/asuswrt-merlin.ng#528]
I have two RT-AC68U that I recently moved from DD-WRT to Merlin 384.17. Prior to the switch I also have a headless Pi-hole DNS server running on a Pi4 at IP 10.9.8.24.
Since the move to Merlin, the Pi4 has been going off-line randomly and I eventually hooked a monitor/keyboard to discover the Pi4 was running fine but something was claiming it's IP and the DHCP service was releasing it's (static) IP bringing the network down. In the logs I see:

`May 27 01:44:49 pi4 dhcpcd[525]: eth0: hardware address e0:3f:49:93:af:40 claims 10.9.8.24
May 27 01:44:49 pi4 dhcpcd[525]: eth0: hardware address e0:3f:49:93:af:40 claims 10.9.8.24
May 27 01:44:49 pi4 dhcpcd[525]: eth0: 10 second defence failed for 10.9.8.24
May 27 01:44:49 pi4 dhcpcd[525]: eth0: deleting route to 10.9.8.0/24
May 27 01:44:49 pi4 dhcpcd[525]: eth0: deleting default route via 10.9.8.1
May 27 01:44:49 pi4 avahi-daemon[386]: Withdrawing address record for 10.9.8.24 on eth0.
May 27 01:44:49 pi4 avahi-daemon[386]: Leaving mDNS multicast group on interface eth0.IPv4 with address 10.9.8.24.
May 27 01:44:49 pi4 avahi-daemon[386]: Interface eth0.IPv4 no longer relevant for mDNS.
`

In this case, the MAC E0:3F:49:93:AF:40 is eth0/br0/vlan1 on one of the AC68U units and I've also seen the MAC of the other unit in the logs doing the same thing!
In AP mode there isn't a DHCP server exposed in the GUI and BOTH units are statically assigned an IP address (10.9.8.2 and 10.9.8.3) and the only reference to 10.9.8.24 in the DNS Server1 field of the LAN IP page.
Why are these units broadcasting packets claiming an IP they shouldn't have?

**Comment by AlecBLI** [comment]
I have the same issue,  running 480.18 firmware on Tmo converted unit.
