### ISSUE TITLE
Clients: 0 (Searching, please wait...) Bug

### ISSUE THREAD

**Issue by slalom-ms** [RMerl/asuswrt-merlin.ng#534]
Since the recent update 384.17 on my AC68U The Clients tab on the front page shows 0 and just shows "Searching, please wait...". I reset the router and all the settings and its still the same issue. Any idea?

![image](https://user-images.githubusercontent.com/41703461/83996814-f3aad080-a92a-11ea-8942-3ea91327b69c.png)

![image](https://user-images.githubusercontent.com/41703461/83996825-f9a0b180-a92a-11ea-8296-5ecdedc3d76e.png)

**Comment by asaddon** [comment]
Is this a genuine AC68U of a transformed T-Mobile unit?

**Comment by asaddon** [comment]
Or*

**Comment by slalom-ms** [comment]
Transformed T-Mobile unit. But it was working on previous updates.

On Jun 8, 2020 8:18 PM, Asad <notifications@github.com> wrote:

Or*

**Comment by RMerl** [comment]
This model is not supported, and never was either.  Asus has taken active measures over time to prevent people from actively hacking it, and one of the symptoms of their measures is exactly what you describe - the networkmap not working.
