### ISSUE TITLE
Question: Can IPSEC Net-to-Net Client/Peer be enabled for RT-AC5300?

### ISSUE THREAD

**Issue by brad-charboneau** [RMerl/asuswrt-merlin.ng#544]
I see that some such as the RT-AC86U have an option to enable the Net-To-Net IPSEC VPN. Is it possible to enable this on the RT-AC5300 and if so, How can I do this? If this feature is not available, is it being worked on to be supported in the future?

Reference: https://www.snbforums.com/threads/asuswrt-merlin-site-to-site-vpn-with-2-rt-ac86u-coming-from-dd-wrt-how-to.47583/#post-464465

**Comment by jackyaz** [comment]
Please do not use Github's Issue tracker for support requests. Use the support forums at [SNBForums](https://www.snbforums.com/forums/asuswrt-merlin.42/) instead. The issue tracker is for development/bug tracking purposes only!
