### ISSUE TITLE
 * opkg_download: Failed to download http://bin.entware.net/armv7sf-k2.6/Packages.gz, wget returned 8.

### ISSUE THREAD

**Issue by tkalfaoglu** [RMerl/asuswrt-merlin.ng#547]
I am unable to download anything..
# opkg update
Downloading http://bin.entware.net/armv7sf-k2.6/Packages.gz
*** Failed to download the package list from http://bin.entware.net/armv7sf-k2.6/Packages.gz

Collected errors:
 * opkg_download: Failed to download http://bin.entware.net/armv7sf-k2.6/Packages.gz, wget returned 8.

My IP is in the range of  78.186.110.x   -- static IP

**Comment by kissglay** [comment]
This is not a FW issue. It's simply because the site is down for the moment.

**Comment by jackyaz** [comment]
Please do not use Github's Issue tracker for support requests. Use the support forums at [SNBForums](https://www.snbforums.com/forums/asuswrt-merlin.42/) instead. The issue tracker is for development/bug tracking purposes only!
