### ISSUE TITLE
Segmentation fault on some software installed by opkg

### ISSUE THREAD

**Issue by 372046933** [RMerl/asuswrt-merlin.ng#549]
`vim` and `bash` failed to start and just crashed each time on 384.18 AC88U

**Comment by jackyaz** [comment]
Please do not use Github's Issue tracker for support requests. Use the support forums at [SNBForums](https://www.snbforums.com/forums/asuswrt-merlin.42/) instead. The issue tracker is for development/bug tracking purposes only!

**Comment by 372046933** [comment]
Thanks
