### ISSUE TITLE
Struggling with dnsmasq

### ISSUE THREAD

**Issue by NogNeetMachinaal** [RMerl/asuswrt-merlin.ng#550]
I'm struggling with dnsmasq and a custom config.

What I'm trying to accomplish:
Porting a working dnsmasq install/config from Ubuntu to Merlin.
On Ubuntu there are 3 config files: dnsmasq.conf, static-hosts.conf and static-dhcp-hosts.conf (attached in zip).
The file static-hosts contains a series of hosts with fixed IP-adresses.
The file static-dhcp-hosts contains a series of hosts, their MAC-address and designated IP-adresses.

What is done on Merlin (running on RT-AC68U with 384.18):
- Formatted and activated JFFS
- Created a folder /jffs/configs/dnsmasq.d
- Copied the 3 conf files to this folder.
- Reboot

Doing a nslookup with a host in static-hosts.conf returns: nslookup: can't resolve 'as-1.itv.lan'.
Doing a nslookup with 192.168.139.1 (the LAN-IP of the router) returns rtr.itv.lan => correct

Commands:
nslookup as-1.itv.lan 192.168.139.1
nslookup 192.168.139.1 192.168.139.1

Please note that at this time, the router is not connected to the Internet.

Reference: https://github.com/RMerl/asuswrt-merlin.ng/wiki/Custom-domains-with-dnsmasq

Any suggestions?

Cheers - Will

[dnsmasq-configs.zip](https://github.com/RMerl/asuswrt-merlin.ng/files/4873507/dnsmasq-configs.zip)

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
