### ISSUE TITLE
AC68U ( the file transferred is not a valid firmware image)

### ISSUE THREAD

**Issue by cache173** [RMerl/asuswrt-merlin.ng#551]
Hi,

I have a Tmobile AC1900 with the latest stock Asus AC68U_300438520630 firmware.   I wanted to use Merlin 380.xx,.  So I followed the instruction on the below link.  I flashed with 378.55 before I can flash 380.xxx.  After flashing 378.55.  The router shows 3.0.0.4.376_3199, then I tried to flash it to 380.xxx.   It said " the file transferred is not a valid firmware image " .  I tried to redo CFE but there is not Telnet or SSH in the Admin/system.   it is gone. Please help.

https://github.com/RMerl/asuswrt-merlin.ng/wiki/Installation
The RT-AC68U and RT-AC56U need to be at least on firmware 378.55 (or the last 378.xxx version from Asus) before you can flash 380.xx, due to the partition size change.

**Comment by RMerl** [comment]
Your device is not supported.

https://github.com/RMerl/asuswrt-merlin.ng/wiki/Supported-Devices
