### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by tkalfaoglu** [RMerl/asuswrt-merlin.ng#555]
I tried an update today but was greeted with these errors:

Collected errors:
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Base.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Formatter/Base.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Formatter/Color.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Formatter/Console/ParallelSession.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Formatter/Console/Session.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Formatter/Console.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Formatter/File/Session.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Formatter/File.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Formatter/Session.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Harness/Env.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Harness.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Object.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Aggregator.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Grammar.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Iterator/Array.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Iterator/Process.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Iterator/Stream.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Iterator.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/IteratorFactory.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Multiplexer.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result/Bailout.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result/Comment.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result/Plan.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result/Pragma.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result/Test.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result/Unknown.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result/Version.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result/YAML.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Result.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/ResultFactory.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Scheduler/Job.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Scheduler/Spinner.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Scheduler.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/Source.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/SourceHandler/Executable.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/SourceHandler/File.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/SourceHandler/Handle.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/SourceHandler/Perl.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/SourceHandler/RawTAP.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/SourceHandler.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/YAMLish/Reader.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser/YAMLish/Writer.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-tap wants to install file /opt/lib/perl5/5.28/TAP/Parser.pm
        But that file is already provided by package  * perl-test-harness
 * resolve_conffiles: Existing conffile /opt/etc/ssh/sshd_config is different from the conffile in the new package. The new conffile will be placed at /opt/etc/ssh/sshd_config-opkg.
 * check_data_file_clashes: Package python3-setuptools wants to install file /opt/bin/easy_install
        But that file is already provided by package  * python-setuptools
 * check_data_file_clashes: Package perlbase-app wants to install file /opt/lib/perl5/5.28/App/Prove/State/Result/Test.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-app wants to install file /opt/lib/perl5/5.28/App/Prove/State/Result.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-app wants to install file /opt/lib/perl5/5.28/App/Prove/State.pm
        But that file is already provided by package  * perl-test-harness
 * check_data_file_clashes: Package perlbase-app wants to install file /opt/lib/perl5/5.28/App/Prove.pm
        But that file is already provided by package  * perl-test-harness
 * resolve_conffiles: Existing conffile /opt/etc/transmission/settings.json is different from the conffile in the new package. The new conffile will be placed at /opt/etc/transmission/settings.json-opkg.
 * check_data_file_clashes: Package python3-base wants to install file /opt/bin/python
        But that file is already provided by package  * python-base
 * check_data_file_clashes: Package python3-pip wants to install file /opt/bin/pip
        But that file is already provided by package  * python-pip
 * resolve_conffiles: Existing conffile /opt/etc/minidlna.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/minidlna.conf-opkg.
 * resolve_conffiles: Existing conffile /opt/etc/php.ini is different from the conffile in the new package. The new conffile will be placed at /opt/etc/php.ini-opkg.
 * check_data_file_clashes: Package perlbase-test wants to install file /opt/lib/perl5/5.28/Test/Harness.pm
        But that file is already provided by package  * perl-test-harness
 * resolve_conffiles: Existing conffile /opt/etc/bind/named.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/bind/named.conf-opkg.

**Comment by JackMerlin** [comment]
Update to what? What firmware version? What model? If you do not provide this basic information, it will be difficult for others to help you.

BTW, it seems to be an entware problem. There are no entware experts here. Please reopen your questions on the SNBforum and close here.
