### ISSUE TITLE
TM-RT-AC1900 upgraded to AC68U asuswrt merlin keeps resetting itself

### ISSUE THREAD

**Issue by typhoonss92** [RMerl/asuswrt-merlin.ng#556]
I have 2 of these devices, 1 is router and other AP. The AP has no issues, the router for some reason keeps resetting itself every couple of days, usually between 12:30am and 1:30am. When it does this it resets back to default so my port forwards dont work and it sets the ssid to asus and asus_5g. The AP keeps the wifi working on my normal ssid so I don't know its a problem till I check my home-assistant. I was on merlin 318.17 when it started and figured upgrade to 318.18, still did it. I had a usb stick plugged in for the traffic history location, disabled that and removed the usb and still did it. I swapped the 2 devices made the AP the router and the router the AP, make sure it is not hardware and same thing 2 days later it reset. I was thinking maybe it could be the parental control for the timer to shut down the xbox, so I just turned that off this morning. Unfortionatly there is no logs as it resets itself. Anyone have any ideas how to troubleshoot this or any possible reasons why it would just reset itself?

**Comment by RMerl** [comment]
That device is not supported:

https://github.com/RMerl/asuswrt-merlin.ng/wiki/Supported-Devices

Asus has various measures in place to prevent it from working properly, for legal reasons.
