### ISSUE TITLE
RT-AC88U 384.18 reboots on its own and reverts settings

### ISSUE THREAD

**Issue by typhoonss92** [RMerl/asuswrt-merlin.ng#560]
Weird, while sleeping it just reboots about 6-7am from what I can tell and looses most of the config(password, port forwards, jffs, 2.4 ssid) but it keeps the 5.0 ssid. I have had this router for 3 days and it has done it each morning. I bought this router because I had a tm-rt-ac1900 upgraded to ac68u with merlin and it would get reset every other or third morning(That must have been tm or asus)
But now I have a legit model and upgraded to merlin and same thing seems to be happening. Any ideas.

**Comment by Syst3mSh0ck** [comment]
Sounds like a potential mains power related issue? Try a different outlet and/or remove any extensions. Odd.
