### ISSUE TITLE
Bell FTTH doesnt reconnect when link drop

### ISSUE THREAD

**Issue by jonathanmasseurca** [RMerl/asuswrt-merlin.ng#562]
I installed a RT-AX88U with MC220L and removed the HH3000.

Everything works fine except sometime the PPPoE link drop after a random time.

Sometime it work for few days and then it drop off. (On the router interface it say Disconnected)

I need to reboot the router everytime that it happen, Is there something that I can enable to auto-reconnect? I'm using Asuswrt-Merlin version 384.18.

When it happen I have those event :

Jul 8 02:00:41 pppd[510]: Connection terminated.
Jul 8 02:00:41 pppd[510]: Modem hangup

I also saw on this forum that people with asus-wrt meet the same issue.

https://www.snbforums.com/threads/script-to-reconnect-wlan-if-dropped.20313/

It would be nice to have a checkbox or something that detect that the pppoe link has been dropped and make a reconnect without having to reboot.

**Comment by Syst3mSh0ck** [comment]
Does this happen with the official firmware? It would be helpful to see the IPCP log from pppd but I'm unsure how to do this with AsusWRT. Maybe someone else can assist.

**Comment by paldier** [comment]
Enable Internet Detection, PPP echo

**Comment by jonathanmasseurca** [comment]
I didnt try the original firmware, I will try it,

My Pppoe settings are 
![3959B29A-A121-4A81-903B-3251DB9C8C94](https://user-images.githubusercontent.com/49443479/87830570-4abb9380-c84f-11ea-9943-96b3299e452e.jpeg)

**Comment by paldier** [comment]
99999? so bad, 10 or 15 is better, which means 60 or 90 seconds

**Comment by jonathanmasseurca** [comment]
Thanks, i made the change, maybe this it, i will test it
