### ISSUE TITLE
AX branch does not build from axhnd.657x

### ISSUE THREAD

**Issue by shural** [RMerl/asuswrt-merlin.ng#564]
I am sure I miss something but I could not find any clues in wiki. Cannot build AX models from src-rt-5.02axhnd.657x. Building RT-AX88U from src-rt-5.02axhnd works half way though (failed at build_crypto in openssl) but least it proves prebuilt configurations including toolchains work well.

Error messages is like below,

root@XXXXX:~/asuswrt-merlin.ng/release/src-rt-5.02axhnd.675x# make RT-AX56U
Makefile:69: /root/asuswrt-merlin.ng/release/src-rt-5.02axhnd.675x/targets/9GW/9GW: No such file or directory
MAKELEVEL='0' MAKEFLAGS='' MAKECMDGOALS='RT-AX56U' MAKEOVERRIDES='' MAKEFILE_LIST=' Makefile chip_profile.tmp target.mak version.conf platform.mak build/Makefile'
MY_DEFAULT_ANY_FIRST_RUN='0' MY_MKENV_FIRST_RECURSION=''
./release/maketargets 9GW
make: ./release/maketargets: Command not found
/root/asuswrt-merlin.ng/release/src-rt-5.02axhnd.675x/make.common:94: /root/asuswrt-merlin.ng/release/src-rt-5.02axhnd.675x/targets/9GW/9GW.RT-AX56U: No such file or directory
/root/asuswrt-merlin.ng/release/src-rt-5.02axhnd.675x/make.common:311: *** KERNEL VERSION not specified in profile /root/asuswrt-merlin.ng/release/src-rt-5.02axhnd.675x/targets/9GW/9GW.RT-AX56U.  Stop.

Any clue would be helpful. Thanks much!

Btw, make menuconfig does not work either from release/kernel/linux4.1 folder.

**Comment by RMerl** [comment]
I suggest you use the support forums at SNBForums instead of this bug tracker.
