### ISSUE TITLE
RT-AX88U (and RT-AC86U) - Adaptive QoS Interface is missing a few things

### ISSUE THREAD

**Issue by dbmajor** [RMerl/asuswrt-merlin.ng#570]
![Adaptive QoS Page Seems Buggy](https://user-images.githubusercontent.com/39684659/88510856-f75bf900-d037-11ea-96bb-12fd975a66a4.png)

Browser cache has been cleared since upgrade, but still no good.

Cheers

**Comment by dbmajor** [comment]
![RT-AC86U - Adaptive QoS Page Seems Buggy](https://user-images.githubusercontent.com/39684659/88511096-5a4d9000-d038-11ea-83dc-92f2f4a322a0.png)

This is the one from the RT-AC86U

**Comment by RMerl** [comment]
Works for me, check your browser.
