### ISSUE TITLE
Can the time / blocking max limit be increased

### ISSUE THREAD

**Issue by NathanaelA** [RMerl/asuswrt-merlin.ng#572]
Looking through the code it appears `MAX_PCONTROL_ENTRY` is the primary value that limits the number of devices in the list (their are a couple other hard codes 16's in the index.asp and parentControl files).    However, can you tell me if you are aware of any issues if I create a PR to double this number and fix those hard coded values...

**Comment by RMerl** [comment]
That define is only used for snmp.  There are most likely various limits, like the size of the nvram itself, which cannot be increased on HND platform.

**Comment by JackMerlin** [comment]
If RMerlin's reply answers your question, you can try to close this issue.
