### ISSUE TITLE
look for b43 driver support for openwrt

### ISSUE THREAD

**Issue by predators46** [RMerl/asuswrt-merlin.ng#574]
why don't you share open source drivers with OpenWRT. if you provide openwrt driver access it is likely that your router sales will increase. and now OpenWrt already uses the 5.xx.x kernel version

**Comment by RMerl** [comment]
I don't sell routers...

The wireless code is closed source, including all the code that loads and configures wifi.

Beside, OpenWRT has no fully functional driver for recent Broadcom chips.
