### ISSUE TITLE
IPv6 CleanBrowsing 1/2 (family) DoT preset IP not recognized as valid

### ISSUE THREAD

**Issue by robertdonat** [RMerl/asuswrt-merlin.ng#580]
After choosing the preset IPv6 addresses of CleanBrowsing 1 and 2 (family) and clicking add, error message of "2a0d:2a00:X:: is not a valid IP address!" appears. I confirmed these are the correct [IPv6 addresses of CleanBrowsing Family](https://cleanbrowsing.org/guides/dnsovertls). 

- IPv6 CleanBrowsing 1: 2a0d:2a00:1:: - family-filter-dns.cleanbrowsing.org
- IPv6 CleanBrowsing 2: 2a0d:2a00:2:: - family-filter-dns.cleanbrowsing.org

The other preset IPv6 address for CleanBrowsing are accepted. Using 384.19 firmware on RT-AC68U.

![CBfamily1IPv6](https://user-images.githubusercontent.com/18128319/90327899-cabb4300-df4c-11ea-974f-f23432773f3b.png)
![CBfamily2IPv6](https://user-images.githubusercontent.com/18128319/90327901-cbec7000-df4c-11ea-9f37-ab0f21ca591d.png)

**Comment by paldier** [comment]
>     2a0d:2a00:1::
It is not a valid IP address, what is your question, firmware bug? NO!

**Comment by robertdonat** [comment]
> It is not a valid IP address, what is your question, firmware bug? NO!

2a0d:2a00:1:: is a valid IPv6 address. Check your work before commenting, please.

![2a0d:2a00:1::](https://user-images.githubusercontent.com/18128319/90338166-7049d300-df9c-11ea-862c-685624193134.png)

**Comment by hurda** [comment]
Isn't there a bug in the IPv6-validator?
https://github.com/RMerl/asuswrt-merlin.ng/blob/5f61bfdfd4305288a6c2258a8d34d41be8624f25/release/src/router/www/validator.js#L846
It splits the address into a part left of :: and a part right of :: .
Then it checks the strings separated by : in these parts if they are only made of at least 1 or at most 4 hexadecimal characters with the isHex-function.
But if there is no part right of :: , the check fails, although such an address is valid.
Am I reading this correctly?
