### ISSUE TITLE
R7000 meilin 384.19 set Disable LEDs ,after reboot,the LEDs auto change to enable!

### ISSUE THREAD

**Issue by abel-d** [RMerl/asuswrt-merlin.ng#581]
![image](https://user-images.githubusercontent.com/14855855/90336688-09660180-e010-11ea-9336-2acfa6832061.png)

**Comment by npmstart-pray** [comment]
I believe you’re looking for support for firmware you may be running on your router “illegally”. Pretty sure RMerlin doesn’t list the r7000 as a supported model he develops for.  So, just in case he closes this topic/issue, that could be why and you’re likely on your own in finding a solution. You could write your own fork based on his work, and fix the issue there. Good luck

**Comment by RMerl** [comment]
You are running an illegal fork of my firmware.
