### ISSUE TITLE
AiCloud does not work with Namecheap DDNS

### ISSUE THREAD

**Issue by mohd-akram** [RMerl/asuswrt-merlin.ng#582]
On the DDNS page, I'm using Namecheap with the following:
```
  Host Name: my.router
Domain Name: example.com
```
On the Network Map page, it correctly shows `DDNS: my.router.example.com`. However, on the AiCloud page it says: `Enter AiCloud 2.0 https://my.router`. I also can't access AiCloud in the first place, I'm not sure if it's because of this or something else.

**Comment by mohd-akram** [comment]
This does in fact seem to be the problem with not being able to access AiCloud too. Faking the hostname with `curl --resolve my.router:my.router.example.com https://my.router` succeeds.

**Comment by gitstua** [comment]
Did you check the port - I think you need to specify in this format: https:example.com:8443

**Comment by JackMerlin** [comment]
I guess it is a port problem, HTTPS uses the default port 8443, AiCloud uses the default port 443, BTW, AiCloud issues please do not feedback here, because it is a closed source component of Asus, RMerlin can't do anything.

**Comment by mohd-akram** [comment]
It's not a AiCloud/port problem or else the curl command I used wouldn't work. It's a problem with the Namecheap DDNS.

**Comment by mohd-akram** [comment]
After updating to 386.1, this now works.
