### ISSUE TITLE
Issue with update on RT-AX88U

### ISSUE THREAD

**Issue by H0W1K2** [RMerl/asuswrt-merlin.ng#589]
Hello, I am using RT-AX88U and currently on 384.18, I have check for update enable, for some reason I never get notification on router GUI that update is available. If I initiate a manual check for update, then it does notify me that update is available for router.  Prior to upgrading to 384.18, same issue existed as well, would never get notification. If I used app and it check for update, then I also get notification in app and as well main router home page. Only automatic periodic schedule check seems to be not working.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
