### ISSUE TITLE
MQTT Broker

### ISSUE THREAD

**Issue by Solraven** [RMerl/asuswrt-merlin.ng#591]
i have been trying to set up a MQTT Broker on my ac68r running Merlin. all the guides i find are for openwrt. i cant seem to get it working. is entware installing it in the wrong place? cant find the executable.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
