### ISSUE TITLE
WebGui unresponsive. Listing contents of jffs partition hangs. 384.18 on Asus AC5300

### ISSUE THREAD

**Issue by jaas666** [RMerl/asuswrt-merlin.ng#592]
I noticed my web interface not loading. Tried loggin via SSH and was able to.
Upon further inspection I noticed I can cd to directory /jffs but if I try to list the directory contents the terminal window just hangs there.

At first I tought this was a fluke but I've seen it happen two times already. Only way I've found to make everything work again is to reboot the router.

Running scripts when it happened: 
- FlexQOS (installed from amtm)
- spdMerlin (installed from amtm)
    -Entware (so spdMerlin would install)
    -2GB Swap file (so spdMerlin would install)
- AutoBW (automatic setting QOS down/up speed based on spdMerlin results) from https://forums.smallnetbuilder.com/threads/autobw-automatically-set-qos-bandwidth-using-spdmerlin.63067/

I formatted the jffs partition and reinstalled FlexQOS only to see if it happens again.

Any idea on where to start looking to troubleshoot this?

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
