### ISSUE TITLE
Set reboot time for mesh nodes

### ISSUE THREAD

**Issue by joalmjoalm** [RMerl/asuswrt-merlin.ng#593]
Hi
Is there anyway by a script in JFFS reboot mesh nodes. I have set reboot of the main router in the settings but cant do it for each mesh node. I would prefer to reboot them in a certain order to get them connected via uplinks that I can determine via boot order.
If mesh nodes are close to eachother uplinks can varie. 
Best would be to have a reboot setting for each mesh node in the main router Gui. I can obviously manually reboot mesh nodes via the Asus app but I look for automation.
/J

**Comment by RMerl** [comment]
Anything related to AiMesh is closed source and outside of my control.
