### ISSUE TITLE
Feature Request - Selective Interface Port Forwarding

### ISSUE THREAD

**Issue by Salvora** [RMerl/asuswrt-merlin.ng#596]
First of all, I gotta say, this custom firmware is super good and ASUS needs to hire and support you to keep this going.
Anyway
By default, "port forwarding" feature forwards ports from WAN to LAN. This was always the case. However, now that VPNs and CGNATs are more widespread, the use of port forwarding is becoming insufficient.

If you can add a dropdown menu to "port forwarding GUI" section to select the interface (WAN,TUN11, TUN12 etc..), it would be super awesome. You can select TUN to LAN instead of default WAN to LAN depending on your needs.

Currently, this can be only achieved by iptables scripts running from JFFS; which is inelegant and confusing.

**Comment by RMerl** [comment]
Too niche of a feature.  And wouldn't work for most users, because port forwarding a VPN interface won't work unless your remote end actually does forward traffic to you.
