### ISSUE TITLE
[Question] Dual WAN, use specific provider for specific lan client

### ISSUE THREAD

**Issue by lorenc-tomasz** [RMerl/asuswrt-merlin.ng#599]
Hi,
I want to use second provider and enable dual WAN. Is there any option to e.g. split providers? So Provider1 on WAN 1 will be used by LAN1, LAN2, and Provider2 on WAN 2 will be used by LAN3 and LAN4 users.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.

**Comment by lorenc-tomasz** [comment]
OK. Thanks. Maybe an option on webui?
