### ISSUE TITLE
Disable LEDs resets after reboot 384.19

### ISSUE THREAD

**Issue by rgozim** [RMerl/asuswrt-merlin.ng#605]
Under Administartion -> System -> **Disable LEDs** setting to _yes_ resets back to _no_ after reboot.

Tested on 384.19 and 384.18 on the Netgear R7000

**Comment by paldier** [comment]
https://github.com/RMerl/asuswrt-merlin.ng/wiki/Supported-Devices

**Comment by RMerl** [comment]
You are running an illegal firmware from someone else than me.  You're on your own.
