### ISSUE TITLE
[RT-AX88U] NsLookup tool is not using DNS-over-TLS

### ISSUE THREAD

**Issue by lucadesogus** [RMerl/asuswrt-merlin.ng#607]
In case DoT is configured I expect that is used also from NsLookup tool.

**Comment by crkinard** [comment]
Isn’t there a check box or something that tells router based commands to use the user specified DNS servers instead of the ISP ones (which it does by default)?

**Comment by lucadesogus** [comment]
Yes, found.
Tools -> Other Settings -> Wan: Use local caching DNS server as system resolver -> Change to Yes
