### ISSUE TITLE
382.1_2 SSID hidden global also for guest wlan

### ISSUE THREAD

**Issue by cybknight** [RMerl/asuswrt-merlin.ng#61]
Thanks for a great firmware

It seems there is a functionality change in new firmware when moving from 380 to 382 release?
(I should perhaps have done factory default, but I am lazy...)

With old firmware, I had default WLAN setting set for SSID hidden, but guest networks were then still shown, and I liked it like that.
In new 382 firmware on my RT-AC88U, the guest networks seems to inherit the SSID hidden flag from the main WLAN settings. So after updating, a lot of my wifi devices dropped out, because they don't really like hidden SSID, and I now have to unhide my main WLAN networks, to get everything working again.

Any chance of restoring this functionality in later releases?

Sincerely Martin

**Comment by RMerl** [comment]
Anything tied to wireless is outside of my control.
