### ISSUE TITLE
Wireguard in userspace and TUN device

### ISSUE THREAD

**Issue by PutinVladimir** [RMerl/asuswrt-merlin.ng#613]
Wireguard-go is userspace
https://github.com/WireGuard/wireguard-go

It easly compile but can't create tun device and I also can't create it by hands, but builting openvpn creates tun device so it should be possible.
So I guess if we can create tun device we can run wireguard.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
