### ISSUE TITLE
RT-AX88U doen't work dual Wan with the last 384.19 version (14-Aug-2020) 

### ISSUE THREAD

**Issue by kitopopo** [RMerl/asuswrt-merlin.ng#615]
Dear friends,

I have updated to 384.19 last version for the rt-ax88u, but doen't work dual wan correctly. The primary wan appears waiting and always start with the secondary lan (modem USB) and the internet red led is on. I have formated the jffs partition but I get the same results.

I had to downgrade to version 384.18 I had to downgrade to version 384.18 and now works correctly again. 
Repeating the update to 384.19 again, the same error occurs again

Any solution?

Thanks in advanced.

Best regards

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
