### ISSUE TITLE
Will this be supported for the new ASUS ZenWifi routers?

### ISSUE THREAD

**Issue by ksylvan** [RMerl/asuswrt-merlin.ng#618]
Specifically:

- ZenWiFi AC (CT8)
- ZenWiFi AX (XT8)

Looking to bypass my uVerse BWG210-700 router setup with the new two node mesh setup I just bought.

Thanks!

**Comment by RMerl** [comment]
I can't speculate about future model support, sorry.

**Comment by paiou** [comment]
Hello.
I would be happy to contribute a merge request to support ZenWifi AX, I'm an experienced developer but never worked on driver or firmware code. Do you think this is achievable with reasonable effort?
Thanks!

**Comment by bohtho** [comment]
Are you any closer to XT8 support? It’s a popular mesh system and I would love to get the same additional features on it. Is the missing support due to less “hackablility” and more “consumer black box”?

**Comment by jmstacey** [comment]
Poking around this looks technically feasible as the XT8 has the same CPU and Radios 1+2 as the RT-AX56U, and radio 3 as GT-AX11000. Both of those routers have Merlin support so driver blobs are there. Don't know if there's any secret sauce for the Zen's compared to standalone router.
