### ISSUE TITLE
Remove ability to edit Wiki pages for regular users

### ISSUE THREAD

**Issue by kolobock** [RMerl/asuswrt-merlin.ng#623]
First of all, I would like to sorry about it. I have modified an empty Wiki page.
https://github.com/RMerl/asuswrt-merlin.ng/wiki/_compare/12272b9929ec8846128653091fb947cdcdb2a2d0

I could neither rollback this action nor change permissions for Wiki pages so
asking you to deny write access for regular users like I am.
<img width="775" alt="Screen Shot 2020-10-14 at 15 36 16" src="https://user-images.githubusercontent.com/871452/95989848-77258280-0e33-11eb-8145-6609e2ade5ba.png">

Thank you for understanding.

**Comment by RMerl** [comment]
The wiki is largely maintained by the community and not by me, therefore it's essential to be left editable by anyone with a valid Github account.  That`s what makes it a wiki and not just a static documentation page.

I will rollback the change, no worry.
