### ISSUE TITLE
Please add support for ASUS RT-AX92U 

### ISSUE THREAD

**Issue by nikallass** [RMerl/asuswrt-merlin.ng#624]
Please could you test/release your firmware on new ASUS RT-AX92U. May be modifications will be not much RT-AX88U. Thanks!

**Comment by jumpsmm7** [comment]
Also, please consider adding support for asus RT-AX86U

**Comment by binswm** [comment]
I also own ax86u, so I also hope to add ax86u support

**Comment by bfara83** [comment]
I also own an AX82U, very interested myself to adding support for this model.

**Comment by binswm** [comment]
I have temporarily bought an ac1900p to install merlin first, because I want to install astrill with merlin.

Binswm

**Comment by qcybb** [comment]
Please add support for RT-AX86U

**Comment by Ruxta** [comment]
+1 on the AX82U, thanks!

**Comment by RMerl** [comment]
Don't use the issue tracker for model support requests.  Model support is determined on a per model basis, regardless of requests, based on numerous factors, some of which technical.
