### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by vladut123** [RMerl/asuswrt-merlin.ng#627]
I can not setup wsl2 to build asuswrt-merlin.ng firmware please tell me the steps required

**Comment by dave14305** [comment]
These were my exact steps from my bash history in WSL2 (edited to remove extra commands and mistakes).
`sudo dpkg --add-architecture i386
sudo dpkg-reconfigure dash
sudo apt-get update
sudo apt-get install libtool-bin cmake libproxy-dev uuid-dev liblzo2-dev autoconf automake bash bison bzip2 diffutils file flex m4 g++ gawk groff-base libncurses5-dev libtool libslang2 make patch perl pkg-config shtool subversion tar texinfo zlib1g zlib1g-dev git gettext libexpat1-dev libssl-dev cvs gperf unzip python libxml-parser-perl gcc-multilib gconf-editor libxml2-dev g++-multilib gitk libncurses5 mtd-utils libncurses5-dev libvorbis-dev git autopoint autogen sed build-essential intltool libglib2.0-dev xutils-dev lib32z1-dev lib32stdc++6 xsltproc gtk-doc-tools libelf1:i386
sudo apt install automake-1.15
cd ~
git clone https://github.com/RMerl/am-toolchains
git clone https://github.com/RMerl/asuswrt-merlin.ng &
mkdir amng-build
rsync -a --progress --del asuswrt-merlin.ng/ amng-build
sudo ln -s ~/am-toolchains/brcm-arm-hnd /opt/toolchains
echo "export LD_LIBRARY_PATH=$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/lib" >> ~/.profile
echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ~/.profile
echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
echo "export LD_LIBRARY_PATH=$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/lib" >> ~/.profile
echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ~/.profile
echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ~/.profile
sudo ln -s ~/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3 /opt/brcm-arm
ln -s ~/am-toolchains/brcm-arm-sdk  ~/asuswrt-merlin.ng/release/src-rt-6.x.4708/toolchains
echo "PATH=\$PATH:/opt/brcm-arm/bin" >> ~/.profile
exit
cd ~
cd asuswrt-merlin.ng/
git checkout mainline.384
cd release/src-rt-6.x.4708/
make clean
make rt-ac68u
cd image/
md5sum RT-AC68U_384.19_0.trx`

**Comment by dave14305** [comment]
I also struggled early on due to a WSL2 bug that breaks the /etc/resolv.conf for the Ubuntu environment.
See: https://github.com/microsoft/WSL/issues/4285

**Comment by vladut123** [comment]
I have a question where the/etc/wsl.conf is located?

**Comment by dave14305** [comment]
> 
> 
> I have a question where the/etc/wsl.conf is located?

It may not exist and you have to create it the first time with `sudo vi /etc/wsl.conf` or `sudo nano /etc/wsl.conf`

**Comment by vladut123** [comment]
It needs to be inside c drive windows system32 folder right?

**Comment by dave14305** [comment]
> 
> 
> It needs to be inside c drive windows system32 folder right?

No, all this happens within the Ubuntu image once you install Ubuntu through the Microsoft Store.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
