### ISSUE TITLE
RT-AX92U support ?

### ISSUE THREAD

**Issue by mcarbonneaux** [RMerl/asuswrt-merlin.ng#628]
what is the status of RT-AX92U support ?

the source are [here](https://dlcdnets.asus.com/pub/ASUS/wireless/RT-AX92U/GPL_RT_AX92U_30043847977.zip).
seem to be an asuswrt flavor....

how to start testing on it's building ?

**Comment by mcarbonneaux** [comment]
i've seen the other issue on this https://github.com/RMerl/asuswrt-merlin.ng/issues/624.

**Comment by RMerl** [comment]
There is no status or anything to test, because that model is not supported, and nothing has been announced yet concerning it.

**Comment by mcarbonneaux** [comment]
why is not supported ? there specifique problem ?

**Comment by RMerl** [comment]
https://www.snbforums.com/threads/faq-read-me-first-before-posting-a-question.47153/post-609193
