### ISSUE TITLE
[AC86U] AiCloud - Sync Server is not supported on AP mode

### ISSUE THREAD

**Issue by Aqours** [RMerl/asuswrt-merlin.ng#629]
Router: RT-AC86U
Operation Mode: AP mode
Firmware Version: 384.19

Reproduce:
1. Set Router to AP mode
2. Select AiCloud 2.0 tab
3. Select Sync Server tab
4. Alert **ERROR**: This function is not supported on this system

Screenshot:
![2DCA818B-13FA-4946-AB8D-C89291075D65_1_201_a](https://user-images.githubusercontent.com/8586286/97853626-5023e780-1d33-11eb-8e43-af4e766526a9.jpeg)

**Comment by RMerl** [comment]
Everything related to AiCloud is closed source and outside of my control.

**Comment by Aqours** [comment]
Thanks.
Should we remove AiCloud tab if it is closed source and outside of your control?

**Comment by RMerl** [comment]
I'd rather not mess with it, since Asus might have a reason for exposing the tab in non-router mode.
