### ISSUE TITLE
Null Outbound Trend Micro Requests/Packets

### ISSUE THREAD

**Issue by TensorTom** [RMerl/asuswrt-merlin.ng#632]
Many useful features require the user to accept Trend Micro's [EULA](https://www.asus.com/Microsite/networks/Trend_Micro_EULA/), [Privacy Policy](https://www.trendmicro.com/en_us/about/legal/privacy.html), and [Data Collection Notice](https://helpcenter.trendmicro.com/en-us/article/TMKA-20275). As is, I would never use these. Not because I don't want to use them but because I wouldn't want telemetry and who knows what else sent to Trend Micro.

Trend Micro's practices and motivations [are less than transparent](https://malwaretips.com/threads/why-does-trend-micro-send-telemetry-to-data-mining-firms.71932/) and it would be super-useful to be able to enable an option that will still allow downloading generic rule files and whatnot from Trend Micro while at the same time blocking any egress traffic to Trend Micro's servers.

If this is somehow incompatible with this project's relationship to Asus (I'm unsure of what that relationship is), we could settle for an ip/host block-list feature where ingress/egress/both can be specified per host.

**Comment by TensorTom** [comment]
Shouldn't this be possible with user scripts/entware? I know it could be done simply by some hosts entries but I prefer something a bit less ham-handed.

**Comment by RMerl** [comment]
You are asking me to make my firmware capable of breaching the EULA.  That`s a definiitve no on that one, even assuming it were technically possible (which it isn't).
