### ISSUE TITLE
How to identify devices running ASUSWRT-Merlin

### ISSUE THREAD

**Issue by 1951FDG** [RMerl/asuswrt-merlin.ng#64]
Hello,

Until now, I was using `uname -o`, but the output is no longer the same! It now returns `GNU/Linux` instead of `ASUSWRT-Merlin` after I upgraded to Entware-ng-3x. So it appears this is not hard coded? Or is has it been overridden somehow by Entware-ng-3x?

I've opened this [issue](https://github.com/Entware-for-kernel-3x/Entware-ng-3x/issues/57)

Though the question now remains, how can I identify that the Linux Platform is `ASUSWRT-Merlin` Linux and not simply `Linux`. I require this because I'm working on a cross platform python script which also targets other `Linux` devices that run standard distributions. I need to be able to distinguish between them by OS name.

I checked `cat /tmp/etc/image_version` but I need something that identifies all devices which are running ASUSWRT-Merlin.

On the side:

When I run dmesg, I see this error, do I have to worry about it?
 [ERROR pktrunner] runnerUcast_inet6addr_event,202: Could not rdpa_ucast_ipv6_host_address_table_find

Also regarding memory usage, by default the RT-AC86U running on ASUSWRT-Merlin uses about 300 MB out of 512 MB, is this normal, does it require that much memory, is it possible to trim this down by turning off particular services?

I also noticed that the Enable UPnP Media Server was on by default why not turn it off by default?
Hint: I had some cpu usage issues when this was on, after I had installed Entware. I've turned it off for now. I believe it was due to indexing.

Thanks!

**Comment by RMerl** [comment]
The uname output is hardcoded into Busybox at compile time, this is why using a custom busybox build won`t return the same uname.  That`s another reason why you should not replace the built-in busybox with your own.  Some of the Busybox applets have been customized for the firmware's needs, overriding Busybox might break other things as well.

There's currently no other official way to determine the installed firmware, short of checking the actual version numbers stored in nvram.
