### ISSUE TITLE
VPN into local network but can't use router webui?

### ISSUE THREAD

**Issue by Eewec** [RMerl/asuswrt-merlin.ng#641]
I'm not sure about this. I have "Enable Web Access from WAN" set to No as I don't want direct access from outside the network. I have my VPN all setup, I can look at various things on my local network just fine (like my 3d printers local web page) and other such items. Is there a reason I'm unaware of why my routers webui is off limits when using a VPN? Or is it having a fit because I'm testing it with a Guest network set to not allow local network access then VPN'ing back in?

I'm using 384.19 on an Asus RT-AC5300 and I'm just not seeing which setting I'm missing....

Also SSH'ing into my router even from the local network seems to make it have a fit and crash. What letters (if any) are a no-no for SSH in the password? It also really doesn't like `ssh <user>@<ip>:<port>` I have to use `ssh <user>@<ip> -p <port>` and even then it doesn't always like taking the password, though this may be windows being annoying rather than the router.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
