### ISSUE TITLE
Data integrity error caused by the deletion of the check of cpu_has_dc_aliases

### ISSUE THREAD

**Issue by Lirong-source** [RMerl/asuswrt-merlin.ng#642]
Hi, in [linux-2.6.36](https://github.com/RMerl/asuswrt-merlin.ng/tree/master/release/src-rt-7.14.114.x/src/linux/linux-2.6.36) arch/mips/mm/init.c, line 271, function copy_from_user_page
, the kernel of assert-merlin deleted the check of cpu_has_dc_aliases (definition: #define cpu_has_dc_aliases	(cpu_data[0].dcache.flags & MIPS_CACHE_ALIASES)), which is used to determine whether OS allows the alias of CPU cache. If yes, multiple virtual addresses can map to a single physical address, and using virtual addresses as tags may cause multiple copies of one piece of data in the cache. In this situation, if one of the copies is modified and the other copies are not updated simultaneously, the data will lose its integrity, which will lead to program errors. Therefore, this security check can ensure the data integrity of a program and should not be deleted.

**Comment by RMerl** [comment]
Irrelevant, since all router models are ARM-based, not MIPS.
