### ISSUE TITLE
DDNS问题

### ISSUE THREAD

**Issue by lf9421** [RMerl/asuswrt-merlin.ng#643]
DDNS使用自定义的，会显示For the Custom DDNS you must manually create a ddns-start script that handles your custom notification.不知道什么原因，有没有什么解决方案啊

**Comment by xfgavin** [comment]
自己写一个ddns脚本就好了

**Comment by JackMerlin** [comment]
If you have a **bug feedback** about DDNS, please post it here in English. If it is other questions, please do not ask here.

如果您有关于 DDNS 的**错误反馈**，请在此处以英语发布。 如果是其他问题，请不要在这里提问。

**Comment by lf9421** [comment]
> 自己写一个ddns脚本就好了
嗯嗯，可就是不会写啊，百度出来的脚本都不行，提供的模版也没有dnspod

**Comment by lf9421** [comment]
> If you have a **bug feedback** about DDNS, please post it here in English. If it is other questions, please do not ask here.
> 
> 如果您有关于 DDNS 的**错误反馈**，请在此处以英语发布。 如果是其他问题，请不要在这里提问。

sorry
