### ISSUE TITLE
Wifi schedule, clients unable to connect

### ISSUE THREAD

**Issue by florenzx** [RMerl/asuswrt-merlin.ng#644]
Wifi (2.4 + 5 Ghz) has been scheduled via UI to be offline from 1am-7am. 
Wifi disappeared at 1am and appeared at 7am. However clients (mobiles, notebooks) were unable to connect to the wifi anymore.
Reboot was required to fix the problem. This happened regularly after each offline schedule cycle.

Router RT-AX56U, Asuswrt 384.18

**Comment by RMerl** [comment]
Anything related to wifi is closed source and outside of my control.
