### ISSUE TITLE
Data use without free

### ISSUE THREAD

**Issue by Lirong-source** [RMerl/asuswrt-merlin.ng#645]
By the way, in [linux-2.6.36](https://github.com/RMerl/asuswrt-merlin.ng/tree/master/release/src-rt-7.14.114.x/src/linux/linux-2.6.36) net/netfilter/nf_queue.c, line 192, function  __nf_queue, the kernel of assert-merlin deleted the release operation that free **struct sk_buff **i.e. skb. Function *kfree_skb* will drop a reference to the buffer and free it if the usage count has hit zero. Therefore, due to the deletion of *kfree_skb(skb)* , the variable *skb* will never be freed.

**Comment by hurda** [comment]
https://github.com/torvalds/linux/commit/06cdb6349c1f3fd439398dbc04ce4c696f0a41ab#diff-a17a09ac5aece84d37f8e606b0db237ba4fea2d1c93e9171f8dab4c27225aa42
`Move free responsibility from nf_queue to caller.`
