### ISSUE TITLE
VPN down traffic appearing as up

### ISSUE THREAD

**Issue by Weggy** [RMerl/asuswrt-merlin.ng#648]
With a VPN Client setup and a client set to utilise the VPN via "Rules for routing client traffic through the tunnel". The traffic on "QoS - WAN/LAN Bandwidth Monitor" appears to be displayed as upload instead of download.

Device: RT-AC5300

**Comment by RMerl** [comment]
Known issue.  Out of my control since the Trend Micro engine is closed source.
