### ISSUE TITLE
RT-AX55

### ISSUE THREAD

**Issue by mkieloch-352** [RMerl/asuswrt-merlin.ng#649]
Any plans to support the RT-AX55 or are there any firmware versions compatible with this model?

**Comment by byyxx128** [comment]
+1
Waiting for response from official maintainers...
https://www.asus.com/Networking-IoT-Servers/Whole-Home-Mesh-WiFi-System/All-series/RT-AX55/techspec/

P.S. It is called "RT-AX56U_V2" in several regions, but different from the real [RT-AX56U](https://www.asus.com/Networking-IoT-Servers/WiFi-Routers/All-series/RT-AX56U/techspec/).

**Comment by RMerl** [comment]
I cannot speculate about future model support.  Expect models to not be supported unless announced otherwise.
