### ISSUE TITLE
VPN Throttling

### ISSUE THREAD

**Issue by Weggy** [RMerl/asuswrt-merlin.ng#650]
Issue:
My internet download speed appears to be throttled somehow (uncertain how) when utilising a VPN via my router. My NAS is setup to ensure all traffic goes via my VPN using Open VPN and strict policy rules. However, when connection via the VPN my speeds are around 50% of what they should be and there is no clear sign as to why this is (at least I've run out of ideas). I'm 100% sure (I think :) ) it's not my service provider (PIA), I double checked this theory by trying another provider (privado) and the issue still persist. I can only assume the issue is my end.

Setup:
Router: Asus RT-AC5300 (Firmware Version:384.18)
Internet Down\Up Speed: 114Mbps\5Mbps
NAS: Synology DS1019+
VPN Service: Private Internet Access

Does anyone know if this is a known issue with the firmware I'm using or if I might have made a mistake in my setup which is why I'd be getting an issue like this.

Any help would be greatly appreciated as I'm completely out of ideas (googling) to fix this issue.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
