### ISSUE TITLE
Request update 5 GHz channels

### ISSUE THREAD

**Issue by NakornC** [RMerl/asuswrt-merlin.ng#652]
Please update the 5 GHz channels if you are available, thank you.
CN (149, 153, 157, 161) -> (36, 40, 44, 48, 64, 149, 153, 157, 161, 165)
TW (52, 56, 60, 64, 149, 153, 157, 161) -> (52, 56, 60, 64, 100, 104, 108, 112, 116, 132, 136, 140, 149, 153, 157, 161, 165)
HK (36, 40, 44, 48, 149, 153, 157, 161) -> (36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 132, 136, 140, 149, 153, 157, 161, 165)

https://www.lairdconnect.com/support/faqs/what-channels-are-supported-both-24-ghz-and-5ghz-band-most-countries

**Comment by paldier** [comment]
You should do that in wifi driver and it's closed code. 
for example:[https://github.com/MerlinRdev/ac85p-merlin/commit/7eb5d7efb1d735cdbd991a310fef4ea9d85634f0/release/src-ra-5010/linux/linux-3.10.14.x/drivers/net/wireless/ralink/mt7615/embedded/common/rt_channel.c](https://github.com/MerlinRdev/ac85p-merlin/commit/7eb5d7efb1d735cdbd991a310fef4ea9d85634f0/release/src-ra-5010/linux/linux-3.10.14.x/drivers/net/wireless/ralink/mt7615/embedded/common/rt_channel.c)
brcm:wlc_clm_data.c

**Comment by RMerl** [comment]
Everything related to wifi is closed source and outside of my control.
