### ISSUE TITLE
Strange hostname showing up in DHCP client list in Network Map

### ISSUE THREAD

**Issue by jamenlang** [RMerl/asuswrt-merlin.ng#662]
I'm not sure what's causing this, but I believe it's been an issue with my router since the start. I've been on Merlin since day 1 so it Might not even be a Merlin issue, but my problem is that all of the mac addresses show up in the list, some of the clients show up with a "West Mikrotik", I can change the name and it reverts back, I saw it happen with my own eyes earlier today.

Does anyone have experience with invasive hostnames?

![image](https://user-images.githubusercontent.com/6394127/102736581-84af2b00-4302-11eb-9d6b-395b4e12e776.png)

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
