### ISSUE TITLE
Firmware for ASUS DSL-AC68VG

### ISSUE THREAD

**Issue by Cure1111** [RMerl/asuswrt-merlin.ng#669]
Hi 

just wanted to ask if this firmware is also available for the ASUS DSL-AC68VG, or is planned for it

**Comment by JackMerlin** [comment]
Regarding DSL-AC68, I suggest you ask the fork author, you can find him here:  https://www.snbforums.com/threads/dsl-ac68u-asuswrt-merlin-builds-for-dsl-routers.55985/

**Comment by RMerl** [comment]
I don't support any non-router model.
