### ISSUE TITLE
Prevent WiFi disconnection when enabling/disabling guest network

### ISSUE THREAD

**Issue by gcacace** [RMerl/asuswrt-merlin.ng#670]
I've noticed that every time I enable/disable the guest network, all the WiFi devices of my home get disconnected, even if they're connected to the standard WiFi networks (not the guest ones). This is a peculiarity of the original firmware. I was wondering if there is any way in Merlin to prevent the reset of all WiFi network interfaces when enabling or disabling guest networks.

**Comment by JackMerlin** [comment]
I think this problem involves wireless drivers. Since the drivers are closed source, I think Merlin is probably powerless.

**Comment by RMerl** [comment]
Nothing I can do about it, this is entirely under Asus's control.
