### ISSUE TITLE
In repeater mode, NTP function does not seem to work

### ISSUE THREAD

**Issue by testn** [RMerl/asuswrt-merlin.ng#674]
In repeater mode, NTP function does not seem to work. The time 

**Model**
RT-AC68U

**Firmware version**
384.19

**Client information**
Chrome 87

**To Reproduce**
Check the time on the router. (https://<ip>:8443/Main_LogStatus_Content.asp) 

**Expected behavior**
The time should be the current time

**Actual results**

It will show the time in 2018

System Time | Tue May 8, 2018
Uptime | 2 days 19 hour(s) 1 minute(s) 3 seconds

**Will this error be reproduced on the official firmware?**
I didn't test

**Screenshots**
![image](https://user-images.githubusercontent.com/445123/103604474-c7e4dd00-4f43-11eb-9792-c690ea2b6204.png)

**Additional context**

**Comment by JackMerlin** [comment]
Have you ever tried to manually click the NTP LINK on the admin page?

**Comment by testn** [comment]
Already tried and enabled the network monitoring but it still does not work.

**Comment by RMerl** [comment]
Tested, working in 386.2 Beta 1.

**Comment by testn** [comment]
Thanks @RMerl  I will check it out.
