### ISSUE TITLE
Additional cachable files

### ISSUE THREAD

**Issue by trajano** [RMerl/asuswrt-merlin.ng#681]
Going through the network logs here's some other candidates I found for caching same as https://github.com/RMerl/asuswrt-merlin.ng/issues/657

* https://github.com/RMerl/asuswrt-merlin.ng/blob/4da3da3142729bb7a197b1248960864cca4c3db7/release/src/router/www/js/sorterApi.js

* https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src/router/www/js/support_site.js

* Everything in https://github.com/RMerl/asuswrt-merlin.ng/tree/master/release/src/router/www/fonts since they're fonts and these are big
 
* _Most likely_ everything in https://github.com/RMerl/asuswrt-merlin.ng/tree/master/release/src/router/www/images since they're images
  
**Model**
RT-AC68U

**Firmware version**
386.1 Beta 5

**Comment by RMerl** [comment]
I currently have no plan to add anything more to the cache.  I don't want to overengineer something that is transferred over a LAN anyway, and which will cause issues whenever the upstream version changes between firmware releases.

Images are already all cached.
