### ISSUE TITLE
[Question][Security] Any chance for security update for AC87? 

### ISSUE THREAD

**Issue by lorenc-tomasz** [RMerl/asuswrt-merlin.ng#685]
Hi,
do you consider to do some security updates (e.g. dnsmasq) for e.g. AC87 model?

**Comment by lorenc-tomasz** [comment]
There is even beta available: 9.0.0.4.382.52503 https://www.asus.com/Networking-IoT-Servers/WiFi-Routers/ASUS-WiFi-Routers/RTAC87U/HelpDesk_BIOS/

**Comment by RMerl** [comment]
No, this model is no longer being supported.
