### ISSUE TITLE
RT-AC5300 upgrade from 386.1_beta5 to 386.1 - Invalid Firmware

### ISSUE THREAD

**Issue by SPouliot1** [RMerl/asuswrt-merlin.ng#686]
When i try to update my RT-AC5300 with RT-AC5300_386.1_0.trx, i receive this error:

Invalid Firmware Upload
To comply with regulatory amendments, we have modified our certification rule to ensure better firmware quality. This version is not compatible with all previously released ASUS firmware and uncertified third party firmware. Please check our official websites for the certified firmware.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
