### ISSUE TITLE
386.1 QoS Speed Test tab tops out at 500 Mbps on a 900 Mbps PPPoE Internet connection

### ISSUE THREAD

**Issue by dbmajor** [RMerl/asuswrt-merlin.ng#689]
**Describe the bug**
RT-AX88U Speedtest under QoS tab only reports 500 Mbps download speed, when the connection speed is 900 Mbps and tests at that on a laptop connected via Ethernet.

**Model**
RT-AX88U

**Firmware version**
386.1_0

**Client information**
The router itself

**To Reproduce**
Connect RT-AX88U to a PPPoE internet connection and attempt a speed test under the QoS section of the router.

**Expected behavior**
A speed test with a download of 900-960 Mbps download and 500 Mbps upload

**Actual results**
A speed test with a download of 500 Mbps download and 500 Mbps upload

**Will this error be reproduced on the official firmware?**
Have only tested on Merlin Firmware

**Screenshots**
See attached

**Additional context**
I'm running Mac OS X Catalina, but can't see how that would affect results, as the speedtest website reports ~930 Mbps

**Comment by crkinard** [comment]
Hardware limitations of the router. Was listed in the release notes.

**Comment by RMerl** [comment]
That would be a hardware limitation.
