### ISSUE TITLE
busybox: update 1.25.1 for HND platform

### ISSUE THREAD

**Issue by blackfuel** [RMerl/asuswrt-merlin.ng#69]
On my RT-AC68U, I've been using the `cp` command with the option to copy only newer files, `cp -u`.  This feature is not available on the RT-AC86U version of Busybox.  Was there an issue bringing Busybox 1.25.1 to HND platform?

```
BusyBox v1.25.1 (2018-01-24 00:18:44 EST) multi-call binary.

Usage: cp [OPTIONS] SOURCE... DEST

Copy SOURCE(s) to DEST

        -a      Same as -dpR
        -R,-r   Recurse
        -d,-P   Preserve symlinks (default if -R)
        -L      Follow all symlinks
        -H      Follow symlinks on command line
        -p      Preserve file attributes if possible
        -f      Overwrite
        -i      Prompt before overwrite
        -l,-s   Create (sym)links
        -u      Copy only newer files
```

**Comment by RMerl** [comment]
Busybox is extensively customized by Broadcom and Asus.  A first attempt by @themiron at porting BB 1.25 to HND failed, and neither of us has had the time to take another shot at it yet.  Ideally it would certainly be nice to reunify all platforms under 1.25.1, but it`s currently not a priority.  Personally, I am still dealing with the fallouts of the 382 (and now 384) jump, with some things still not working properly (some of them broken upstream).

**Comment by blackfuel** [comment]
I got his BB port to compile for HND platform and it's running on my RT-AC86U now.  If there are issues I will update here.

https://github.com/blackfuel/asuswrt-merlin.382/commit/fc908731c4deaeb8d5e112fab6cb0e79a85d43b6

**Comment by themiron** [comment]
sounds promising, does vlans works normally for you?

**Comment by blackfuel** [comment]
Because there's no robocfg for HND, I do not have a custom vlan, as I do with my RT-AC68U.  How to configure vlans on the RT-AC86U without robocfg?  There is some new Broadcom programs, I know little: `ethswctl` and `vlanctl`.

Your ported BB seems fine on the RT-AC86U.  However, I remove some Asus features for my own custom firmware.
```
MEDIASRV=n
PARENTAL2=n
WEBDAV=n
CLOUDSYNC=n
DROPBOXCLIENT=n
TIMEMACHINE=n
MDNS=n
BWDPI=n
SWEBDAVCLIENT=n
SNMPD=n
CLOUDCHECK=n
DNSFILTER=n
HSPOT=n
SMARTSYNCBASE=n
EMAIL=n
NOTIFICATION_CENTER=n
NATNL_AICLOUD=n
NATNL_AIHOME=n
IFTTT=n
ALEXA=n
LETSENCRYPT=n
VISUALIZATION=n
WTFAST=n
ROG=n
MULTICASTIPTV=n
QUAGGA=n
OPTIMIZE_XBOX=n
AMAS=n
```

**Comment by RMerl** [comment]
I`d like to move HND to 1.25 (or better yet, both to 1.27), but since I`m currently still dealing with 382/384 specific issues, I don't want to introduce another variable into the equation.  This will have to wait until after 384.xx has stabilized enough to make it possible to start introducing new low-level changes.

**Comment by RMerl** [comment]
Commits b9abd3ee7de43afda3843abdbb033b22ea99085c and 10f0099a6e5a2eb64981207fe8a83a138213c7ff have moved HND to the same busybox as non-HND models (currently 1.25.1).

I added a few applets that were present in 1.24 but not 1.25.1.  I didn't go for complete feature parity tho, as I suspect most of these are just default values Broadcom implements but aren't actually needed by Asuswrt.

Will require extensive testing.  Then if all goes well, an attempt might be done to moving to a newer version.

**Comment by mlzboy** [comment]
i build an old version busybox for ac68u due to display chinese character with `ls` cmd,hope help for u
https://github.com/mlzboy/busybox-1.25.1-armv7l/blob/master/busybox
