### ISSUE TITLE
Setup AImesh node with 2 R7000 routers doesn't work

### ISSUE THREAD

**Issue by babavers** [RMerl/asuswrt-merlin.ng#693]
With the 386 firmware, the router doesn't find any possible node to configure, not over WiFi, nor cabled.
I had to fall back to 384.19 to setup the node (gets stuck on 99% if done over WiFi, cabled connection is needed to succeed). After that upgrading to 386.1 is possible but not always. The first time I did it, the node remained existing for some days. The second time (after resetting both devices to factory default) I had to start again from scratch in version 384.19 and than updated to 386.1, it didn't. The node stayed for a while in the 386.1 version but disappeared soon after a simple reboot.
I had to go back (again) to 384.19 waiting for more AImesh stability.

**Comment by RMerl** [comment]
Asuswrt-Merlin does not support any non-Asus routers.  The firmware you are running is an illegal fork of this project.
