### ISSUE TITLE
System Time incorrect on web user interface, syslog when DST enabled

### ISSUE THREAD

**Issue by boonhui** [RMerl/asuswrt-merlin.ng#695]
**Describe the bug**

On the web user interface, System Log > General Log > System Time, syslog (and possibly other places) are not displaying the correct time when DST is enabled.

e.g. Current time is Feb 11 19:32:41 2021

System Time incorrectly shows:
![System Time](https://user-images.githubusercontent.com/10037996/107615383-f9884c80-6c43-11eb-8a9b-1cd1f9165b43.png)

However `uptime` is showing correctly:
![Uptime](https://user-images.githubusercontent.com/10037996/107615375-f68d5c00-6c43-11eb-99df-7b8ceba4d845.png)

**Model**

RT-AC86U
RT-AC68U

**Firmware version**

386.1, stable

**Client information**

Chrome 88.0.4324.150 (Official Build) (64-bit)
Firefox 85.0.2 (64-bit)

**To Reproduce**

![Basic Config](https://user-images.githubusercontent.com/10037996/107613910-3141c500-6c41-11eb-8b32-89dee24e9db1.png)

**Expected behavior**

System Log > General Log > System Time should display current time with DST enabled

**Actual results**

System Log > General Log > System Time displays current time without DST enabled

**Will this error be reproduced on the official firmware?**

Not tested on the official firmware

**Screenshots**

See above

**Additional context**

n/a

**Comment by snaunton** [comment]
Seems to be a bug on the Asus end. Set your timezone to Hobart, and enjoy the extra finger and head until this is fixed.
