### ISSUE TITLE
386.1 Aimesh 2.0 problems

### ISSUE THREAD

**Issue by nykroy** [RMerl/asuswrt-merlin.ng#696]
### Describe the bug
the devices connected by wifi to the root router on a AiMesh netrwork don't responds. 
I have some IoT devices conected throug the home. The Iot connected by wifi on nodes work perfectly but the devices conected on root router dont respond. I can see how it is conected by the router web ui but if i try to access to the web ui interface or action that Iot Devices they dont responds.
The devices on the root router are near to the root  router, and if i connect those to the node moving them near to the nodes they works perfectly ( so the IoT devices havent got any problem i think)

With Aimesh 1.0 i had not this problem so i think this is a problem on the aimesh 2.0. It is possible? 

In other hands. I have a nas on 192.168.1.6 (wired connection to the root router)  if i connect my movil by wifi to the root (because i am near to him) i cant access to the nas ( but i can access to google), but if i connect my movil to the node i can access to the synology perfectly. I seems like the wifi devices connected to the root router are isolated from the ethernet devices and from the nodes. It is possible? 

Sorry for my English and thank you very much your work!!

### Model

root router RT-AC88U
nodes 2 RT-AC68U

### Firmware version

386.1, stable

### Client information

Chrome 88.0.4324.150 (Official Build) (64-bit)
Firefox 85.0.2 (64-bit)

Screenshots

![image](https://user-images.githubusercontent.com/7745881/107679996-8f9c9100-6c9d-11eb-8d22-c2d0c70ddec8.png)
![image](https://user-images.githubusercontent.com/7745881/107680049-a511bb00-6c9d-11eb-9978-4d629f49d08f.png)

Additional context

n/a

**Comment by RMerl** [comment]
Everything related to AiMesh is closed source and outside of my control.
