### ISSUE TITLE
my internet connection is really slow

### ISSUE THREAD

**Issue by darksh3ll** [RMerl/asuswrt-merlin.ng#714]
on my ASUS RT-AC88U router my internet connection is really slow with 600Mpbs r45 cable I've switched to 200 Mbps since I upgraded to version 386.1.2

**Comment by paldier** [comment]
Disable all qos

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
