### ISSUE TITLE
ROG Rapture GT-AXE11000 Support

### ISSUE THREAD

**Issue by breisig** [RMerl/asuswrt-merlin.ng#722]
Is it possible to get the Asus ROG Rapture GT-AXE11000 firmware support? I know you have the GT-AX11000 firmware support so hopefully the GT-AXE11000 shouldn't be that difficult to include?

 Thank you!

**Comment by RMerl** [comment]
Not at this time.

**Comment by kfortner** [comment]
I would be interested in the GT-AXE11000 being supported.

**Comment by breisig** [comment]
@kfortner I agree. I miss not having the Merlin firmware running on it.
