### ISSUE TITLE
Unhandled level 3 translation fault

### ISSUE THREAD

**Issue by dbmajor** [RMerl/asuswrt-merlin.ng#727]
Hi all,

After upgrading my RT-AC86U to 386.1_2, I'm receiving this error:

ar 24 11:15:40 kernel: dcd[25514]: unhandled level 3 translation fault (11) at 0x00000000, esr 0x92000007
Mar 24 11:15:40 kernel: pgd = ffffffc015618000
Mar 24 11:15:40 kernel: [00000000] *pgd=0000000019335003, *pud=0000000019335003, *pmd=0000000002258003, *pte=0000000000000000
Mar 24 11:15:40 kernel: CPU: 1 PID: 25514 Comm: dcd Tainted: P           O    4.1.27 #2
Mar 24 11:15:40 kernel: Hardware name: Broadcom-v8A (DT)
Mar 24 11:15:40 kernel: task: ffffffc01417c040 ti: ffffffc009194000 task.ti: ffffffc009194000
Mar 24 11:15:40 kernel: PC is at 0xf716ef44
Mar 24 11:15:40 kernel: LR is at 0x1dd14
Mar 24 11:15:40 kernel: pc : [<00000000f716ef44>] lr : [<000000000001dd14>] pstate: 600f0010
Mar 24 11:15:40 kernel: sp : 00000000ffceb138
Mar 24 11:15:40 kernel: x12: 00000000000a2050 
Mar 24 11:15:40 kernel: x11: 00000000f63ff024 x10: 00000000000a23c4 
Mar 24 11:15:40 kernel: x9 : 00000000f63ffbac x8 : 00000000000a287c 
Mar 24 11:15:40 kernel: x7 : 00000000f63ffbdc x6 : 00000000000a2876 
Mar 24 11:15:40 kernel: x5 : 0000000000000000 x4 : 00000000f63ffb90 
Mar 24 11:15:40 kernel: x3 : 0000000000000000 x2 : 0000000000000000 
Mar 24 11:15:40 kernel: x1 : 000000000007d75a x0 : 0000000000000000

Further to the above, the router keeps requesting IP renewals from the ISP that I've only picked up since putting a logging entry into a dhcpc-event script.

Any help would be appreciated.

Cheers.

**Comment by RMerl** [comment]
Well-known issue that has existed for years with the dcd process on the RT-AC86U.  Outside of my control.
