### ISSUE TITLE
blog_request dpsta put_stats (null)

### ISSUE THREAD

**Issue by pdc1** [RMerl/asuswrt-merlin.ng#734]
Problem: on my RT-AC86U AiMesh node with remote syslog, the log file is filling up with very frequent (and useless) log messages for a null put_stats related to "dpsta" device. I counted as many as 15 per minute.

```
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
Apr  3 11:15:11 AC86U-OFFICE kernel: blog_request 1502: dev dpsta put_stats           (null)
```

This is caused by a patch from Asus: 2f7a878aad kernel: proper fix for wlan accumulating stats issue

The following change is the cause:

```
-            if ( (dev_p->reg_state == NETREG_REGISTERED) && virt_addr_valid(dev_p->put_stats) )
-                dev_p->put_stats( dev_p, bstats_p );
--------
+            if (dev_p->reg_state == NETREG_REGISTERED) {
+                unsigned long addr = (unsigned long)(dev_p->put_stats);
+                if (virt_addr_valid(dev_p->put_stats) || (addr >= MODULES_VADDR && addr < MODULES_END))
+                    dev_p->put_stats( dev_p, bstats_p );
+                else
+                    printk("%s %d: dev %s put_stats %p\n", __FUNCTION__, __LINE__, dev_p->name, dev_p->put_stats);
+            }
```

Given that dev_p->put_stats is null, it does not seem this message is working as intended. I would suggest adding "if (dev_p->put_stats != null)" to the else statement...

I did not notice this during the beta, and my comments may have gotten lost in the post-release thread (https://www.snbforums.com/threads/asuswrt-merlin-386-2-is-now-available.71625/post-679519). My apologies if posting an issue here is not helpful.

**Comment by RMerl** [comment]
Since that else branch is purely debugging output, it would be simpler to simply remove it altogether.
