### ISSUE TITLE
New wiki entry: Compile-Firmware-from-source (multi-platform)

### ISSUE THREAD

**Issue by 1951FDG** [RMerl/asuswrt-merlin.ng#735]
Hi @RMerl,

I've recently had to compile the firmware to compile additional kernel modules not present and I've written a definitive guide on how to compile the firmware on multiple platforms using [Multipass](https://multipass.run):

[Compile-Firmware-from-source](https://github.com/RMerl/asuswrt-merlin.ng/wiki/Compile-Firmware-from-source)

If you  could revise it quickly, especially the part:

Note: Do not build from the master branch, build from the mainline.384 branch or ax.384 branch.

I am not entirely sure if one has to use the master branch, or otherwise. Hopefully I got the above note right in the wiki...

**Comment by RMerl** [comment]
The 384.xxxx branches are over 6 months old.  The current code is on master at this time.

**Comment by 1951FDG** [comment]
Ok, I've made the changes to wiki entry! Thanks for the info.
