### ISSUE TITLE
Bug in error handling of wget in sig2nd_upgrade.sh

### ISSUE THREAD

**Issue by modemboy** [RMerl/asuswrt-merlin.ng#74]
I believe there is a bug in the https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src/router/rom/webs_scripts/sig2nd_upgrade.sh file regarding the error handling of wget.
In the previous version of the script https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src/router/rom/webs_scripts/sig_upgrade.sh on line 52 you do the wget exit code error check right after the wget command, no problem.

In the new version there is an nvram get command inserted after the wget but before the error check, on line 42: https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src/router/rom/webs_scripts/sig2nd_upgrade.sh#L43

This causes the script to check the exit code of the nvram get command instead of wget, which is always going to be 0. Looks like that line can just be moved above the wget to fix the issue.

I found this due to currently getting 404 errors from Asus's site trying to download the sig file when using wget manually (which returns an exit code of 8), but the script continued on outputting:
---- Download and mv trf OK ----
---- sig rule mv jffs ----

when it should have errored out with:
---- Download and mv trf Failure ----

**Comment by RMerl** [comment]
This code is actually straight from Asus, I haven't made any change to it.

Moving that nvram to the top where it belongs should resolve this.
