### ISSUE TITLE
Add support for easyDNS dynamic DNS

### ISSUE THREAD

**Issue by Ruslan-Urban** [RMerl/asuswrt-merlin.ng#740]
This is a feature request.

EasyDNS dynamic DNS service is one of the popular services in North America. It is supported by other firmwares like Advanced Tomato.

The following article contains the easyDNS Dynamic DNS client specification, which is very similar to the protocols used by other Dynamic DNS service providers.

[https://kb.easydns.com/knowledge/dynamic-dns/](https://kb.easydns.com/knowledge/dynamic-dns/)

**Comment by RMerl** [comment]
I currently have no plan to add more DDNS services to the webui because it would be an endless task to add and manage everyone's personal favorite.

Inadyn, the DDNS client used by Asuswrt-Merlin has EasyDNS support, so you can use it through a custom configuration.
