### ISSUE TITLE
cru not work as expected when expect it to run once every two days.

### ISSUE THREAD

**Issue by zw963** [RMerl/asuswrt-merlin.ng#746]
**Describe the bug**

Add a task,  i want it to run once every two days, so i add a new task like this.

```
cru a update_geosites "* * */2 * *" "/opt/etc/update_geosite.sh"
```

What i expected is, "/opt/etc/update_geosite.sh" will be run once every two days,
but after i add it, it will be run very frequently which cause network disconnect.
(because update_geosite.sh will restart network)

following is content of update_geosite.sh

https://raw.githubusercontent.com/zw963/asuswrt-merlin-v2ray/master/router/opt/etc/update_geosite.sh

**Model**

RT-AC5300

**Firmware version**

384.19

**Expected behavior**

It should not run so frequently.

**Comment by paldier** [comment]
>  (because update_geosite.sh will restart network)

Why?  You do not need to restart network.

**Comment by zw963** [comment]
> The command to restart dnsmasq is `service restart_dnsmasq`

Sorry, the key issue is not restart network, the issue is `/opt/etc/update_geosite.sh` was restart too frequently.

In fact, what i means for restart network is this. `/opt/etc/init.d/S22v2ray restart`, it is a proxy service.

**Comment by paldier** [comment]
You do NOT NEED to restart network, OK? V2ray will not do that, it's you. So, the firmware has no bugs.
If you want to learn how to restart plugins, you can see https://github.com/MerlinRdev/softcenterarm/blob/master/koolproxy/koolproxy/koolproxy/kp_config.sh

**Comment by zw963** [comment]
> You do NOT NEED to restart network, OK? V2ray will not do that, it's you. So, the firmware has no bugs.
> If you want to learn how to restart plugins, you can see https://github.com/MerlinRdev/softcenterarm/blob/master/koolproxy/koolproxy/koolproxy/kp_config.sh

Sorry,  maybe not explain clearly,  i am not restart network, i just restart v2ray to load newest `geosite.dat`.
but when restart v2ray, my network is disconnect because proxy is temorary unvailable.

But anyway, above things not relative to this issue, the issue is, why this script has been reboot frequently instead of once two day?

**Comment by kwloafman** [comment]
See here
<https://www.cyberciti.biz/faq/how-to-add-cron-job-on-asuswrt-merlin-wifi-router/>.
Your command should be:

# cru a update_geosites "* * */2 * * /opt/etc/update_geosite.sh"

all as one string, not two.

...Ken

**Comment by paldier** [comment]
````
Cron Utility
add:    cru a <unique id> <"min hour day month week command">
delete: cru d <unique id>
list:   cru l
````

**Comment by zw963** [comment]
Thank  you, following is my cron tasks.

![image](https://user-images.githubusercontent.com/549126/115410674-68c28400-a225-11eb-8c48-29805f7b5078.png)

the first one is run with  `cru a update_geosites "* * */2 * *" "/opt/etc/update_geosite.sh"`
the second one is run with `cru a update_geosites "* * */2 * * /opt/etc/update_geosite.sh"`

Any different ? 

in fact, i think another two service(run-services, run-iptables) is works as expected.

**Comment by paldier** [comment]
Are you kidding me? 
````
*/1 * * * * /jffs/scripts/services-start
````

**Comment by zw963** [comment]
Hi, i tested with new syntax,  `cru a update_geosites1 "* * */2 * * /opt/etc/update_geosite.sh"`, it not work too.

I am very sure `/opt/etc/update_geosite.sh` is invoked very frequently, so, that is a bug?

 



> Are you kidding me?
> 
> ```
> */1 * * * * /jffs/scripts/services-start
> ```

No, i hope `services-start` can be run frequently to ensure sometimes somethings broken v2ray, as you can see, it run very quickly if all program was working fine.

![image](https://user-images.githubusercontent.com/549126/115414707-d9b76b00-a228-11eb-84c8-b5bf4d2376f3.png)

**Comment by RMerl** [comment]
> No, i hope services-start can be run frequently to ensure sometimes somethings broken v2ray, as you can see, it run very quickly if all program was working fine.

Do NOT do that.  That script is only intended to be run ONCE, at **boot time**.

Your cron entry does not work because busybox's crontab does not allow using the "/" operator on the day, it's only support on minutes and hours.  See this reference:

https://openwrt.org/docs/guide-user/base-system/cron

This is working as intended.  If you want extended crontab support, you will have to contact the busybox devs about this.
