### ISSUE TITLE
2.4ghz traffic is isolated if Guest Network 1 Isolation is turned on

### ISSUE THREAD

**Issue by russellweed** [RMerl/asuswrt-merlin.ng#747]
**Describe the bug**
With *Smart Connect* turned off and separate SSIDs used for the main 2.4 and 5ghz networks, and *Set AP Isolated* turned off for both bands, if a 2.4ghz Guest Network is created in the 1st slot with isolation turned on (`wl0.1_ap_isolate=1`) it will eventually cause the main 2.4ghz network to turn start isolating traffic as if *Set AP Isolated* was turned on.

- The trigger for this seems to be semi-random, as it can be as early as within an hour, or as late as a day later. The average seems to be 3-6 hours since the last reboot
- All clients on the 2.4ghz network can no longer ping or otherwise reach any other device on the network
- Internet access remains, as one would expect with isolation turned on
- Rebooting the router or otherwise resetting wi-fi network will temporarily fix the issue. The main 2.4 network can see other clients but the guest network still cannot (as intended).
- The 5ghz network remains unaffected and can see all clients on any band or wired [separate SSID and no guest network on 5ghz]
- A guest network in slot 2 does NOT cause any problems, so the issue can be worked around by simply keeping the 1st guest network disabled (although it took me several weeks and factory resets to discover this)

**Model**
RT-AX88U

**Firmware versions**
386.1 - 386.2_2 (latest at the time of this report)

**Client information**
Any device on the 2.4ghz network is affected, including:
- iPhones
- iPads
- Windows PCs
- IP Cameras
- IOT devices

**To Reproduce**
1. Turn off *Smart Connect* and give each band a separate SSID
2. Turn off *Set AP Isolated* for each band
3. Enable a 2.4ghz network in the first slot and turn on AP Isolation
4. Wait up to 24 hours (although it averages around 3-6 hours) for isolation to kick in

**Expected behavior**
Client Isolation for the guest 2.4ghz network, no isolation for the regular 2.4 and 5ghz networks

**Actual results**
After a few hours, the main 2.4ghz network will start isolating traffic. The 5ghz network continues to operate normally,

**Will this error be reproduced on the official firmware?**
I have not tested, sorry.

**nvram Settings**
Below is an nvram show from when the bug was occurring (2.4ghz clients were being isolated). Note that the wl0_ap_isolate value is 0 even though it is currently acting as if it were 1! (This is also with the 2nd guest network disabled)
```bash
ASUSWRT-Merlin RT-AX88U 386.2_2 Tue Apr 13 21:13:01 UTC 2021
admin@RT-AX88U-2FF0:/tmp/home/root# nvram show | grep isolate
size: 69995 bytes (61077 left)
wl0.1_ap_isolate=1
wl0.2_ap_isolate=0
wl0.3_ap_isolate=0
wl0_ap_isolate=0
wl1.1_ap_isolate=0
wl1.2_ap_isolate=0
wl1.3_ap_isolate=0
wl1_ap_isolate=0
wl_ap_isolate=0
```

**Additional Information**
- I have not tested what happens if *Smart Connect* is on and a single SSID is used
- I have not tested what happens if a 5ghz Guest Network with isolation is used
- If isolation is turned off for 2.4 Guest Network 1, everything is fine and the bug does not occur
- Resetting router to factory default after updating to 386.2_2 did not solve the issue, although it did seem to not come back for a little longer (2 days instead of 1)
- This can happen even as devices are currently connected to the router pulling a constant connection (streaming video from an IP camera, which suddenly cuts out as I'm watching it)
- I have waited a few days to verify that the "only use the 2nd slot" workaround works consistently and is error free
- This bug may be present in earlier versions than 386.1, but I have not gone back to test them.

Thank you for your time and effort!

**Comment by RMerl** [comment]
Everything related to wifi is closed source and outside of my control.
