### ISSUE TITLE
Can have at most 1 VPN client connect to the firmware's OpenVPN server at one time

### ISSUE THREAD

**Issue by changyuheng** [RMerl/asuswrt-merlin.ng#754]
**Describe the bug**
If multiple clients connect to the firmware's OpenVPN server at the same time, only the latest connected client will work, the others will get stalled.

**Model**
RT-AC68U

**Firmware version**
386.2_4

**Client information**
The latest OpenVPN Connect

**To Reproduce**
1. Create 2 username/password pairs for the OpenVPN server on the router.
2. Having 2 computers connect to the OpenVPN server at the same time. Each computer connects with one unique username/password pair.

**Expected behavior**
Multiple clients are able to connect to the router's OpenVPN server at the same time.

**Actual results**
Once the second client connects to the server, the first client's connection will get stalled. The first client will then re-connect to the server after the defined timeout. And then the second client's connection will get stalled. And so on.

**Will this error be reproduced on the official firmware?**
No.

**Screenshots**

Here are some screenshots I took from the *official* firmware. I had very similar settings on the Merlin firmware.

<img width="992" alt="Screen Shot 2021-05-26 at 10 46 33 AM" src="https://user-images.githubusercontent.com/1842626/119596069-1cb0c380-be11-11eb-855e-acf17078753b.png">

<img width="778" alt="Screen Shot 2021-05-26 at 10 45 59 AM" src="https://user-images.githubusercontent.com/1842626/119596066-1b7f9680-be11-11eb-8b70-56d6c9c0e3c5.png">

<img width="217" alt="Screen Shot 2021-05-26 at 10 42 41 AM" src="https://user-images.githubusercontent.com/1842626/119596050-191d3c80-be11-11eb-85bc-5eacc009ea92.png">

**Additional context**

A piece of log of the VPN server:

```
Session invalidated: KEEPALIVE_TIMEOUT
Client terminated, restarting in 2000 ms...
```

**Comment by haohetao** [comment]
I have same problem,after each reboot, only first openvpn client can connect,all other client authentication failed.

**Comment by OliverPA77** [comment]
Had the same issue and tried to generate further client certificates following the [guide](https://github.com/RMerl/asuswrt-merlin.ng/wiki/Generating-OpenVPN-keys-using-Easy-RSA) in the wiki but it doesn't work (lots of errors coming from the openssl.cnf file). I assume we'd need to generate additional client certificates and then edit the downloaded ovpn files.

As a workaround I made two changes - after that having >1 client connecting worked fine and survived a reboot.
VPN Server -> VPN Details -> Advanced -> Username / Password Auth. Only = Yes :(
I assume this is actually enough but for the record I also assigned static IPs by following this [guide](https://github.com/RMerl/asuswrt-merlin.ng/wiki/Static-ip-for-OpenVPN-clients).

**Comment by RMerl** [comment]
Works for me.  Must be a configuration issue, look at your system log for more info.  For instance if you use client certificates, then each client must have a certificate with a unique common-name.

**Comment by RMerl** [comment]
Also based on your screnshots, this isn't my firmware, this is Asus' stock firmware.  If you have an issue with the stock firmware, then contact Asus about it.

**Comment by haohetao** [comment]
> Works for me. Must be a configuration issue, look at your system log for more info. For instance if you use client certificates, then each client must have a certificate with a unique common-name.

Are you saying that each user should use a separate client certificate?

**Comment by haohetao** [comment]
@RMerl 
I‘m config username-as-comman-name.

**Comment by OliverPA77** [comment]
Yes you need to generate a certificate for each client using this [guide](https://github.com/RMerl/asuswrt-merlin.ng/wiki/Generating-OpenVPN-keys-using-Easy-RSA), then you export the generic client config using VPN Server -> Export OpenVPN configuration file and edit it for each client (you will find "insert client certificate/key" lines in the downloaded config).
Afterwards you can also set Username/Password Authentication to No.

@RMerl The issue with the guide (or the easy rsa script) is that after the step "cd /mnt/sda1/easy-rsa" you also need to cp openssl-1.0.0.cnf openssl.cnf otherwise the script complains about missing openssl.cnf file.
Once doing this extra step everything worked as expected and as documented.

**Comment by haohetao** [comment]
@RMerl 
The above problems still occur as long as the user password authentication is enabled

**Comment by haohetao** [comment]
![图片](https://user-images.githubusercontent.com/4592571/126930332-27e5b130-0ef0-4b84-b3b3-1691b4926249.png)
