### ISSUE TITLE
RT-AX86U unknown device COMPAL INFORMATION (KUNSHAN) CO shown in Network map list

### ISSUE THREAD

**Issue by jacktheripper19** [RMerl/asuswrt-merlin.ng#755]
Hello, I don't know if this is the right place to post this.

After updating to the latest version 386.2_4 on my RT-AX86U, I noticed a new device in the network map list with the name of COMPAL INFORMATION (KUNSHAN) CO. At first it's shown as if it's connected through Ethernet with a public IP address? After rebooting the router, it showed up again but with a local IP address. All my devices are connected with wireless.

**Comment by dave14305** [comment]
From the README:
Please do not use Github's Issue tracker for support requests. Use the support forums at [SNBForums](https://www.snbforums.com/forums/asuswrt-merlin.42/) instead. The issue tracker is for development/bug tracking purposes only!
