### ISSUE TITLE
why rewirte commit history?

### ISSUE THREAD

**Issue by sadoneli** [RMerl/asuswrt-merlin.ng#756]
I noticed the whole projet commit hash have been changed since the sccond commit in this project: 2e104e83cd16cfec2eb55aed10741d70b954f134

by compare rewirted version and my backup version, some files related to boardcom SDK and WPS were removed in history commit.

why remove those file in history other than just remove them in HEAD and commit it?

**Comment by RMerl** [comment]
Because confidential files had to be purged from the repo.  Just removing them from HEAD would still leave them easily available.
