### ISSUE TITLE
2.4Ghz not working after firmware upgrade

### ISSUE THREAD

**Issue by Syst3mSh0ck** [RMerl/asuswrt-merlin.ng#757]
After upgrading from 386.2_2 to 386.2_6 my 2.4Ghz Wireless network is no longer working. I can't see the SSID being broadcasted and manually connecting doesn't work either (just in case it's hidden for some reason; it's not set that way).

Model: RT-AC86U
Firmware: 386.2_6

I've not tried a Factory Reset because I'm not sure how to do it properly with these Routers. I've read a few guides but it seems quite convoluted due to the different ways/types of resets available. If you think I should try this, could someone please kindly explain the best way of resetting this Router. Thanks for all your hard work.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
