### ISSUE TITLE
RT-AC87U support

### ISSUE THREAD

**Issue by umerov1999** [RMerl/asuswrt-merlin.ng#76]
Do you want to plan RT-AC87U support in this repository. Asus Public Source Code for 382 firmware http://dlcdnet.asus.com/pub/ASUS/wireless/RT-AC87U/GPL_RT_AC87U_300438250010.zip?_ga=2.246236483.636355255.1517759932-208863152.1517164101

**Comment by RMerl** [comment]
Please do not use the bug tracker for questions or support requests.

The RT-AC87U GPL will be evaluated after the 384.3 release.
