### ISSUE TITLE
DHCP Manual Assignment not Honoring Full IP entered

### ISSUE THREAD

**Issue by jonestristand** [RMerl/asuswrt-merlin.ng#760]
**Describe the bug**
Using asus merlin wrt firmware with YazDHCP. Router is 10.0.1.1/16, but DHCP manual assignment doesn't let me assign anything other than on 10.0.1.0/24. For instance if I enter 10.0.3.70 as the assigned IP for a particular MAC address, it will accept it when I press Add, but after pressing Apply it will have changed it to 10.0.1.70. What gives?!

**Model**

RT-AC66U B1

**Firmware version**

386.2_4

**Client information**

Chrome

**To Reproduce**

As above. Change router LAN IP to be 10.0.1.1, subnet to be 255.255.0.0, then try to assign a manual IP to 10.0.3.70 for instance. It will accept the change and add to the list when the "Add" button is clicked, but after "Apply" completes will have changed it to 10.0.1.70

**Expected behavior**

I would expect this to allow me to assign the IP 10.0.3.70 to a MAC address as this is on the same subnet as the router (10.0.1.1/16)

**Actual results**

Aafter "Apply" completes will have changed it to 10.0.1.70.

**Will this error be reproduced on the official firmware?**

Unknown.

**Screenshots**

![image](https://user-images.githubusercontent.com/6055279/123594734-ee722b00-d7a4-11eb-94a9-07da8d391402.png)
![image](https://user-images.githubusercontent.com/6055279/123594813-02b62800-d7a5-11eb-977f-0be070f1f078.png)
![image](https://user-images.githubusercontent.com/6055279/123594896-1a8dac00-d7a5-11eb-8f3c-b43ef9f14521.png)
![image](https://user-images.githubusercontent.com/6055279/123594962-32fdc680-d7a5-11eb-9cc9-cb930e8936f3.png)
![image](https://user-images.githubusercontent.com/6055279/123595102-5a549380-d7a5-11eb-9b48-c27dfcb53533.png)

**Comment by dave14305** [comment]
That’s a YazDHCP issue, not a firmware issue.
