### ISSUE TITLE
RT-AX86U - "nvram show" anomaly

### ISSUE THREAD

**Issue by ColinTaylorUK** [RMerl/asuswrt-merlin.ng#764]
I don't know whether this is a bug or a feature.

When looking at the output of `nvram show` some variables are duplicated. The duplicates are for the variables that have been moved into `/jffs/nvram`. The first occurrence of the variable in the output shows it containing a null string whereas the second occurrence shows its real value.

`nvram get` always returns the correct value (AFAIK).

On my router this is the case for all variables in `/jffs/nvram` with 5 exceptions.

**Model**
RT-AX86U

**Firmware version**
386.2_6

**To Reproduce**

Look at the contents of /jffs/nvram/ and pick some variables. Then issue the following command (for example):

`nvram show 2>/dev/null | grep -E "autofw_rulelist|custom_usericon_del|ipsec_client_list_3|subnet_rulelist=|vts_rulelist" | sort`
autofw_rulelist=
autofw_rulelist=
custom_usericon_del=
custom_usericon_del=
game_vts_rulelist=
game_vts_rulelist=
ipsec_client_list_3=
ipsec_client_list_3=
subnet_rulelist=
subnet_rulelist=192.168.101.1>255.255.255.0>1>192.168.101.2>192.168.101.254>86400>>>>>>1>192.168.102.1>255.255.255.0>1>192.168.102.2>192.168.102.254>86400>>>>>>1>
vts_rulelist=
vts_rulelist=<EchoLink>5198:5199>192.168.1.49>>UDP><FTP Server>54000>192.168.1.9>21>TCP><FTP Passive Ports>55000:55100>192.168.1.9>>TCP>

I found only 5 exceptions to this duplication:

`nvram show 2>/dev/null | grep -E "dhcp_hostnames|keyword_rulelist|url_rulelist|vpn_server_custom|vpnc_clientlist"`
dhcp_hostnames=
keyword_rulelist=
url_rulelist=
vpn_server_custom=
vpnc_clientlist=

**The Issue**

While being largely cosmetic there are posts in the forum that suggest people run the following code to "clean up" empty variables. I can see this might cause a problem.

http://www.snbforums.com/threads/solved-high-nvram-usage.56848/post-494736

**Comment by RMerl** [comment]
nvram manipulation code is closed source since HND, nothing I can do about it.
