### ISSUE TITLE
'openvpn-event' custom script not persistent

### ISSUE THREAD

**Issue by macek-jm** [RMerl/asuswrt-merlin.ng#766]
Custom script: 'openvpn-event' file disappear after reboot, router. [no problem witch other custom scripts]

**Model**

RT-AC86U

**Firmware version**

386.2_6

**Client information**

**To Reproduce**

put file to /jffs/scripts and reboot

**Expected behavior**

should stay 
**Actual results**

file dissapear ;)

**Will this error be reproduced on the official firmware?**

**Screenshots**

**Additional context**

**Comment by RMerl** [comment]
Unable to reproduce here.

Try the following:

1) Post the content of /jffs/asd.log (if you have that file
2) Remove the content of /jffs/asd/ then reboot

**Comment by macek-jm** [comment]
Thanks, now everything is ok[after remove content of /jffs/asd/ ],
what mistake I made?

content of my old  asd.log 

1525496710[register_feature] blockfile registered 
1525496710[register_feature] chknvram registered 
1525496710[register_feature] misc registered 
1525496710[init] Load existing signature files.
1525496710[update_signature_in_feature] Update sig in feature(blockfile)
1525496710[update_signature_in_feature] Update sig in feature(chknvram)
1525496715[chknvram_action]Unset invalid nvram,<jffs2_scripts, 0>
1624989729[check_version_from_server] Check server at Tue Jun 29 20:02:09 2021
1624989731[update_signature_in_feature] Update sig in feature(chknvram)
1624989731[check_version_from_server]update version file
1525496711[register_feature] blockfile registered 
1525496711[register_feature] chknvram registered 
1525496711[register_feature] misc registered 
1525496711[init] Load existing signature files.
1525496711[update_signature_in_feature] Update sig in feature(blockfile)
1525496711[update_signature_in_feature] Update sig in feature(chknvram)
1525496710[register_feature] blockfile registered 
1525496710[register_feature] chknvram registered 
1525496710[register_feature] misc registered 
1525496710[init] Load existing signature files.
1525496710[update_signature_in_feature] Update sig in feature(blockfile)
1525496710[update_signature_in_feature] Update sig in feature(chknvram)
1625208260[check_version_from_server] Check server at Fri Jul  2 08:44:20 2021
1625208263[_download_and_verify_file] Download file (version) fail!
1625208290[check_version_from_server] Check server at Fri Jul  2 08:44:50 2021
1625208293[_download_and_verify_file] Download file (version) fail!
1625208320[check_version_from_server] Check server at Fri Jul  2 08:45:20 2021
1625208323[_download_and_verify_file] Download file (version) fail!
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496710[register_feature] blockfile registered 
1525496710[register_feature] chknvram registered 
1525496710[register_feature] misc registered 
1525496710[init] Load existing signature files.
1525496710[update_signature_in_feature] Update sig in feature(blockfile)
1525496710[update_signature_in_feature] Update sig in feature(chknvram)
1525496710[register_feature] blockfile registered 
1525496710[register_feature] chknvram registered 
1525496710[register_feature] misc registered 
1525496710[init] Load existing signature files.
1525496710[update_signature_in_feature] Update sig in feature(blockfile)
1525496710[update_signature_in_feature] Update sig in feature(chknvram)
1525496710[register_feature] blockfile registered 
1525496710[register_feature] chknvram registered 
1525496710[register_feature] misc registered 
1525496710[init] Load existing signature files.
1525496710[update_signature_in_feature] Update sig in feature(blockfile)
1525496710[update_signature_in_feature] Update sig in feature(chknvram)
1525496710[register_feature] blockfile registered 
1525496710[register_feature] chknvram registered 
1525496710[register_feature] misc registered 
1525496710[init] Load existing signature files.
1525496710[update_signature_in_feature] Update sig in feature(blockfile)
1525496710[update_signature_in_feature] Update sig in feature(chknvram)
1525496710[register_feature] blockfile registered 
1525496710[register_feature] chknvram registered 
1525496710[register_feature] misc registered 
1525496710[init] Load existing signature files.
1525496710[update_signature_in_feature] Update sig in feature(blockfile)
1525496710[update_signature_in_feature] Update sig in feature(chknvram)
1525496710[register_feature] blockfile registered 
1525496710[register_feature] chknvram registered 
1525496710[register_feature] misc registered 
1525496710[init] Load existing signature files.
1525496710[update_signature_in_feature] Update sig in feature(blockfile)
1525496710[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1625507768[check_version_from_server] Check server at Mon Jul  5 19:56:08 2021
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1625508528[check_version_from_server] Check server at Mon Jul  5 20:08:48 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1625509566[check_version_from_server] Check server at Mon Jul  5 20:26:06 2021
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1625510504[check_version_from_server] Check server at Mon Jul  5 20:41:44 2021
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1625510916[check_version_from_server] Check server at Mon Jul  5 20:48:36 2021
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1625511906[check_version_from_server] Check server at Mon Jul  5 21:05:06 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1625512479[check_version_from_server] Check server at Mon Jul  5 21:14:39 2021
1625532549[check_version_from_server] Check server at Tue Jul  6 02:49:09 2021
1625532552[_download_and_verify_file] Download file (version) fail!
1625532579[check_version_from_server] Check server at Tue Jul  6 02:49:39 2021
1625532582[_download_and_verify_file] Download file (version) fail!
1625532609[check_version_from_server] Check server at Tue Jul  6 02:50:09 2021
1625532612[_download_and_verify_file] Download file (version) fail!
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] dump /jffs/scripts/openvpn-event.
<brctl addbr br12>
1625595127[check_version_from_server] Check server at Tue Jul  6 20:12:07 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496712[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496712[blockfile] dump /jffs/scripts/openvpn-event.
<#!/bin/sh

# wypiecie interfejsu tap12 z bridga br0
brctl delif br0 tap12
# dopiecie tap12 do wczesniej wytworzonego bridga br10
brctl addif br10 tap12
# konfiguracja ip
ifconfig br10 192.168.0.251 netmask 255.255.255.0
ifconfig br10 allmulti up
>
1625596046[check_version_from_server] Check server at Tue Jul  6 20:27:26 2021
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496714[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496714[blockfile] /jffs/scripts/openvpn-event is binary.
1625596486[check_version_from_server] Check server at Tue Jul  6 20:34:46 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1625597018[check_version_from_server] Check server at Tue Jul  6 20:43:38 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1625597231[check_version_from_server] Check server at Tue Jul  6 20:47:11 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1625597453[check_version_from_server] Check server at Tue Jul  6 20:50:53 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1625598067[check_version_from_server] Check server at Tue Jul  6 21:01:07 2021
1625630287[check_version_from_server] Check server at Wed Jul  7 05:58:07 2021
1625630291[_download_and_verify_file] Download file (version) fail!
1625630317[check_version_from_server] Check server at Wed Jul  7 05:58:37 2021
1625630321[_download_and_verify_file] Download file (version) fail!
1625630347[check_version_from_server] Check server at Wed Jul  7 05:59:07 2021
1625630351[_download_and_verify_file] Download file (version) fail!
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496714[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496714[blockfile] /jffs/scripts/openvpn-event is binary.
1625656476[check_version_from_server] Check server at Wed Jul  7 13:14:36 2021
1625656480[_download_and_verify_file] Download file (version) fail!
1625656507[check_version_from_server] Check server at Wed Jul  7 13:15:07 2021
1625656510[_download_and_verify_file] Download file (version) fail!
1625656536[check_version_from_server] Check server at Wed Jul  7 13:15:36 2021
1625656540[_download_and_verify_file] Download file (version) fail!
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1625682644[check_version_from_server] Check server at Wed Jul  7 20:30:44 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496714[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496714[blockfile] /jffs/scripts/openvpn-event is binary.
1625766488[check_version_from_server] Check server at Thu Jul  8 19:48:08 2021
1525496713[register_feature] blockfile registered 
1525496713[register_feature] chknvram registered 
1525496713[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496714[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496714[blockfile] /jffs/scripts/openvpn-event is binary.
1625767297[check_version_from_server] Check server at Thu Jul  8 20:01:37 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1625767997[check_version_from_server] Check server at Thu Jul  8 20:13:17 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1625768741[check_version_from_server] Check server at Thu Jul  8 20:25:41 2021
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496712[init] Load existing signature files.
1525496712[update_signature_in_feature] Update sig in feature(blockfile)
1525496712[update_signature_in_feature] Update sig in feature(chknvram)
1525496713[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496713[blockfile] /jffs/scripts/openvpn-event is binary.
1525496712[register_feature] blockfile registered 
1525496712[register_feature] chknvram registered 
1525496712[register_feature] misc registered 
1525496713[init] Load existing signature files.
1525496713[update_signature_in_feature] Update sig in feature(blockfile)
1525496713[update_signature_in_feature] Update sig in feature(chknvram)
1525496714[remove_file_in_dir]Delete harmful file,/jffs/scripts/openvpn-event
1525496714[blockfile] /jffs/scripts/openvpn-event is binary.

**Comment by RMerl** [comment]
Your router was still using ASD security signatures from the stock firmware, which deletes any existing openvpn-event script.  Removing the signatures fixed it, your router should normally download Asuswrt-Merlin specific signatures after that.  No idea why it didn't, maybe something on your configuration is preventing your router from properly updating its signature files with Asuswrt-Merlin versions.
