### ISSUE TITLE
WiFi 2.4 GHz stops working when USB stick is plugged in

### ISSUE THREAD

**Issue by thalch** [RMerl/asuswrt-merlin.ng#768]
**Describe the bug**
Whenever I attach a USB 3 stick to my router the 2.4 GHz Wifi stops working

**Model**
Asus RT-AC68U

**Firmware version**
386.2_6

**Client information**
I have this issue with iPhone`s  iOS 14.6 (latest available), Windows 10 laptops as well as Sonos speakers

**To Reproduce**
restart the router without the USB stick, connect the devices and ensure the internet is working, If this is fine plug in the USB stick and check the internet again. For me Sonos speakers are not available any more. If I try to reconnect the iPhone I do not get an IP address. Same on Windows 10

**Expected behavior**
The WiFi should work as without the USB stick

**Actual results**
WiFi stops working

**Will this error be reproduced on the official firmware?**
not tested

**Screenshots**

**Additional context**
Wifi 5 Ghz is working as usual. The stick was formatted with amtm and ext4.

**Comment by RMerl** [comment]
USB 3 signals can emit radio frequencies within the 2.4 GHz frequency band.  This isn`t a firmware issue, this is inherent to the USB 3 technology, and generally requires a better shielded USB disk to avoid interference issues, or downgrading to USB 2.

https://www.intel.com/content/www/us/en/products/docs/io/universal-serial-bus/usb3-frequency-interference-paper.html
