### ISSUE TITLE
Channel not changing on Apply

### ISSUE THREAD

**Issue by feranick** [RMerl/asuswrt-merlin.ng#77]
Running 384-3beta1 on the rt-ac68u. When I change channel on either band and push "Apply", I would expect the change to take place, but the router seems to stick to the old channel. The only way to actually enable the change is a reboot. This has been the case all along the 384-3alphas. No problem with 380-69.

**Comment by RMerl** [comment]
Have you tested the final 384.3 release or the 384.4 alpha builds?

**Comment by feranick** [comment]
It's still there on 384.3. will test tonight on the 383.4 alpha.
