### ISSUE TITLE
LED lights on AiMesh Nodes turn on a few minutes after you turn them off. This is not an issue on the primary AiMesh router.

### ISSUE THREAD

**Issue by adamsiem** [RMerl/asuswrt-merlin.ng#776]
This is not an issue on the primary AiMesh router.

This experienced on RT-AC88U and RT-AC5300 (with an RT-AC5300 as the primary AiMesh router without LED issues).

This is occurring in firmware 386.2_6 and the prior release.

**Comment by RMerl** [comment]
Everything related to AiMesh is closed source and outside of my control.
