### ISSUE TITLE
Can't reach `router.asus.com` when custom DNS is set

### ISSUE THREAD

**Issue by maicol07** [RMerl/asuswrt-merlin.ng#780]
**Describe the bug**
`router.asus.com` can't be accessed when custom DNS is set from LAN --> DHCP Server --> DNS Server 1 and 2

**Model**
DSL-AX82U

**Firmware version**
386.03_1-gnuton0_alpha3

**Client information**
Browser: Firefox 91 x64

**To Reproduce**
1. Go to LAN --> DHCP Server
2. Set DNS Server 1 and 2 to something (i.e. Cloudflare ones (`1.1.1.1`/`1.0.0.1`) or Google ones (`8.8.8.8`/`8.8.4.4`)
3. After router reloading go to `router.asus.com` from your browser

**Expected behavior**
Web GUI can be reached through the link

**Actual results**
`router.asus.com` not working

**Screenshots**
Interestingely the GUI in the Administration --> Settings show that it can't be accessed from `router.asus.com`...
![immagine](https://user-images.githubusercontent.com/9463142/126748322-ae746e13-f48e-4616-b35d-87d361248ef3.png)

**Will this error be reproduced on the official firmware?**

**Comment by RMerl** [comment]
This is normal since you are bypassing the router's DNS server.  Google's DNS cannot know what's the LAN IP address of your router.
