### ISSUE TITLE
httpd starts on port 80 although not configured in settings

### ISSUE THREAD

**Issue by erikdewildt** [RMerl/asuswrt-merlin.ng#79]
Hi,

I have explicitly configured my RT-AC88U router to only use HTTPS as i'm running an NGINX reverse proxy on port 80. Since i've upgraded to 384.3_beta2 the httpd daemon starts at boot and occupies port 80.

> admin@RT-AC88U-0888:/tmp/home/root# netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
... ... ...
tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN      397/httpd

> admin@RT-AC88U-0888:/tmp/home/root# ps axf | grep http
 2648 pts/1    S+     0:00          \_ grep http
  396 ?        Ss     0:54 httpds -s -i br0 -p 8443
  397 ?        Ss     0:00 httpd -i br0

![asus_wireless_router_rt-ac88u_-_system](https://user-images.githubusercontent.com/6085985/36060241-ca2c9658-0e45-11e8-934b-fc8a9388229c.png)

Thanks!

**Comment by RMerl** [comment]
Asus does it on purpose for models with AiHome support, probably because the service relies on it.  As a workaround, move httpd to a different port.

```
nvram set http_lanport=81
nvram commit
service restart_httpd
```

**Comment by themiron** [comment]
@erikdewildt fyi, due closed source, asusnatnl, bwdpi blocking and aicloud redirect may not work properly after port change. this needs more updates from asus

**Comment by RMerl** [comment]
As long https is enabled tho he should be fine, those services should normally use https if http is listed as disabled.

**Comment by themiron** [comment]
right with doubts about asusnatnl, otherwise why httpd was kept running then?

**Comment by RMerl** [comment]
I don't know.  But since virtually nobody uses asusnatnl (it's for their AiHome solution), I doubt it would be a problem for @erikdewildt .

**Comment by erikdewildt** [comment]
@RMerl Indeed, that is no problem fo me. Your workaround works just fine. Thanks for the support!

**Comment by dreamwraith** [comment]
Would it be possible to add a configurable option to change this setting in the menu?
