### ISSUE TITLE
[384.3] Should not use RSA by default in httpd.

### ISSUE THREAD

**Issue by iMocW** [RMerl/asuswrt-merlin.ng#85]
It's an obsolete key exchange. In 382, it's using ECDHE_RSA, why this changed on 384.3.

**Comment by RMerl** [comment]
Nothing has been changed there.  My own browser is also using ECDHE when connecting:

```
The connection to this site is encrypted and authenticated using TLS 1.2 (a strong protocol), ECDHE_RSA with P-256 (a strong key exchange), and AES_128_GCM (a strong cipher).
```

**Comment by RMerl** [comment]
mssl.c was last changed 5 months ago - when the AM380 code was merged into this new repo.

https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src/router/mssl/mssl.c#L33

**Comment by iMocW** [comment]
Seems this randomly happens. Consider disabling explicitly RSA.
