### ISSUE TITLE
asus ac86u - samba CPU usage

### ISSUE THREAD

**Issue by lghinet** [RMerl/asuswrt-merlin.ng#87]
hello,
i have an asus ac86u (firmware: 384.3) with an USB stick (usb 3.0);
i activate the media server and samba share, all good, but when i try to copy a large file from my laptop(windows 8.1) to that samba share, the CPU is going to 100% (both cores ) and memory to 95% (on the router), after the upload is completed, the cpu goes down, but the memory does not.

the copying speed is 10MB/s, thats the write limit of my stick

is this ok ? 
thanks

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
