### ISSUE TITLE
Can I compile bcm96848 able to use RMerl firmware?

### ISSUE THREAD

**Issue by daiaji** [RMerl/asuswrt-merlin.ng#89]
https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src-rt-5.02hnd/kernel/dts/96848.dts
Does this mean that RMerl can work on the "96848 GPON / EPON board"?

**Comment by RMerl** [comment]
No, the firmware only works for the specific Asus models that are explicitely listed.  That file is simply a component of Broadcom's SDK for the HND platform, and Asus hasn't spent time filtering out which pieces are needed and which aren't.

**Comment by daiaji** [comment]
@RMerl I can understand that the Broadcom distributed SDK does not include drivers that allow Optical modem devices to work properly?
