### ISSUE TITLE
Remote Syslog Forwarding

### ISSUE THREAD

**Issue by Xboarder56** [RMerl/asuswrt-merlin.ng#90]
Perviously ASUSWRT-Merlin supported remote syslog destinations through the web interface. I can enable this through the CLI interface but this will not be maintained through a reboot. Will this feature be coming back or is it discontinued ?

**Comment by RMerl** [comment]
The setting is now on the System Log page itself.

**Comment by Xboarder56** [comment]
Ohh my bad sorry about that didn't notice it got switched around. When an IP is enter for the remote log server where does this go?

**Comment by RMerl** [comment]
It will be sent to whichever IP you enter on that page.

**Comment by Xboarder56** [comment]
Sorry I mean to say the config file that will be updated with the IP.

**Comment by RMerl** [comment]
There's no config file.  Asuswrt uses Busybox's syslogd, which can only be configured through command line switches - there's no config file.

**Comment by Xboarder56** [comment]
Ohh okay thanks for the help.
