### ISSUE TITLE
[Suggestion] Store authorized_keys in /jffs location

### ISSUE THREAD

**Issue by kolobock** [RMerl/asuswrt-merlin.ng#97]
Currently `sshd_authkeys` is stored in nvram and `sshd_*key`(dss, ecdsa, host) have moved into `/jffs/ssl` location (and it is perfect!)

Can we please store sshd_authkeys on jffs as well?

**Comment by RMerl** [comment]
After further investigation, doing so would break AiMesh functionality, as the router would no longer be able to push the keys to the nodes.
