### ISSUE TITLE
Browser cache wipe, why is that needed going to 384.x?

### ISSUE THREAD

**Issue by hanoii** [RMerl/asuswrt-merlin.ng#98]
I am about to move into a 384 and read on the changelog that both a factory reset and a browser cache wipe is recommended. I get the factory reset, but why the browser cache? Is that only for the admin site, or for everything?

Thanks for this great firmware.

**Comment by RMerl** [comment]
Numerous CSS changes between 380 and 384, causes the webui to fail to load properly unless you either clear the browser cache, or force reload the webui.  The simplest procedure was documented to avoid having to answer everyone's question on how to force a page reload on everyone's specific browser of choice.

Please use the support forums in the future for support requests.  The Github tracker is for development purposes only.
