### ISSUE TITLE
downloadmaster not running after updating to 384.3

### ISSUE THREAD

**Issue by the0ne** [RMerl/asuswrt-merlin.ng#99]
upgraded to 384.3
enabled let's encrypt => status OK
downloadmaster not accessible at https://router.asus.com:8481/downloadmaster/
=> because asus lighttpd cannot load the empty plain file server.pem residing in /opt/etc/asus_lighttpd

```
admin@dozer:/tmp/home/root# dir /opt/etc/asus_lighttpd
drwxrwxrwx    2 admin    root          4096 Mar  5 13:42 .
drwxr-xr-x   13 admin    root          4096 Mar  5 13:59 ..
-rwxrwxrwx    1 admin    root             0 Mar  5 12:47 server.pem
admin@dozer:/tmp/home/root# 

```
after linking the file to /etc/server.pem all is good again and downloadmaster can successfully start up

```
admin@dozer:/tmp/home/root# dir /opt/etc/asus_lighttpd
drwxrwxrwx    2 admin    root          4096 Mar  5 13:42 .
drwxr-xr-x   13 admin    root          4096 Mar  5 13:59 ..
lrwxrwxrwx    1 admin    root            15 Mar  5 13:42 server.pem -> /etc/server.pem
admin@dozer:/tmp/home/root# 

```

**Comment by RMerl** [comment]
Downloadmaster is not part of the firmware.  Any fix would have to come from Asus and be implemented in the downloadmaster package downloaded from their server.
